import type { Chapter } from "@/lib/types";

const chapter2: Chapter = {
  slug: "numbers-and-ticket",
  title: "Числа и билет",
  subtitle:
    "Сегодня Айдана учит тебя числам — без них не купить билет, не назвать возраст и не понять, во сколько рейс.",
  goals: [
    "считать от 1 до 10 и понимать числа на слух",
    "называть свой возраст и спрашивать чужой",
    "разбираться в анкете: имя и фамилия",
    "понимать время вылета",
  ],
  stages: [
    { icon: "🔢", name: "Числа" },
    { icon: "🎂", name: "Возраст" },
    { icon: "🎫", name: "Билет" },
    { icon: "🕐", name: "Время рейса" },
    { icon: "✅", name: "Готово" },
  ],
  steps: [
    {
      kind: "story",
      stage: 0,
      ru: "Айдана пишет на листке: one, two, three, four, five, six, seven, eight, nine, ten. «Это числа от 1 до 10. Сегодня они тебе понадобятся три раза!»",
    },
    {
      kind: "choice",
      stage: 0,
      tag: "Запомни числа",
      q: "Какое число «seven»?",
      note: "Считаем: one (1), two (2), three (3), four (4), five (5), six (6), seven (7), eight (8), nine (9), ten (10).",
      options: [{ t: "7", ok: true }, { t: "6" }, { t: "9" }],
      why: "Seven — 7. Счёт до десяти — фундамент: цены, время, номера рейсов — всё на числах.",
    },
    {
      kind: "listen",
      stage: 0,
      tag: "Аудирование",
      q: "Айдана называет число. Какое?",
      audio: "Three.",
      note: "Слушай внимательно: three (3) звучит как «сри», а tree («дерево») — почти так же. Не путай с two (2).",
      options: [{ t: "3", ok: true }, { t: "2" }, { t: "10" }],
      why: "Three — 3. Числа на слух — самое полезное умение: цены в магазине называют быстро!",
    },
    {
      kind: "story",
      stage: 1,
      ru: "«Теперь возраст, — говорит Айдана. — В анкете на визу и в отеле тебя спросят: How old are you? — Сколько тебе лет?» (дословно: «Насколько ты старый?» 🙂)",
    },
    {
      kind: "fill",
      stage: 1,
      tag: "Впиши слово",
      qBefore: "I ",
      qAfter: " twenty years old.",
      hintRu: "Мне двадцать лет. (говоришь про себя — «я»)",
      note: "Возраст говорят через связку: I am + число + years old. Помни: I → am, you → are. Twenty — двадцать.",
      rule: "to-be",
      answer: "am",
      why: "I am twenty years old — «Мне 20 лет». Меняешь число — и фраза готова для любого возраста.",
      phrase: { en: "I am … years old.", ru: "Мне … лет." },
    },
    {
      kind: "assemble",
      stage: 1,
      tag: "Собери фразу",
      q: "Спроси возраст у Айданы:",
      note: "How old — «насколько старый», are you — «есть ты». Порядок такой: How old + are + you?",
      rule: "question-words",
      words: ["How", "old", "are", "you?"],
      answer: "How old are you?",
      why: "How old are you? — «Сколько тебе лет?» Заметь: are стоит ПЕРЕД you, потому что это вопрос.",
      phrase: { en: "How old are you?", ru: "Сколько тебе лет?" },
    },
    {
      kind: "story",
      stage: 2,
      ru: "Пора проверить твой билет! Айдана открывает письмо от авиакомпании. Там два поля: «First name» и «Last name».",
    },
    {
      kind: "choice",
      stage: 2,
      tag: "Пойми анкету",
      q: "Что писать в поле «First name»?",
      note: "First — первый, last — последний. First name — «первое имя» (то, как тебя зовут), last name — фамилия.",
      options: [
        { t: "Имя", ok: true },
        { t: "Фамилию" },
        { t: "Город" },
      ],
      why: "First name — имя, last name (или surname) — фамилия. Эти поля есть в каждой анкете — запомни раз и навсегда.",
    },
    {
      kind: "story",
      stage: 3,
      ru: "Осталось главное — не проспать самолёт! Айдана читает билет вслух. Во сколько рейс?",
    },
    {
      kind: "listen",
      stage: 3,
      tag: "Аудирование",
      q: "Послушай Айдану. Во сколько вылет?",
      audio: "Your flight is at ten.",
      note: "Flight — рейс, at — в (о времени). Лови число после слова at!",
      options: [{ t: "В 10", ok: true }, { t: "В 3" }, { t: "В 7" }],
      why: "Your flight is at ten — «Твой рейс в десять». Число после at — это время.",
    },
    {
      kind: "assemble",
      stage: 3,
      tag: "Собери фразу",
      q: "Повтори время рейса, чтобы не забыть:",
      note: "Схема: The flight (рейс) + is (есть) + at ten (в десять).",
      words: ["The", "flight", "is", "at", "ten."],
      answer: "The flight is at ten.",
      why: "The flight is at ten — «Рейс в десять». Формула «… is at + время» подходит для всего: встреч, автобусов, кино.",
      phrase: { en: "The flight is at ten.", ru: "Рейс в десять." },
    },
    {
      kind: "story",
      stage: 4,
      ru: "«Отлично! — Айдана ставит тебе пятёрку. — Числа выучены, билет проверен. Завтра расскажешь мне о своей семье — по-английски!»",
    },
  ],
  words: [
    { en: "one … ten", ru: "один … десять" },
    { en: "twenty", ru: "двадцать" },
    { en: "years old", ru: "… лет (о возрасте)" },
    { en: "first name / last name", ru: "имя / фамилия" },
    { en: "flight", ru: "рейс" },
    { en: "at ten", ru: "в десять (о времени)" },
  ],
};

export default chapter2;
