import type { Chapter } from "@/lib/types";

const chapter3: Chapter = {
  slug: "my-family",
  title: "Моя семья",
  subtitle:
    "Айдана показывает фото своей семьи и учит тебя рассказывать о своей: мама, папа, брат, сестра — и волшебные слова he и she.",
  goals: [
    "представлять людей: «Это моя мама»",
    "рассказывать, кто есть в моей семье",
    "говорить о других через he и she",
  ],
  stages: [
    { icon: "📸", name: "Фото" },
    { icon: "👩", name: "Мама и папа" },
    { icon: "👦", name: "Брат и сестра" },
    { icon: "💬", name: "Он и она" },
    { icon: "⭐", name: "Твой рассказ" },
  ],
  steps: [
    {
      kind: "story",
      stage: 0,
      ru: "Айдана достаёт телефон: «В Лондоне тебя обязательно спросят о семье — это любимая тема для разговора. Смотри, это фото моей семьи». Она показывает на женщину на фото…",
    },
    {
      kind: "story",
      stage: 0,
      who: "Айдана",
      say: "This is my mother.",
      ru: "Это моя мама.",
    },
    {
      kind: "choice",
      stage: 1,
      tag: "Пойми фразу",
      q: "«This is my mother» — что сказала Айдана?",
      note: "This — это, is — есть, my — моя, mother — мама. Семья: mother — мама, father — папа, brother — брат, sister — сестра.",
      options: [
        { t: "Это моя мама", ok: true },
        { t: "Это моя сестра" },
        { t: "Моя мама дома" },
      ],
      why: "This is my… — «Это мой/моя…» — так представляют людей на фото и в жизни.",
      phrase: { en: "This is my mother.", ru: "Это моя мама." },
    },
    {
      kind: "fill",
      stage: 1,
      tag: "Впиши слово",
      qBefore: "This ",
      qAfter: " my father.",
      hintRu: "Это мой папа. (покажи на фото и представь его)",
      note: "После this всегда идёт связка is: This is… — «Это есть…». Father — папа.",
      answer: "is",
      why: "This is my father — «Это мой папа». Формула This is + человек работает для всей семьи и друзей.",
    },
    {
      kind: "assemble",
      stage: 2,
      tag: "Собери фразу",
      q: "Теперь про свою семью. Скажи: «У меня есть брат»:",
      note: "«У меня есть…» по-английски просто: I have + … . Have — «имею». A brother — брат (a — просто «один какой-то»).",
      rule: "have",
      words: ["I", "have", "a", "brother."],
      answer: "I have a brother.",
      why: "I have a brother — «У меня есть брат». I have — главная формула владения: I have a car, I have a dog…",
      phrase: { en: "I have a brother.", ru: "У меня есть брат." },
    },
    {
      kind: "listen",
      stage: 2,
      tag: "Аудирование",
      q: "Айдана говорит о своей семье. Сколько у неё сестёр?",
      audio: "I have two sisters.",
      note: "Лови число! Помни: two — 2, three — 3. Sisters — сёстры (буква s в конце = «много»).",
      options: [{ t: "Две", ok: true }, { t: "Три" }, { t: "Одна" }],
      why: "I have two sisters — «У меня две сестры». Буква -s в конце слова означает множественное число: sister → sisters.",
    },
    {
      kind: "story",
      stage: 3,
      ru: "«Теперь секретное оружие, — улыбается Айдана. — Слова he и she. He — он, she — она. Без них не рассказать ни про кого!» Она показывает на брата на фото: «He is a doctor» — он врач.",
    },
    {
      kind: "choice",
      stage: 3,
      tag: "Он или она?",
      q: "Ты рассказываешь про СЕСТРУ. Какое слово выбрать?",
      note: "He — он (про мужчин), she — она (про женщин), it — оно (про вещи).",
      options: [{ t: "She", ok: true }, { t: "He" }, { t: "It" }],
      why: "Сестра — she (она). Брат был бы he, а чемодан — it.",
    },
    {
      kind: "fill",
      stage: 3,
      tag: "Впиши слово",
      qBefore: "She ",
      qAfter: " a doctor.",
      hintRu: "Она врач. (расскажи о сестре)",
      note: "Наше правило-связка растёт: I → am, you → are, he/she/it → is. Здесь she — значит…",
      rule: "to-be",
      answer: "is",
      why: "She is a doctor — «Она врач». Теперь ты знаешь связку целиком: I am, you are, he/she/it is!",
    },
    {
      kind: "story",
      stage: 4,
      ru: "Финальное испытание: представь свою семью одной фразой — как будто показываешь фото новому знакомому в Лондоне.",
    },
    {
      kind: "assemble",
      stage: 4,
      tag: "Собери фразу",
      q: "Скажи: «Это моя семья»:",
      note: "Вспомни: This is + … — «Это …». Family — семья.",
      words: ["This", "is", "my", "family."],
      answer: "This is my family.",
      why: "This is my family — «Это моя семья». Покажешь фото в телефоне — и разговор пойдёт сам!",
      phrase: { en: "This is my family.", ru: "Это моя семья." },
    },
    {
      kind: "story",
      stage: 4,
      ru: "«Молодец! — Айдана собирает вещи. — Остался последний урок: собрать чемодан. Встретимся завтра — и по-английски, конечно!»",
    },
  ],
  words: [
    { en: "mother / father", ru: "мама / папа" },
    { en: "brother / sister", ru: "брат / сестра" },
    { en: "family", ru: "семья" },
    { en: "this is…", ru: "это…" },
    { en: "I have…", ru: "у меня есть…" },
    { en: "he / she", ru: "он / она" },
  ],
};

export default chapter3;
