import type { Chapter } from "@/lib/types";

const chapter4: Chapter = {
  slug: "packing",
  title: "Собираем чемодан",
  subtitle:
    "Последний урок перед вылетом: вещи, цвета и слово need. Собери чемодан по-английски — и ты готов к Лондону!",
  goals: [
    "называть одежду и вещи",
    "называть основные цвета",
    "говорить «мне нужно…» и отвечать на вопрос «У тебя есть…?»",
  ],
  stages: [
    { icon: "🧳", name: "Чемодан" },
    { icon: "👕", name: "Вещи" },
    { icon: "🎨", name: "Цвета" },
    { icon: "🛂", name: "Документы" },
    { icon: "🚀", name: "Готов!" },
  ],
  steps: [
    {
      kind: "story",
      stage: 0,
      ru: "Завтра вылет! Айдана приходит помочь собрать чемодан: «Собираем по-английски. Я называю вещь — ты кладёшь. Начнём с одежды».",
    },
    {
      kind: "choice",
      stage: 1,
      tag: "Выучи вещи",
      q: "Айдана просит положить «a T-shirt». Что кладём?",
      note: "Одежда: T-shirt — футболка, jacket — куртка, shoes — обувь. T-shirt легко запомнить: футболка похожа на букву T!",
      options: [{ t: "Футболку", ok: true }, { t: "Куртку" }, { t: "Ботинки" }],
      why: "T-shirt — футболка (по форме буквы T). Jacket — куртка, shoes — обувь.",
    },
    {
      kind: "listen",
      stage: 1,
      tag: "Аудирование",
      q: "Послушай, что говорит Айдана. Где лежит паспорт?",
      audio: "The passport is on the table.",
      note: "On — на (сверху). Лови слово после on — там и лежит паспорт. Table — стол.",
      options: [
        { t: "На столе", ok: true },
        { t: "В чемодане" },
        { t: "В куртке" },
      ],
      why: "The passport is on the table — «Паспорт на столе». Предлог on означает «на».",
    },
    {
      kind: "fill",
      stage: 2,
      tag: "Впиши слово",
      qBefore: "I ",
      qAfter: " a blue jacket.",
      hintRu: "У меня есть синяя куртка. (вспомни слово «имею» из урока о семье)",
      note: "«У меня есть…» = I have… (ты уже говорил так про брата!). Blue — синий.",
      rule: "have",
      answer: "have",
      why: "I have a blue jacket — «У меня есть синяя куртка». Заметь: цвет ставится ПЕРЕД вещью — blue jacket, а не jacket blue.",
    },
    {
      kind: "choice",
      stage: 2,
      tag: "Выучи цвета",
      q: "Какого цвета «a red T-shirt»?",
      note: "Цвета: red — красный, blue — синий, green — зелёный, black — чёрный, white — белый.",
      options: [{ t: "Красная", ok: true }, { t: "Синяя" }, { t: "Белая" }],
      why: "Red — красный. Пять главных цветов: red, blue, green, black, white — хватит на первое время.",
    },
    {
      kind: "story",
      stage: 3,
      ru: "Чемодан почти собран. «Стоп! — Айдана поднимает палец. — Самое важное. Есть слово need — „нужно“. Скажи, что тебе нужен паспорт!»",
    },
    {
      kind: "assemble",
      stage: 3,
      tag: "Собери фразу",
      q: "Скажи: «Мне нужен мой паспорт»:",
      note: "Need — нуждаться. Схема такая же, как с have: I need + вещь — «Мне нужно…».",
      words: ["I", "need", "my", "passport."],
      answer: "I need my passport.",
      why: "I need my passport — «Мне нужен паспорт». I need — фраза-спасатель: I need help (помощь), I need water (вода), I need a taxi!",
      phrase: { en: "I need my passport.", ru: "Мне нужен мой паспорт." },
    },
    {
      kind: "listen",
      stage: 3,
      tag: "Аудирование",
      q: "Айдана проверяет документы. Что она спрашивает?",
      audio: "Do you have your ticket?",
      note: "Do you have…? — «У тебя есть…?» Лови последнее слово: ticket — билет, passport — паспорт.",
      options: [
        { t: "Есть ли у тебя билет", ok: true },
        { t: "Есть ли у тебя паспорт" },
        { t: "Где твой чемодан" },
      ],
      why: "Do you have your ticket? — «У тебя есть билет?» Вопрос строится так: Do you have + вещь?",
      phrase: { en: "Do you have your ticket?", ru: "У тебя есть билет?" },
    },
    {
      kind: "choice",
      stage: 3,
      tag: "Выбери ответ",
      q: "Билет у тебя в руке. Что ответить?",
      note: "На вопрос Do you…? отвечают коротко: Yes, I do! — «Да!» или No, I don't — «Нет».",
      options: [{ t: "Yes, I do!", ok: true }, { t: "I am a ticket." }, { t: "Goodbye!" }],
      why: "Yes, I do! — «Да, есть!» А «I am a ticket» значило бы «я — билет» 🙂",
      phrase: { en: "Yes, I do!", ru: "Да! (ответ на вопрос с do)" },
    },
    {
      kind: "story",
      stage: 4,
      ru: "Чемодан закрыт, документы на месте. Айдана торжественно смотрит на тебя: «Скажи финальную фразу — и я тебя отпускаю!»",
    },
    {
      kind: "assemble",
      stage: 4,
      tag: "Собери фразу",
      q: "Скажи: «Я готов!»:",
      note: "Ready — готовый. Про себя говорим через am: I am ready.",
      words: ["I", "am", "ready!"],
      answer: "I am ready!",
      why: "I am ready! — «Я готов!» Курс Starter пройден. Дальше — сезон 1: твой самолёт уже приземляется в Лондоне!",
      phrase: { en: "I am ready!", ru: "Я готов(а)!" },
    },
  ],
  words: [
    { en: "T-shirt / jacket / shoes", ru: "футболка / куртка / обувь" },
    { en: "red, blue, green, black, white", ru: "красный, синий, зелёный, чёрный, белый" },
    { en: "on the table", ru: "на столе" },
    { en: "I need…", ru: "мне нужно…" },
    { en: "Do you have…?", ru: "у тебя есть…?" },
    { en: "ready", ru: "готовый" },
  ],
};

export default chapter4;
