import type { Chapter } from "@/lib/types";

const drills: Chapter = {
  slug: "drills",
  title: "Тренажёр: am / is / are и первые фразы",
  subtitle:
    "Быстрая тренировка без сюжета: связки, have, my/your, a/an и множественное число. Идеально после раздела «Правила».",
  section: "exercise",
  stages: [
    { icon: "🔗", name: "Связки" },
    { icon: "🎒", name: "Have" },
    { icon: "🏷️", name: "Артикли" },
    { icon: "👥", name: "Мн. число" },
    { icon: "✅", name: "Готово" },
  ],
  steps: [
    {
      kind: "fill",
      stage: 0,
      tag: "Связка to be",
      qBefore: "I ",
      qAfter: " from Almaty.",
      hintRu: "Я из Алматы. (правило: I → ?)",
      note: "Тройка связок: I → am, he/she/it → is, you/we/they → are.",
      answer: "am",
      why: "I am from Almaty. С «I» — всегда am.",
    },
    {
      kind: "fill",
      stage: 0,
      tag: "Связка to be",
      qBefore: "She ",
      qAfter: " a doctor.",
      hintRu: "Она врач. (she → ?)",
      answer: "is",
      why: "She is a doctor. He/she/it — is.",
    },
    {
      kind: "fill",
      stage: 0,
      tag: "Связка to be",
      qBefore: "They ",
      qAfter: " my friends.",
      hintRu: "Они мои друзья. (they → ?)",
      answer: "are",
      why: "They are my friends. You/we/they — are.",
    },
    {
      kind: "choice",
      stage: 0,
      tag: "Вопрос с to be",
      q: "Как спросить «Ты готов?»",
      note: "В вопросе to be перепрыгивает вперёд: You are ready → Are you ready?",
      options: [
        { t: "Are you ready?", ok: true },
        { t: "You are ready?" },
        { t: "Ready you are?" },
      ],
      why: "Are you ready? — глагол-связка встаёт перед подлежащим.",
    },
    {
      kind: "fill",
      stage: 1,
      tag: "Глагол have",
      qBefore: "We ",
      qAfter: " a big family.",
      hintRu: "У нас большая семья. (слово «имеем»)",
      answer: "have",
      why: "We have a big family — «у нас есть» = have.",
    },
    {
      kind: "choice",
      stage: 1,
      tag: "have или has",
      q: "Выбери правильную фразу про брата:",
      note: "С he/she/it форма have меняется на has.",
      options: [
        { t: "He has a car.", ok: true },
        { t: "He have a car." },
        { t: "He is a car." },
      ],
      why: "He has a car — с he форма has. (He is a car означало бы «он — машина» 🙂)",
    },
    {
      kind: "choice",
      stage: 2,
      tag: "Артикль",
      q: "Выбери правильный вариант:",
      note: "a — перед согласным звуком, an — перед гласным.",
      options: [
        { t: "an apple, a banana", ok: true },
        { t: "a apple, an banana" },
        { t: "an apple, an banana" },
      ],
      why: "an apple (гласный звук), a banana (согласный).",
    },
    {
      kind: "assemble",
      stage: 2,
      tag: "Притяжательные",
      q: "Скажи: «Это её паспорт»:",
      note: "her — её. Порядок: This is + her + вещь.",
      words: ["This", "is", "her", "passport."],
      answer: "This is her passport.",
      why: "This is her passport. Мой — my, твой — your, его — his, её — her.",
    },
    {
      kind: "choice",
      stage: 3,
      tag: "Мн. число",
      q: "Как будет «города» (city → ?)",
      note: "Согласная + y → -ies.",
      options: [{ t: "cities", ok: true }, { t: "citys" }, { t: "cityes" }],
      why: "city → cities: y после согласной меняется на -ies.",
    },
    {
      kind: "choice",
      stage: 3,
      tag: "Мн. число",
      q: "Какое слово — исключение во множественном числе?",
      note: "Несколько слов не берут -s, а меняются целиком.",
      options: [
        { t: "child → children", ok: true },
        { t: "book → bookes" },
        { t: "car → cares" },
      ],
      why: "child → children — исключение. book → books, car → cars — обычное правило.",
    },
    {
      kind: "assemble",
      stage: 4,
      tag: "Финал",
      q: "Собери фразу со всеми правилами сразу: «У меня есть две сестры»:",
      note: "I + have + two + sisters (мн. число!).",
      words: ["I", "have", "two", "sisters."],
      answer: "I have two sisters.",
      why: "I have two sisters — have + множественное число. Тренажёр пройден!",
    },
  ],
  words: [],
};

export default drills;
