import type { Chapter } from "@/lib/types";

const drills: Chapter = {
  slug: "drills-2",
  title: "Тренажёр 2: вопросы и отрицания",
  subtitle:
    "Вторая тренировка уровня: отрицания с not, вопросы с am/is/are, вопросительные слова и ответы Yes/No. Коротко и по делу.",
  section: "exercise",
  stages: [
    { icon: "🚫", name: "Отрицание" },
    { icon: "❓", name: "Вопрос" },
    { icon: "🧭", name: "Слова-вопросы" },
    { icon: "💬", name: "Ответы" },
    { icon: "✅", name: "Готово" },
  ],
  steps: [
    {
      kind: "fill",
      stage: 0,
      tag: "Отрицание",
      qBefore: "I am ",
      qAfter: " tired. Let's walk!",
      hintRu: "Я не устал. Пойдём гулять! (слово-отрицание после am)",
      note: "Отрицание с to be: am/is/are + not. I am not — «я не…».",
      answer: "not",
      why: "I am not tired — «Я не устал». Not встаёт сразу после связки.",
    },
    {
      kind: "choice",
      stage: 0,
      tag: "Отрицание",
      q: "Как сказать «Она не дома»?",
      note: "is + not = isn't. Отрицание всегда после связки.",
      options: [
        { t: "She is not at home.", ok: true },
        { t: "She not is at home." },
        { t: "Not she is at home." },
      ],
      why: "She is not at home — not идёт после is. Короткая форма: She isn't at home.",
    },
    {
      kind: "choice",
      stage: 1,
      tag: "Вопрос",
      q: "Преврати в вопрос: «It is far» (это далеко)?",
      note: "В вопросе связка перепрыгивает вперёд: It is → Is it…?",
      options: [
        { t: "Is it far?", ok: true },
        { t: "It is far?" },
        { t: "Far is it?" },
      ],
      why: "Is it far? — «Это далеко?» Связка is встала перед it.",
    },
    {
      kind: "fill",
      stage: 1,
      tag: "Вопрос",
      qBefore: "",
      qAfter: " you from Almaty?",
      hintRu: "Ты из Алматы? (связка для you — в начале вопроса)",
      note: "Вопрос с to be начинается со связки: Are you…? — «Ты…?»",
      answer: "are",
      why: "Are you from Almaty? — «Ты из Алматы?» Are первым, you вторым.",
    },
    {
      kind: "choice",
      stage: 2,
      tag: "Слова-вопросы",
      q: "Хочешь узнать, ГДЕ отель. С какого слова начать вопрос?",
      note: "What — что, Where — где, Who — кто, How — как.",
      options: [
        { t: "Where is the hotel?", ok: true },
        { t: "What is the hotel?" },
        { t: "Who is the hotel?" },
      ],
      why: "Where is the hotel? — «Где отель?» Where спрашивает о месте.",
    },
    {
      kind: "choice",
      stage: 2,
      tag: "Слова-вопросы",
      q: "Хочешь узнать ЦЕНУ чашки. Какой вопрос правильный?",
      note: "How much…? — сколько стоит. How old…? — сколько лет.",
      options: [
        { t: "How much is this cup?", ok: true },
        { t: "How old is this cup?" },
        { t: "Who is this cup?" },
      ],
      why: "How much is this cup? — «Сколько стоит эта чашка?» О цене — how much.",
    },
    {
      kind: "assemble",
      stage: 2,
      tag: "Слова-вопросы",
      q: "Спроси незнакомца, откуда он:",
      note: "«Откуда ты?» = Where are you from? Слово from («из») уходит в конец.",
      words: ["Where", "are", "you", "from?"],
      answer: "Where are you from?",
      why: "Where are you from? — «Откуда ты?» Запомни целиком: from всегда в конце этого вопроса.",
    },
    {
      kind: "choice",
      stage: 3,
      tag: "Короткий ответ",
      q: "«Do you have a ticket?» Билет у тебя есть. Ответ?",
      note: "Вопрос с do → ответ с do: Yes, I do / No, I don't.",
      options: [
        { t: "Yes, I do.", ok: true },
        { t: "Yes, I am." },
        { t: "Yes, I have do." },
      ],
      why: "Do you have…? → Yes, I do. Каким словом спросили, таким и отвечаем.",
    },
    {
      kind: "choice",
      stage: 3,
      tag: "Короткий ответ",
      q: "«Are you ready?» Ты готов. Ответ?",
      note: "Вопрос с are → ответ с am/are: Yes, I am.",
      options: [
        { t: "Yes, I am.", ok: true },
        { t: "Yes, I do." },
        { t: "Yes, I ready." },
      ],
      why: "Are you ready? → Yes, I am. Вопрос со связкой — ответ со связкой.",
    },
    {
      kind: "assemble",
      stage: 4,
      tag: "Финал",
      q: "Собери вежливое отрицание: «Извини, я не знаю»:",
      note: "«Не знаю» = I don't know (do + not + know). Sorry — извини.",
      words: ["Sorry,", "I", "don't", "know."],
      answer: "Sorry, I don't know.",
      why: "Sorry, I don't know — честный и вежливый ответ, который выручит в любом разговоре. Тренажёр пройден!",
    },
  ],
  words: [],
};

export default drills;
