import type { Chapter } from "@/lib/types";

const drills: Chapter = {
  slug: "drills-3",
  title: "Тренажёр 3: семья и «у меня есть»",
  subtitle:
    "Отработка юнита «Семья и принадлежность»: have / has и притяжательные местоимения my, your, his, her, our, their.",
  section: "exercise",
  stages: [
    { icon: "🎒", name: "Have / has" },
    { icon: "🔑", name: "Чьё это?" },
    { icon: "👤", name: "He или his?" },
    { icon: "✅", name: "Готово" },
  ],
  steps: [
    {
      kind: "choice",
      stage: 0,
      tag: "Have / has",
      q: "«У неё есть собака». Как правильно?",
      note: "С he/she/it форма have меняется на has.",
      options: [
        { t: "She has a dog.", ok: true },
        { t: "She have a dog." },
        { t: "She is a dog." },
      ],
      why: "She has a dog — с she форма has. (She is a dog значило бы «она — собака» 🙂)",
    },
    {
      kind: "fill",
      stage: 0,
      tag: "Have / has",
      qBefore: "They ",
      qAfter: " a small child.",
      hintRu: "У них есть маленький ребёнок. (they → have или has?)",
      note: "С I/you/we/they — всегда have.",
      answer: "have",
      why: "They have a small child — they берёт have, не has.",
    },
    {
      kind: "choice",
      stage: 0,
      tag: "Have / has",
      q: "«У моего брата есть машина». Выбери верный вариант:",
      note: "Brother — это he, значит форма has.",
      options: [
        { t: "My brother has a car.", ok: true },
        { t: "My brother have a car." },
        { t: "My brother is a car." },
      ],
      why: "My brother has a car — brother = he → has.",
    },
    {
      kind: "fill",
      stage: 1,
      tag: "Чьё это?",
      qBefore: "This is ",
      qAfter: " book.",
      hintRu: "Это моя книга. (какое слово значит «мой»?)",
      answer: "my",
      why: "This is my book — my значит «мой/моя».",
    },
    {
      kind: "fill",
      stage: 1,
      tag: "Чьё это?",
      qBefore: "Is this ",
      qAfter: " phone?",
      hintRu: "Это твой телефон? (какое слово значит «твой»?)",
      answer: "your",
      why: "Is this your phone? — your значит «твой/ваш».",
    },
    {
      kind: "choice",
      stage: 1,
      tag: "Чьё это?",
      q: "«Это её сумка». Как сказать правильно?",
      note: "her — её. Порядок: This is + her + вещь.",
      options: [
        { t: "This is her bag.", ok: true },
        { t: "This is she bag." },
        { t: "This is hers bag." },
      ],
      why: "This is her bag — перед предметом ставим her, а не she.",
    },
    {
      kind: "assemble",
      stage: 1,
      tag: "Чьё это?",
      q: "Скажи: «Это наш дом»:",
      note: "our — наш. Порядок: This is + our + house.",
      words: ["This", "is", "our", "house."],
      answer: "This is our house.",
      why: "This is our house — our перед словом house.",
    },
    {
      kind: "fill",
      stage: 1,
      tag: "Чьё это?",
      qBefore: "It is ",
      qAfter: " passport, not mine.",
      hintRu: "Это их паспорт, не мой. (какое слово значит «их»?)",
      answer: "their",
      why: "It is their passport — their значит «их».",
    },
    {
      kind: "choice",
      stage: 2,
      tag: "He или his?",
      q: "«Он мой брат. Его зовут Алим». Выбери верную пару:",
      note: "he — «он» (перед глаголом), his — «его» (перед предметом или именем).",
      options: [
        { t: "He is my brother. His name is Alim.", ok: true },
        { t: "His is my brother. He name is Alim." },
        { t: "He is my brother. He name is Alim." },
      ],
      why: "He is my brother — he перед глаголом is. His name — his перед словом name.",
    },
    {
      kind: "choice",
      stage: 2,
      tag: "She или her?",
      q: "«Она врач. Её сестра тоже врач». Выбери верную пару:",
      note: "she — перед глаголом, her — перед предметом.",
      options: [
        { t: "She is a doctor. Her sister is a doctor too.", ok: true },
        { t: "Her is a doctor. She sister is a doctor too." },
        { t: "She is a doctor. She sister is a doctor too." },
      ],
      why: "She is a doctor — she перед is. Her sister — her перед словом sister.",
    },
    {
      kind: "assemble",
      stage: 3,
      tag: "Финал",
      q: "Собери фразу со всеми правилами сразу: «У меня большая семья, и у неё тоже есть сестра»:",
      note: "I have + big family, and she has + a sister.",
      words: ["I", "have", "a", "big", "family,", "and", "she", "has", "a", "sister."],
      answer: "I have a big family, and she has a sister.",
      why: "I have… (я) и she has… (она) — have и has рядом в одной фразе. Тренажёр пройден!",
    },
  ],
  words: [],
};

export default drills;
