import type { Chapter } from "@/lib/types";

const drills: Chapter = {
  slug: "drills-4",
  title: "Тренажёр 4: вещи, артикли и вежливость",
  subtitle:
    "Отработка юнита «Вещи, артикли и вежливость»: a / an, множественное число, порядок слов и вежливые просьбы перед вылетом.",
  section: "exercise",
  stages: [
    { icon: "🏷️", name: "Артикли" },
    { icon: "👥", name: "Мн. число" },
    { icon: "🧭", name: "Порядок слов" },
    { icon: "🙏", name: "Вежливость" },
  ],
  steps: [
    {
      kind: "choice",
      stage: 0,
      tag: "a / an",
      q: "Выбери правильную пару:",
      note: "a — перед согласным звуком, an — перед гласным.",
      options: [
        { t: "a suitcase, an hour", ok: true },
        { t: "an suitcase, a hour" },
        { t: "a suitcase, a hour" },
      ],
      why: "a suitcase (согласный звук), an hour (h не читается, звук гласный).",
    },
    {
      kind: "fill",
      stage: 0,
      tag: "a / an",
      qBefore: "I need ",
      qAfter: " umbrella.",
      hintRu: "Мне нужен зонт. (umbrella начинается с гласного звука)",
      answer: "an",
      why: "an umbrella — перед гласным звуком u ставим an.",
    },
    {
      kind: "choice",
      stage: 0,
      tag: "a / an",
      q: "«Это старая карта». Какой артикль?",
      note: "old начинается с гласного звука.",
      options: [
        { t: "It is an old map.", ok: true },
        { t: "It is a old map." },
        { t: "It is an old maps." },
      ],
      why: "an old map — old начинается с гласного, значит an.",
    },
    {
      kind: "fill",
      stage: 1,
      tag: "Мн. число",
      qBefore: "I have three ",
      qAfter: ".",
      hintRu: "У меня три чемодана. (bag → мн. число)",
      answer: "bags",
      why: "bag → bags: обычное правило, просто +s.",
    },
    {
      kind: "choice",
      stage: 1,
      tag: "Мн. число",
      q: "Как будет «автобусы» (bus → ?)",
      note: "После -s, -sh, -ch, -x добавляется -es.",
      options: [
        { t: "buses", ok: true },
        { t: "buss" },
        { t: "buses'" },
      ],
      why: "bus → buses: после -s пишем -es.",
    },
    {
      kind: "choice",
      stage: 1,
      tag: "Мн. число",
      q: "Найди слово-исключение во множественном числе:",
      note: "man/woman меняются полностью, а не просто добавляют -s.",
      options: [
        { t: "man → men", ok: true },
        { t: "bag → bages" },
        { t: "phone → phones'" },
      ],
      why: "man → men — исключение. bag → bags, phone → phones — обычное правило.",
    },
    {
      kind: "assemble",
      stage: 2,
      tag: "Порядок слов",
      q: "Собери фразу: «Мне нравится этот аэропорт» (кто → действие → что):",
      note: "I (кто) + like (действие) + this airport (что). Порядок нельзя менять.",
      words: ["I", "like", "this", "airport."],
      answer: "I like this airport.",
      why: "I like this airport — строгий порядок: подлежащее, глагол, остальное.",
    },
    {
      kind: "choice",
      stage: 2,
      tag: "Порядок слов",
      q: "Какое предложение построено правильно?",
      note: "По-русски можно переставлять слова свободно, по-английски — нет.",
      options: [
        { t: "We have a big suitcase.", ok: true },
        { t: "A big suitcase we have." },
        { t: "Have we a big suitcase." },
      ],
      why: "We have a big suitcase — кто, действие, что. Другой порядок звучит неправильно.",
    },
    {
      kind: "choice",
      stage: 3,
      tag: "Вежливая просьба",
      q: "Хочешь заказать кофе в кафе. Как вежливо попросить?",
      note: "Can I have + предмет + please? — стандартная вежливая просьба о вещи.",
      options: [
        { t: "Can I have a coffee, please?", ok: true },
        { t: "Give me a coffee." },
        { t: "I want coffee now." },
      ],
      why: "Can I have a coffee, please? — вежливо и естественно. Give me звучит как приказ.",
    },
    {
      kind: "fill",
      stage: 3,
      tag: "Вежливая просьба",
      qBefore: "Can you help me, ",
      qAfter: "?",
      hintRu: "Можете мне помочь, пожалуйста? (волшебное слово вежливости)",
      answer: "please",
      why: "Can you help me, please? — please делает просьбу вежливой.",
    },
    {
      kind: "assemble",
      stage: 3,
      tag: "Финал",
      q: "Собери вежливую просьбу о действии: «Можете открыть окно, пожалуйста?»:",
      note: "Can you + действие + please? — просьба о действии, не о предмете.",
      words: ["Can", "you", "open", "the", "window,", "please?"],
      answer: "Can you open the window, please?",
      why: "Can you open the window, please? — вежливая просьба о действии. Тренажёр пройден!",
    },
  ],
  words: [],
};

export default drills;
