import type { Chapter } from "@/lib/types";

const exam: Chapter = {
  slug: "exam",
  title: "Экзамен уровня Starter",
  subtitle:
    "Айдана устраивает тебе выпускной экзамен: приветствие, числа, семья, вещи — плюс чтение и аудирование. Докажи, что готов к Лондону!",
  exam: true,
  stages: [
    { icon: "📝", name: "Слова и фразы" },
    { icon: "🔢", name: "Грамматика" },
    { icon: "📄", name: "Чтение" },
    { icon: "🎧", name: "Аудирование" },
    { icon: "🎓", name: "Результат" },
  ],
  steps: [
    {
      kind: "choice",
      stage: 0,
      tag: "Вопрос",
      q: "Незнакомец говорит тебе: «Hello! How are you?» Что он сказал?",
      options: [
        { t: "«Привет! Как дела?»", ok: true },
        { t: "«Пока! До завтра!»" },
        { t: "«Как тебя зовут?»" },
      ],
      why: "Hello — привет, How are you? — как дела? Ответить можно: I'm fine, thanks!",
    },
    {
      kind: "assemble",
      stage: 0,
      tag: "Собери фразу",
      q: "Познакомься: скажи «Приятно познакомиться!»",
      words: ["Nice", "to", "meet", "you!"],
      answer: "Nice to meet you!",
      why: "Nice to meet you! — говорят сразу после знакомства.",
    },
    {
      kind: "choice",
      stage: 0,
      tag: "Вопрос",
      q: "Какое число «eight»?",
      options: [{ t: "8", ok: true }, { t: "3" }, { t: "10" }],
      why: "Eight — 8. Счёт: one, two, three, four, five, six, seven, eight, nine, ten.",
    },
    {
      kind: "fill",
      stage: 1,
      tag: "Впиши слово",
      qBefore: "How old ",
      qAfter: " you?",
      hintRu: "Сколько тебе лет? (связка для you)",
      rule: "to-be",
      answer: "are",
      why: "You дружит с are: How old are you? — «Сколько тебе лет?»",
    },
    {
      kind: "fill",
      stage: 1,
      tag: "Впиши слово",
      qBefore: "I ",
      qAfter: " a brother and two sisters.",
      hintRu: "У меня есть брат и две сестры. (слово «имею»)",
      rule: "have",
      answer: "have",
      why: "I have… — «у меня есть…». Работает с семьёй, вещами и чем угодно.",
    },
    {
      kind: "fill",
      stage: 1,
      tag: "Впиши слово",
      qBefore: "This ",
      qAfter: " my father. He is a teacher.",
      hintRu: "Это мой папа. Он учитель. (связка после this)",
      rule: "to-be",
      answer: "is",
      why: "This is my father — «Это мой папа». Полная тройка связок: I am, you are, he/she/it is.",
    },
    {
      kind: "reading",
      stage: 2,
      tag: "Чтение",
      title: "Записка на холодильнике",
      note: "Экзаменационное чтение: прочитай записку и ответь на два вопроса. Подглядывать в текст можно!",
      text: [
        "Good morning!",
        "Your breakfast is on the table.",
        "I need my blue jacket today — it is not in my room. Where is it?",
        "Call me! — Mum",
      ],
      questions: [
        {
          q: "Где завтрак?",
          options: [{ t: "На столе", ok: true }, { t: "В холодильнике" }, { t: "В комнате" }],
          why: "Your breakfast is on the table — «Твой завтрак на столе». On — на.",
        },
        {
          q: "Что ищет мама?",
          options: [
            { t: "Синюю куртку", ok: true },
            { t: "Синюю футболку" },
            { t: "Телефон" },
          ],
          why: "I need my blue jacket — «Мне нужна моя синяя куртка». Blue — синий, jacket — куртка.",
        },
      ],
    },
    {
      kind: "listening",
      stage: 3,
      tag: "Аудирование",
      intro: "Голосовое сообщение от Айданы — финальное задание!",
      note: "Слушай столько раз, сколько нужно. Лови число и действие.",
      audio: [
        "Hello! It's Aidana.",
        "Your exam is great!",
        "The lesson tomorrow is at five.",
        "Don't be late! Bye!",
      ],
      questions: [
        {
          q: "Во сколько завтра урок?",
          options: [{ t: "В 5", ok: true }, { t: "В 9" }, { t: "В 10" }],
          why: "The lesson tomorrow is at five — «Урок завтра в пять». Five — 5.",
        },
        {
          q: "О чём просит Айдана в конце?",
          options: [
            { t: "Не опаздывать", ok: true },
            { t: "Позвонить ей" },
            { t: "Принести тетрадь" },
          ],
          why: "Don't be late! — «Не опаздывай!»",
        },
      ],
    },
    {
      kind: "assemble",
      stage: 4,
      tag: "Финал экзамена",
      q: "Последняя фраза — скажи, что ты готов:",
      words: ["I", "am", "ready!"],
      answer: "I am ready!",
      why: "I am ready! — «Я готов!» Экзамен Starter завершён.",
    },
  ],
  words: [],
};

export default exam;
