import type { Chapter } from "@/lib/types";

const chapter6: Chapter = {
  slug: "going-home",
  title: "Домой!",
  subtitle:
    "Последний день в Лондоне: прощание с Данияром, аэропорт и первое слово о прошлом — was. Финал сезона!",
  goals: [
    "говорить о прошлом через was",
    "благодарить и прощаться",
    "ориентироваться в аэропорту по указателям",
    "понимать объявления о рейсах",
  ],
  stages: [
    { icon: "📆", name: "Последний день" },
    { icon: "🤗", name: "Прощание" },
    { icon: "🚕", name: "В аэропорт" },
    { icon: "🛫", name: "Вылет" },
    { icon: "🏠", name: "Домой" },
  ],
  steps: [
    {
      kind: "story",
      stage: 0,
      en: "Your last day in London. The suitcase is ready — now it is {heavier|тяжелее}: souvenirs! Daniyar comes to say goodbye.",
      ru: "Твой последний день в Лондоне. Чемодан собран — теперь он тяжелее: сувениры! Данияр приходит попрощаться.",
    },
    {
      kind: "story",
      stage: 0,
      who: "Данияр",
      say: "So… did you like London?",
      ru: "Ну что… понравился тебе Лондон?",
    },
    {
      kind: "fill",
      stage: 0,
      tag: "Впиши слово",
      qBefore: "Yes! The trip ",
      qAfter: " amazing!",
      hintRu: "Да! Поездка была потрясающей! (нужна связка «был/была» — прошлое от is)",
      note: "Знакомая связка is умеет говорить о прошлом: is («есть») → was («был/была»). Поездка (trip) — «она/оно», значит в прошлом — was.",
      answer: "was",
      why: "The trip was amazing! — «Поездка была потрясающей!» Was — это is в прошлом. Первый шаг к рассказам о том, что было.",
      phrase: { en: "It was amazing!", ru: "Это было потрясающе!" },
    },
    {
      kind: "assemble",
      stage: 1,
      tag: "Собери фразу",
      q: "Поблагодари Данияра за всё:",
      note: "Thank you for… — «спасибо за…». Everything — всё (ты уже знаешь это слово из отеля!).",
      words: ["Thank", "you", "for", "everything!"],
      answer: "Thank you for everything!",
      why: "Thank you for everything! — «Спасибо за всё!» После for можно назвать что угодно: thank you for the help, for the tea…",
      phrase: { en: "Thank you for everything!", ru: "Спасибо за всё!" },
    },
    {
      kind: "story",
      stage: 1,
      who: "Данияр",
      say: "Come back next summer! And write to me!",
      ru: "Возвращайся следующим летом! И пиши мне!",
    },
    {
      kind: "choice",
      stage: 1,
      tag: "Пойми фразу",
      q: "«Come back next summer!» — что сказал Данияр?",
      note: "Come back — возвращайся, next — следующий, summer — лето.",
      options: [
        { t: "Возвращайся следующим летом", ok: true },
        { t: "Уезжай до лета" },
        { t: "Напиши мне летом" },
      ],
      why: "Come back next summer! — «Возвращайся следующим летом!» Похоже, у истории будет продолжение…",
    },
    {
      kind: "story",
      stage: 2,
      en: "The taxi to the airport. You look at London through the window: Big Ben, the river, red buses. You will miss this city.",
      ru: "Такси в аэропорт. Ты смотришь на Лондон через окно: Биг-Бен, река, красные автобусы. Ты будешь скучать по этому городу.",
    },
    {
      kind: "choice",
      stage: 3,
      tag: "Пойми знак",
      q: "В аэропорту два указателя. Тебе куда — ты улетаешь?",
      note: "Departures — вылеты (от depart — отправляться), arrivals — прилёты (от arrive — прибывать).",
      options: [
        { t: "DEPARTURES", ok: true },
        { t: "ARRIVALS" },
        { t: "WAY OUT" },
      ],
      why: "Departures — вылеты, тебе туда. Arrivals — прилёты (там ты был в первой главе!), way out — выход.",
    },
    {
      kind: "listen",
      stage: 3,
      tag: "Аудирование",
      q: "Объявление в аэропорту! Во сколько твой рейс в Алматы?",
      audio: "The flight to Almaty is at six.",
      note: "Лови число после at — это время. Six — 6, seven — 7.",
      options: [{ t: "В 6", ok: true }, { t: "В 7" }, { t: "В 10" }],
      why: "The flight to Almaty is at six — «Рейс в Алматы в шесть». Аэропортные объявления ты теперь понимаешь на слух!",
    },
    {
      kind: "fill",
      stage: 3,
      tag: "Впиши слово",
      qBefore: "Excuse me, where ",
      qAfter: " gate B7?",
      hintRu: "Извините, где выход B7? (формула из музея и багажа — она всегда одна)",
      note: "Where is + место = «Где …?». Gate — выход на посадку. Ты спрашивал так про чемодан и музей — третий раз будет легко!",
      answer: "is",
      why: "Where is gate B7? — «Где выход B7?» Одна формула провела тебя через весь Лондон.",
    },
    {
      kind: "story",
      stage: 4,
      en: "You sit by the window. The plane goes up. Goodbye, London! In your phone — a message from Daniyar: «Safe flight, friend!»",
      ru: "Ты садишься у окна. Самолёт взлетает. До свидания, Лондон! В телефоне — сообщение от Данияра: «Хорошего полёта, друг!»",
    },
    {
      kind: "assemble",
      stage: 4,
      tag: "Собери фразу",
      q: "Ответь Данияру — до скорой встречи:",
      note: "See you — увидимся, soon — скоро. Ты знаешь все эти слова — осталось собрать!",
      words: ["Thanks!", "See", "you", "soon!"],
      answer: "Thanks! See you soon!",
      why: "See you soon! — «До скорого!» Сезон 1 пройден. Герой вернётся в Лондон — уже на уровне A2!",
      phrase: { en: "See you soon!", ru: "До скорого!" },
    },
  ],
  words: [
    { en: "was", ru: "был, была (прошлое от is)" },
    { en: "trip", ru: "поездка" },
    { en: "amazing", ru: "потрясающий" },
    { en: "departures / arrivals", ru: "вылеты / прилёты" },
    { en: "gate", ru: "выход на посадку" },
    { en: "soon", ru: "скоро" },
  ],
};

export default chapter6;
