import type { Chapter } from "@/lib/types";

const chapter2: Chapter = {
  slug: "first-day-in-the-city",
  title: "Первый день в городе",
  subtitle:
    "Метро, дорога до музея и новое знакомство — учимся спрашивать и понимать ответы.",
  goals: [
    "покупать билет в метро",
    "спрашивать дорогу и понимать ответ",
    "понимать городские указатели",
    "знакомиться и договариваться о встрече",
  ],
  stages: [
    { icon: "🚇", name: "Метро" },
    { icon: "🗺️", name: "Улица" },
    { icon: "🏛️", name: "Музей" },
    { icon: "🥪", name: "Ланч" },
    { icon: "👋", name: "Знакомство" },
  ],
  steps: [
    {
      kind: "story",
      stage: 0,
      en: "Morning! Today you want to visit the British Museum. First — the {underground|метро}. You go to the {ticket office|билетная касса}.",
      ru: "Утро! Сегодня ты хочешь сходить в Британский музей. Сначала — метро. Ты подходишь к кассе.",
    },
    {
      kind: "story",
      stage: 0,
      who: "Кассир в метро",
      say: "Hello! Single or return?",
      ru: "Здравствуйте! В одну сторону или туда-обратно?",
    },
    {
      kind: "choice",
      stage: 0,
      tag: "Выбери ответ",
      q: "Тебе нужен билет туда и обратно. Что сказать?",
      note: "Билеты в Британии: single — в одну сторону, return — туда и обратно (от слова «вернуться»).",
      options: [
        { t: "A return, please.", ok: true },
        { t: "Yes, hello!" },
        { t: "I am single." },
      ],
      why: "A return, please — «туда-обратно, пожалуйста». Осторожно: «I am single» значит «я не женат/не замужем» 🙂",
      phrase: { en: "A return, please.", ru: "Туда-обратно, пожалуйста." },
    },
    {
      kind: "story",
      stage: 1,
      en: "You get off the train and go up to the {street|улица}. So many people! But… where is the museum? You ask a woman with a dog.",
      ru: "Ты выходишь из поезда и поднимаешься на улицу. Сколько людей! Но… где музей? Ты спрашиваешь женщину с собакой.",
    },
    {
      kind: "fill",
      stage: 1,
      tag: "Впиши слово",
      qBefore: "Excuse me, where ",
      qAfter: " the museum?",
      hintRu: "Извините, где музей?",
      note: "Помнишь из первой главы? Where is + вещь/место = «Где …?». Музей — это «оно» (it), а it дружит с is.",
      answer: "is",
      why: "Where is the museum? — «Где музей?» Ты уже спрашивал так про чемодан — формула одна и та же!",
      phrase: { en: "Excuse me, where is the museum?", ru: "Извините, где музей?" },
    },
    {
      kind: "story",
      stage: 1,
      who: "Женщина с собакой",
      say: "Go straight and turn left. It's five minutes.",
      ru: "…",
    },
    {
      kind: "choice",
      stage: 1,
      tag: "Пойми ответ",
      q: "Что сказала женщина: «Go straight and turn left»?",
      note: "Слова для дороги: go — иди, straight — прямо, turn — поверни, left — налево, right — направо.",
      options: [
        { t: "Иди прямо и поверни налево", ok: true },
        { t: "Иди назад и поверни направо" },
        { t: "Садись на автобус" },
      ],
      why: "Go straight — иди прямо, turn left — поверни налево. Запомни пару: left — налево, right — направо.",
    },
    {
      kind: "story",
      stage: 2,
      en: "The museum is huge and beautiful. On the door you see a sign: «FREE ENTRY».",
      ru: "Музей огромный и красивый. На двери табличка: «FREE ENTRY».",
    },
    {
      kind: "choice",
      stage: 2,
      tag: "Пойми знак",
      q: "Что значит «FREE ENTRY»?",
      note: "Free — бесплатный, entry — вход (от слова enter — входить).",
      options: [
        { t: "Вход бесплатный", ok: true },
        { t: "Вход закрыт" },
        { t: "Только для своих" },
      ],
      why: "Вход бесплатный! Британский музей и правда не берёт денег за вход.",
    },
    {
      kind: "story",
      stage: 3,
      en: "Two hours later you are hungry. In the museum café you want a {sandwich|сэндвич} and an orange juice.",
      ru: "Через два часа ты проголодался. В кафе музея ты хочешь сэндвич и апельсиновый сок.",
    },
    {
      kind: "assemble",
      stage: 3,
      tag: "Собери фразу",
      q: "Закажи сэндвич вежливо:",
      note: "Формула заказа из первой главы: Can I have + еда + please? — «Можно мне + … + пожалуйста?»",
      rule: "can",
      words: ["Can", "I", "have", "a", "sandwich,", "please?"],
      answer: "Can I have a sandwich, please?",
      why: "Та же формула, что и с чаем. Один раз выучил — заказываешь что угодно и где угодно.",
      phrase: { en: "Can I have a sandwich, please?", ru: "Можно мне сэндвич, пожалуйста?" },
    },
    {
      kind: "story",
      stage: 4,
      en: "At your table sits a student with a Kazakhstan flag sticker on his laptop! He smiles at you.",
      ru: "За твоим столиком сидит студент — на его ноутбуке наклейка с флагом Казахстана! Он улыбается тебе.",
    },
    {
      kind: "story",
      stage: 4,
      who: "Студент",
      say: "Hi! I'm Daniyar. What's your name?",
      ru: "Привет! Я Данияр. Как тебя зовут?",
    },
    {
      kind: "fill",
      stage: 4,
      tag: "Впиши слово",
      qBefore: "Nice to meet you! I ",
      qAfter: " from Kazakhstan too!",
      hintRu: "Приятно познакомиться! Я тоже из Казахстана!",
      note: "Правило-связка: I → am, you → are, he/she/it → is. Здесь говоришь про себя — «я»…",
      answer: "am",
      why: "I дружит с am: I am from Kazakhstan — «Я из Казахстана». Теперь ты знаешь всю тройку: am, are, is!",
      phrase: { en: "Nice to meet you!", ru: "Приятно познакомиться!" },
    },
    {
      kind: "assemble",
      stage: 4,
      tag: "Собери фразу",
      q: "Данияр зовёт тебя завтра гулять по городу. Согласись и попрощайся:",
      note: "Great! — «Отлично!». See you! — «Увидимся!» (дословно «увижу тебя»). Tomorrow — завтра.",
      words: ["Great!", "See", "you", "tomorrow!"],
      answer: "Great! See you tomorrow!",
      why: "See you tomorrow! — «До завтра!» Так прощаются, когда договорились встретиться.",
      phrase: { en: "See you tomorrow!", ru: "До завтра!" },
    },
  ],
  words: [
    { en: "underground", ru: "метро (брит.)" },
    { en: "return (ticket)", ru: "билет туда-обратно" },
    { en: "straight", ru: "прямо" },
    { en: "turn left / right", ru: "поверни налево / направо" },
    { en: "free entry", ru: "вход бесплатный" },
    { en: "sandwich", ru: "сэндвич" },
  ],
};

export default chapter2;
