import type { Chapter } from "@/lib/types";

const chapter3: Chapter = {
  slug: "walk-with-daniyar",
  title: "Прогулка с Данияром",
  subtitle:
    "Новый друг показывает тебе Лондон: учимся говорить, что нам нравится, спрашивать время и понимать знаменитое «Mind the gap!».",
  goals: [
    "говорить, что мне нравится",
    "спрашивать и понимать время",
    "предлагать что-то сделать вместе",
    "понимать объявления в метро",
  ],
  stages: [
    { icon: "🤝", name: "Встреча" },
    { icon: "🚶", name: "Прогулка" },
    { icon: "🕒", name: "Время" },
    { icon: "🚇", name: "Метро" },
    { icon: "🌇", name: "Вечер" },
  ],
  steps: [
    {
      kind: "story",
      stage: 0,
      en: "Next morning. Daniyar {waits|ждёт} for you near the hotel. He knows London very well — he studies here!",
      ru: "Следующее утро. Данияр ждёт тебя у отеля. Он отлично знает Лондон — он здесь учится!",
    },
    {
      kind: "story",
      stage: 0,
      who: "Данияр",
      say: "Do you like London?",
      ru: "Тебе нравится Лондон?",
    },
    {
      kind: "choice",
      stage: 0,
      tag: "Выбери ответ",
      q: "Лондон тебе очень нравится. Что ответить?",
      note: "Like — нравиться. На вопрос Do you like…? отвечают: Yes, I do! (да) или No, I don't (нет). Very much — очень.",
      rule: "do-does",
      options: [
        { t: "Yes, I do! I like it very much!", ok: true },
        { t: "No, thank you." },
        { t: "I am from Kazakhstan." },
      ],
      why: "Yes, I do! I like it very much! — «Да! Мне очень нравится!» Короткое Yes, I do отвечает на сам вопрос, остальное — добавка.",
      phrase: { en: "I like it very much!", ru: "Мне очень нравится!" },
    },
    {
      kind: "story",
      stage: 1,
      en: "You walk along the {river|река} Thames. Big Ben, the London Eye… Daniyar tells stories about every place.",
      ru: "Вы идёте вдоль Темзы. Биг-Бен, «Лондонский глаз»… Данияр рассказывает истории о каждом месте.",
    },
    {
      kind: "assemble",
      stage: 1,
      tag: "Собери фразу",
      q: "Скажи Данияру, что тебе нравится этот город:",
      note: "Схема простая: I like + что нравится. This city — этот город.",
      words: ["I", "like", "this", "city!"],
      answer: "I like this city!",
      why: "I like this city! — «Мне нравится этот город!» После I like можно ставить что угодно: I like tea, I like music…",
      phrase: { en: "I like this city!", ru: "Мне нравится этот город!" },
    },
    {
      kind: "story",
      stage: 2,
      ru: "Вы гуляете уже давно. Пора спросить время — заодно и потренироваться!",
    },
    {
      kind: "assemble",
      stage: 2,
      tag: "Собери фразу",
      q: "Спроси у Данияра, который час:",
      note: "«Который час?» = What time is it? Дословно: «Что за время есть оно?» Просто запомни целиком — это готовая фраза.",
      words: ["What", "time", "is", "it?"],
      answer: "What time is it?",
      why: "What time is it? — «Который час?» Одна из самых частых фраз в языке.",
      phrase: { en: "What time is it?", ru: "Который час?" },
    },
    {
      kind: "listen",
      stage: 2,
      tag: "Аудирование",
      q: "Послушай ответ Данияра. Который час?",
      audio: "It's three o'clock.",
      note: "O'clock значит «ровно» (о часах). Лови число перед o'clock: three — 3, four — 4.",
      options: [{ t: "Ровно три", ok: true }, { t: "Ровно четыре" }, { t: "Половина третьего" }],
      why: "It's three o'clock — «Ровно три часа». Ответ о времени всегда начинается с It's… — «Сейчас…».",
      phrase: { en: "It's three o'clock.", ru: "Ровно три часа." },
    },
    {
      kind: "story",
      stage: 3,
      en: "Daniyar smiles: «Let's go to Camden Market by tube!» In the underground you hear a famous announcement…",
      ru: "Данияр улыбается: «Поехали на рынок Кэмден на метро!» В метро ты слышишь знаменитое объявление…",
    },
    {
      kind: "listen",
      stage: 3,
      tag: "Аудирование",
      q: "Что объявили в метро?",
      audio: "Mind the gap!",
      note: "Mind — «берегись, обрати внимание», gap — щель (между поездом и платформой). Это объявление — символ лондонского метро!",
      options: [
        { t: "Осторожно, щель между поездом и платформой", ok: true },
        { t: "Поезд дальше не идёт" },
        { t: "Уступайте места" },
      ],
      why: "Mind the gap! — «Осторожно, щель!» Эту фразу печатают на футболках и кружках — главный сувенир Лондона.",
      phrase: { en: "Mind the gap!", ru: "Осторожно, щель! (метро Лондона)" },
    },
    {
      kind: "choice",
      stage: 3,
      tag: "Пойми фразу",
      q: "Данияр говорит: «Let's go!» Что это значит?",
      note: "Let's = let us — «давай мы». Let's go — приглашение что-то сделать вместе.",
      options: [{ t: "Пойдём!", ok: true }, { t: "Подожди!" }, { t: "Смотри!" }],
      why: "Let's go! — «Пойдём!» Формула Let's + действие зовёт с собой: Let's eat! Let's play!",
      phrase: { en: "Let's go!", ru: "Пойдём!" },
    },
    {
      kind: "story",
      stage: 4,
      en: "Evening. You are tired but very happy. Daniyar has an idea: «Tomorrow — Camden Market. You need pounds and good shoes!»",
      ru: "Вечер. Ты устал, но очень доволен. У Данияра идея: «Завтра — рынок Кэмден. Понадобятся фунты и удобная обувь!»",
    },
    {
      kind: "fill",
      stage: 4,
      tag: "Впиши слово",
      qBefore: "Today ",
      qAfter: " a great day!",
      hintRu: "Сегодня отличный день! (день — это «оно»)",
      note: "Правило-связка: I → am, you → are, he/she/it → is. День (day) — это «оно», значит…",
      answer: "is",
      why: "Today is a great day! — «Сегодня отличный день!» Простая фраза, которая всегда поднимает настроение собеседнику.",
      phrase: { en: "Today is a great day!", ru: "Сегодня отличный день!" },
    },
  ],
  words: [
    { en: "like", ru: "нравиться" },
    { en: "city", ru: "город" },
    { en: "What time is it?", ru: "который час?" },
    { en: "o'clock", ru: "ровно (о часах)" },
    { en: "let's go", ru: "пойдём" },
    { en: "mind the gap", ru: "осторожно, щель (метро)" },
  ],
};

export default chapter3;
