import type { Chapter } from "@/lib/types";

const chapter5: Chapter = {
  slug: "hotel-problem",
  title: "Проблема в отеле",
  subtitle:
    "В номере нет полотенец, а душ сломался. Учимся вежливо жаловаться, просить помощи и понимать ответ ресепшена.",
  goals: [
    "сообщать о проблеме через there is / there are",
    "говорить, что вещь не работает",
    "вежливо просить починить",
    "понимать ответ сотрудника отеля",
  ],
  stages: [
    { icon: "🏨", name: "Номер" },
    { icon: "😱", name: "Проблема" },
    { icon: "📞", name: "Ресепшен" },
    { icon: "🔧", name: "Решение" },
    { icon: "😌", name: "Всё хорошо" },
  ],
  steps: [
    {
      kind: "story",
      stage: 0,
      en: "You come back to the hotel with your bags. You want a hot {shower|душ}… but wait. Something is wrong!",
      ru: "Ты возвращаешься в отель с покупками. Мечтаешь о горячем душе… но стоп. Что-то не так!",
    },
    {
      kind: "story",
      stage: 1,
      en: "There is no {towel|полотенце} in the bathroom. And the shower doesn't work! Time to call the reception.",
      ru: "В ванной нет полотенца. А душ не работает! Пора звонить на ресепшен.",
    },
    {
      kind: "assemble",
      stage: 1,
      tag: "Собери фразу",
      q: "Сообщи о проблеме — начни с главного:",
      note: "«Есть проблема» по-английски: There is a problem. There is значит «имеется, есть» (о том, что где-то находится).",
      rule: "there-is-are",
      words: ["There", "is", "a", "problem", "in", "my", "room."],
      answer: "There is a problem in my room.",
      why: "There is a problem in my room — «В моём номере проблема». There is — так говорят обо всём, что где-то есть: There is a café near the hotel.",
      phrase: { en: "There is a problem in my room.", ru: "В моём номере проблема." },
    },
    {
      kind: "fill",
      stage: 2,
      tag: "Впиши слово",
      qBefore: "There ",
      qAfter: " no towels in the bathroom.",
      hintRu: "В ванной нет полотенец. (полотенца — их много!)",
      note: "There is — про ОДНУ вещь, there are — про НЕСКОЛЬКО. Towels — полотенца (много). Значит…",
      answer: "are",
      why: "There are no towels — «Полотенец нет». Одна вещь → there is, много → there are.",
    },
    {
      kind: "story",
      stage: 2,
      who: "Ресепшен",
      say: "I'm so sorry to hear that! What is the problem?",
      ru: "Мне очень жаль! Что случилось?",
    },
    {
      kind: "choice",
      stage: 2,
      tag: "Пойми ответ",
      q: "«I'm so sorry to hear that» — что сказали на ресепшене?",
      note: "Sorry — жаль, to hear — слышать. Дословно: «Мне так жаль это слышать». Это вежливое сочувствие, а не извинение за вину.",
      options: [
        { t: "Мне очень жаль это слышать", ok: true },
        { t: "Я вас не слышу" },
        { t: "Перезвоните позже" },
      ],
      why: "I'm sorry to hear that — стандартное вежливое сочувствие. Услышишь его каждый раз, когда рассказываешь о проблеме.",
      phrase: { en: "I'm sorry to hear that.", ru: "Мне жаль это слышать." },
    },
    {
      kind: "assemble",
      stage: 3,
      tag: "Собери фразу",
      q: "Опиши вторую проблему — душ не работает:",
      note: "Work — работать. «Не работает» = doesn't work. Так говорят про любую сломанную вещь: The TV doesn't work.",
      rule: "do-does",
      words: ["The", "shower", "doesn't", "work."],
      answer: "The shower doesn't work.",
      why: "The shower doesn't work — «Душ не работает». Формула «… doesn't work» спасёт с любой поломкой: Wi-Fi, телевизор, кондиционер.",
      phrase: { en: "It doesn't work.", ru: "Это не работает." },
    },
    {
      kind: "listen",
      stage: 3,
      tag: "Аудирование",
      q: "Послушай ответ ресепшена. Что они сделают?",
      audio: "We will send new towels and fix the shower.",
      note: "Send — прислать, fix — починить. Лови два действия в одной фразе!",
      options: [
        { t: "Пришлют полотенца и починят душ", ok: true },
        { t: "Переселят в другой номер" },
        { t: "Вернут деньги" },
      ],
      why: "We will send new towels and fix the shower — «Мы пришлём новые полотенца и починим душ». Will — «сделаем» (обещание).",
    },
    {
      kind: "fill",
      stage: 3,
      tag: "Впиши слово",
      qBefore: "Can you ",
      qAfter: " it today, please?",
      hintRu: "Вы можете починить это сегодня, пожалуйста? (слово «починить» только что прозвучало)",
      note: "Просьба-формула из главы про такси: Can you + действие + please? Починить — fix.",
      answer: "fix",
      why: "Can you fix it today, please? — «Можете починить сегодня?» Вежливо, но настойчиво — как раз то, что нужно.",
      phrase: { en: "Can you fix it, please?", ru: "Можете это починить?" },
    },
    {
      kind: "story",
      stage: 4,
      en: "Twenty minutes later: fresh towels, working shower. A man from the reception asks: «Is everything OK now?»",
      ru: "Через двадцать минут: свежие полотенца, рабочий душ. Сотрудник ресепшена спрашивает: «Теперь всё в порядке?»",
    },
    {
      kind: "choice",
      stage: 4,
      tag: "Финальный ответ",
      q: "Всё починили. Что ответить?",
      note: "Everything — всё. «Всё отлично, спасибо» = Everything is great, thank you!",
      options: [
        { t: "Everything is great, thank you!", ok: true },
        { t: "There is a problem!" },
        { t: "It's too expensive!" },
      ],
      why: "Everything is great, thank you! — «Всё отлично, спасибо!» Проблема решена — и решил её ты, по-английски!",
      phrase: { en: "Everything is great!", ru: "Всё отлично!" },
    },
  ],
  words: [
    { en: "there is / there are", ru: "есть, имеется (одно / много)" },
    { en: "towel", ru: "полотенце" },
    { en: "shower", ru: "душ" },
    { en: "it doesn't work", ru: "не работает" },
    { en: "fix", ru: "починить" },
    { en: "everything", ru: "всё" },
  ],
};

export default chapter5;
