import type { Chapter } from "@/lib/types";

const chapter4: Chapter = {
  slug: "camden-market",
  title: "Рынок Кэмден",
  subtitle:
    "Шумный рынок, яркие футболки и торг за сувениры: учимся спрашивать цену, понимать ответ и говорить «беру!».",
  goals: [
    "вежливо отвечать продавцу",
    "спрашивать цену за одну вещь и за несколько",
    "торговаться и говорить «слишком дорого»",
    "завершать покупку",
  ],
  stages: [
    { icon: "🏪", name: "Рынок" },
    { icon: "👟", name: "Примерка" },
    { icon: "💷", name: "Цена" },
    { icon: "🤔", name: "Дорого!" },
    { icon: "🛍️", name: "Покупка" },
  ],
  steps: [
    {
      kind: "story",
      stage: 0,
      en: "Camden Market is loud and colourful! Music, street food, hundreds of small {shops|магазинчики}. A seller smiles at you…",
      ru: "Рынок Кэмден — шумный и яркий! Музыка, уличная еда, сотни лавочек. Продавец улыбается тебе…",
    },
    {
      kind: "story",
      stage: 0,
      who: "Продавец",
      say: "Hello! Can I help you?",
      ru: "Здравствуйте! Вам помочь?",
    },
    {
      kind: "choice",
      stage: 0,
      tag: "Выбери ответ",
      q: "Ты пока просто смотришь. Что вежливо ответить?",
      note: "Если просто разглядываешь товары, говорят: I'm just looking, thanks — «Я просто смотрю, спасибо». Just — просто, looking — смотрю.",
      options: [
        { t: "I'm just looking, thanks!", ok: true },
        { t: "Yes, I do!" },
        { t: "Where is my suitcase?" },
      ],
      why: "I'm just looking, thanks! — «Я просто смотрю, спасибо». Волшебная фраза для любого магазина — продавец не будет мешать.",
      phrase: { en: "I'm just looking, thanks!", ru: "Я просто смотрю, спасибо!" },
    },
    {
      kind: "story",
      stage: 1,
      en: "But then you see them: perfect {trainers|кроссовки}! You want to know the price.",
      ru: "И тут ты видишь их: идеальные кроссовки! Надо узнать цену.",
    },
    {
      kind: "assemble",
      stage: 1,
      tag: "Собери фразу",
      q: "Спроси, сколько стоят эти кроссовки:",
      note: "Про ОДНУ вещь спрашивают How much is…, а про НЕСКОЛЬКО (кроссовки — их два!) — How much are… These — эти.",
      rule: "how-much-many",
      words: ["How", "much", "are", "these", "trainers?"],
      answer: "How much are these trainers?",
      why: "How much are these trainers? — «Сколько стоят эти кроссовки?» Одна вещь → is, много → are: How much is this cup? / How much are these shoes?",
      phrase: { en: "How much are these?", ru: "Сколько стоят эти?" },
    },
    {
      kind: "listen",
      stage: 2,
      tag: "Аудирование",
      q: "Послушай продавца. Сколько стоят кроссовки?",
      audio: "They are thirty pounds.",
      note: "Pounds — фунты (деньги Британии). Лови число: thirteen — 13, thirty — 30. Они звучат похоже — это ловушка для всех новичков!",
      options: [{ t: "30 фунтов", ok: true }, { t: "13 фунтов" }, { t: "3 фунта" }],
      why: "They are thirty pounds — «Они стоят 30 фунтов». Thirteen (13) и thirty (30) путают даже продвинутые — переспрашивать не стыдно!",
    },
    {
      kind: "story",
      stage: 3,
      ru: "Тридцать фунтов?! Дороговато. Данияр шепчет: «Скажи, что это дорого — здесь можно торговаться!»",
    },
    {
      kind: "choice",
      stage: 3,
      tag: "Поторгуйся",
      q: "Как сказать «это слишком дорого»?",
      note: "Expensive — дорогой, cheap — дешёвый, too — слишком. «Слишком дорого» = too expensive.",
      options: [
        { t: "It's too expensive!", ok: true },
        { t: "It's too cheap!" },
        { t: "It's very nice!" },
      ],
      why: "It's too expensive! — «Слишком дорого!» После этой фразы на рынке цена часто волшебным образом падает 🙂",
      phrase: { en: "It's too expensive!", ru: "Это слишком дорого!" },
    },
    {
      kind: "story",
      stage: 3,
      who: "Продавец",
      say: "OK, OK… Twenty pounds for you, my friend!",
      ru: "Ладно, ладно… Для тебя — двадцать фунтов, друг мой!",
    },
    {
      kind: "fill",
      stage: 4,
      tag: "Впиши слово",
      qBefore: "Can I ",
      qAfter: " these trainers, please?",
      hintRu: "Можно мне эти кроссовки, пожалуйста? (вспомни формулу заказа из кафе)",
      note: "Та же формула, что с чаем и сэндвичем: Can I have + вещь + please? Работает и в кафе, и в магазине.",
      answer: "have",
      why: "Can I have these trainers, please? — «Можно мне эти кроссовки?» Одна формула — тысяча ситуаций.",
    },
    {
      kind: "assemble",
      stage: 4,
      tag: "Собери фразу",
      q: "Цена отличная — соглашайся! Скажи «Я беру их!»:",
      note: "Take — брать. «Беру!» по-английски: I'll take… (I'll = I will — «я возьму»). Them — их.",
      words: ["I'll", "take", "them!"],
      answer: "I'll take them!",
      why: "I'll take them! — «Беру их!» Финальная фраза любой удачной покупки.",
      phrase: { en: "I'll take it!", ru: "Я беру! (о покупке)" },
    },
    {
      kind: "story",
      stage: 4,
      en: "New trainers, a red London T-shirt and a small Big Ben for your mother. Daniyar laughs: «You are a real Londoner now!»",
      ru: "Новые кроссовки, красная футболка «London» и маленький Биг-Бен для мамы. Данияр смеётся: «Ну всё, ты теперь настоящий лондонец!»",
    },
  ],
  words: [
    { en: "How much is / are…?", ru: "сколько стоит / стоят…?" },
    { en: "pounds", ru: "фунты" },
    { en: "expensive / cheap", ru: "дорогой / дешёвый" },
    { en: "too", ru: "слишком" },
    { en: "trainers", ru: "кроссовки" },
    { en: "I'll take it!", ru: "беру!" },
  ],
};

export default chapter4;
