import type { Chapter } from "@/lib/types";

const chapter1: Chapter = {
  slug: "arrival-in-london",
  title: "Прилёт в Лондон",
  subtitle:
    "Паспортный контроль, багаж, такси и первая чашка чая — пройди день, отвечая по-английски.",
  goals: [
    "отвечать на вопросы на паспортном контроле",
    "спрашивать, где находится нужная вещь или место",
    "вежливо просить о помощи",
    "делать заказ в кафе и спрашивать цену",
  ],
  stages: [
    { icon: "✈️", name: "Посадка" },
    { icon: "🛂", name: "Паспортный контроль" },
    { icon: "🧳", name: "Багаж" },
    { icon: "🚕", name: "Такси" },
    { icon: "☕", name: "Кафе" },
  ],
  steps: [
    {
      kind: "story",
      stage: 0,
      en: "The {plane|самолёт} {lands|приземляется} in London. You are {tired|уставший} but happy. Welcome to England!",
      ru: "Самолёт приземляется в Лондоне. Ты устал, но счастлив.",
    },
    {
      kind: "story",
      stage: 1,
      who: "Офицер на паспортном контроле",
      say: "Good morning! What is the purpose of your visit?",
      ru: "Доброе утро! Какова цель вашего визита?",
    },
    {
      kind: "choice",
      stage: 1,
      tag: "Выбери ответ",
      q: "Что ответить офицеру?",
      note: "Purpose of visit значит «цель визита». Отвечают по формуле: I'm here on… — «Я здесь в/по…». Holiday — отпуск.",
      options: [
        { t: "I'm here on holiday.", ok: true },
        { t: "Yes, please." },
        { t: "My name is Alex." },
      ],
      why: "«Я здесь в отпуске» — именно такого ответа ждёт офицер. Два других варианта отвечают на другие вопросы.",
      phrase: { en: "I'm here on holiday.", ru: "Я здесь в отпуске." },
    },
    {
      kind: "story",
      stage: 2,
      en: "You go to get your {suitcase|чемодан}. But you don't see it! You ask a worker for help.",
      ru: "Ты идёшь за чемоданом. Но его не видно! Ты просишь работника помочь.",
    },
    {
      kind: "assemble",
      stage: 2,
      tag: "Собери фразу",
      q: "Спроси, где твой чемодан:",
      note: "Спросить «Где …?» очень просто: Where is + вещь. Where — где, is — есть, my — мой.",
      words: ["Where", "is", "my", "suitcase?"],
      answer: "Where is my suitcase?",
      why: "Where is my suitcase? — «Где (есть) мой чемодан?» Слово is по-русски не переводим, но в английском оно обязательно.",
      phrase: { en: "Where is my suitcase?", ru: "Где мой чемодан?" },
    },
    {
      kind: "story",
      stage: 2,
      en: "The worker smiles and points: your suitcase is here! Now you follow the sign: «EXIT — WAY OUT».",
      ru: "Работник улыбается и показывает: вот твой чемодан! Теперь ты идёшь по указателю.",
    },
    {
      kind: "choice",
      stage: 2,
      tag: "Пойми знак",
      q: "Что значит указатель «EXIT — WAY OUT»?",
      note: "Way — путь, out — наружу. Попробуй догадаться: «путь наружу» — это что?",
      options: [{ t: "Выход", ok: true }, { t: "Вход" }, { t: "Осторожно" }],
      why: "EXIT и WAY OUT — оба значат «выход». В Британии чаще пишут WAY OUT, в Америке — EXIT.",
    },
    {
      kind: "story",
      stage: 3,
      who: "Таксист",
      say: "Hello! Where are you going?",
      ru: "Привет! Куда вы едете?",
    },
    {
      kind: "fill",
      stage: 3,
      tag: "Впиши слово",
      qBefore: "Where ",
      qAfter: " you going?",
      hintRu: "Куда вы едете?",
      note: "В английском есть маленькое слово-связка «есть». Оно меняется: I → am, you → are, he/she/it → is. Здесь у нас you — значит…",
      answer: "are",
      why: "You всегда дружит с are: Where are you going? — «Куда вы едете?»",
    },
    {
      kind: "story",
      stage: 3,
      en: "You show the address of your hotel. The taxi drives through London. You see Big Ben! Suddenly you can't open the {window|окно}. You ask the driver:",
      ru: "Ты показываешь адрес отеля. Такси едет через Лондон. Ты видишь Биг-Бен! Вдруг у тебя не открывается окно, и ты просишь водителя:",
    },
    {
      kind: "assemble",
      stage: 3,
      tag: "Собери фразу",
      q: "Вежливо попроси о помощи:",
      note: "Просьба строится по формуле: Can you + действие + please? — «Можете ли вы + … + пожалуйста?». Help me — помочь мне.",
      rule: "can",
      words: ["Can", "you", "help", "me,", "please?"],
      answer: "Can you help me, please?",
      why: "Can you help me, please? — «Можете мне помочь, пожалуйста?» Эта формула работает с любой просьбой.",
      phrase: { en: "Can you help me, please?", ru: "Вы можете мне помочь, пожалуйста?" },
    },
    {
      kind: "story",
      stage: 4,
      en: "Evening. You are at a small café near the hotel. It smells like fresh {pastry|выпечка}. Time for real English tea!",
      ru: "Вечер. Ты в маленьком кафе рядом с отелем. Пахнет свежей выпечкой. Время настоящего английского чая!",
    },
    {
      kind: "choice",
      stage: 4,
      tag: "Сделай заказ",
      q: "Как вежливо заказать чай?",
      note: "Заказ в кафе — почти та же формула, что и просьба: Can I have + напиток + please? — «Можно мне + … + пожалуйста?»",
      options: [
        { t: "Can I have a tea, please?", ok: true },
        { t: "Give me tea!" },
        { t: "I am a tea." },
      ],
      why: "«Give me tea!» звучит грубо — как приказ. А «I am a tea» значит «я — чай» 🙂",
      phrase: { en: "Can I have a tea, please?", ru: "Можно мне чай, пожалуйста?" },
    },
    {
      kind: "fill",
      stage: 4,
      tag: "Впиши слово",
      qBefore: "How much ",
      qAfter: " it?",
      hintRu: "Сколько это стоит?",
      note: "Вспомни правило-связку: I → am, you → are, he/she/it → is. Здесь «it» — чай, о котором ты спрашиваешь.",
      rule: "how-much-many",
      answer: "is",
      why: "It дружит с is: How much is it? — «Сколько это стоит?» Пригодится в каждом магазине.",
      phrase: { en: "How much is it?", ru: "Сколько это стоит?" },
    },
    {
      kind: "story",
      stage: 4,
      who: "Бариста",
      say: "That's two pounds. Have a nice day!",
      ru: "Два фунта. Хорошего дня!",
    },
    {
      kind: "choice",
      stage: 4,
      tag: "Финальный ответ",
      q: "Что ответить бариста?",
      note: "Have a nice day! — «Хорошего дня!» На такие пожелания отвечают: you too — «и вам тоже».",
      options: [
        { t: "Thank you, you too!", ok: true },
        { t: "Two pounds." },
        { t: "Where are you going?" },
      ],
      why: "«Спасибо, и вам!» — вежливо и просто. Так отвечают на любое доброе пожелание.",
      phrase: { en: "Thank you, you too!", ru: "Спасибо, и вам!" },
    },
  ],
  words: [
    { en: "plane", ru: "самолёт" },
    { en: "suitcase", ru: "чемодан" },
    { en: "way out", ru: "выход" },
    { en: "holiday", ru: "отпуск" },
    { en: "window", ru: "окно" },
    { en: "tired", ru: "уставший" },
  ],
};

export default chapter1;
