import type { Chapter } from "@/lib/types";

const drills: Chapter = {
  slug: "drills-u2",
  title: "Тренажёр: дорога и предлоги",
  subtitle: "Отработка юнита «Дорога и предлоги»: in / on / at и this / that / these / those.",
  section: "exercise",
  stages: [
    { icon: "📍", name: "Предлоги" },
    { icon: "👉", name: "This / that" },
    { icon: "✅", name: "Готово" },
  ],
  steps: [
    {
      kind: "choice",
      stage: 0,
      tag: "Предлоги",
      q: "Ключи лежат ВНУТРИ сумки. Какой предлог?",
      note: "in — внутри чего-то.",
      options: [
        { t: "The keys are in the bag.", ok: true },
        { t: "The keys are on the bag." },
        { t: "The keys are at the bag." },
      ],
      why: "in the bag — ключи внутри сумки.",
    },
    {
      kind: "fill",
      stage: 0,
      tag: "Предлоги",
      qBefore: "The cup is ",
      qAfter: " the table.",
      hintRu: "Чашка на столе. (на поверхности)",
      answer: "on",
      why: "on the table — на поверхности стола.",
    },
    {
      kind: "choice",
      stage: 0,
      tag: "Предлоги",
      q: "«Встретимся у входа в пять». Какая пара предлогов верна?",
      note: "at + точка места, at + время.",
      options: [
        { t: "at the entrance at five", ok: true },
        { t: "in the entrance on five" },
        { t: "on the entrance in five" },
      ],
      why: "at the entrance at five — at для точки и для времени.",
    },
    {
      kind: "fill",
      stage: 0,
      tag: "Предлоги направления",
      qBefore: "I go ",
      qAfter: " work at nine.",
      hintRu: "Я иду на работу в девять. (движение куда-то)",
      answer: "to",
      why: "go to work — to показывает направление движения.",
    },
    {
      kind: "choice",
      stage: 1,
      tag: "This / that",
      q: "В руках у тебя карта (она рядом). Как спросить, где вокзал, показывая на карту?",
      note: "this — этот предмет рядом с тобой.",
      options: [
        { t: "Where is the station on this map?", ok: true },
        { t: "Where is the station on that map?" },
        { t: "Where is the station on these map?" },
      ],
      why: "this map — карта у тебя в руках, значит рядом.",
    },
    {
      kind: "choice",
      stage: 1,
      tag: "These / those",
      q: "Указываешь на туфли в витрине (они далеко, за стеклом). Как спросить цену?",
      note: "those — предметы вдалеке, во множественном числе.",
      options: [
        { t: "How much are those shoes?", ok: true },
        { t: "How much are these shoes?" },
        { t: "How much is that shoes?" },
      ],
      why: "those shoes — далеко и во множественном числе.",
    },
    {
      kind: "fill",
      stage: 1,
      tag: "This / these",
      qBefore: "",
      qAfter: " is my seat.",
      hintRu: "Это моё место. (место рядом, единственное число)",
      answer: "This",
      why: "This is my seat — this для одного предмета рядом.",
    },
    {
      kind: "assemble",
      stage: 2,
      tag: "Финал",
      q: "Собери вопрос: «Извините, где ближайшая станция метро?»",
      note: "Excuse me, where is + the nearest + предмет?",
      words: ["Excuse", "me,", "where", "is", "the", "nearest", "metro", "station?"],
      answer: "Excuse me, where is the nearest metro station?",
      why: "Excuse me, where is the nearest metro station? — вежливый вопрос о дороге. Тренажёр пройден!",
    },
  ],
  words: [],
};

export default drills;
