import type { Chapter } from "@/lib/types";

const drills: Chapter = {
  slug: "drills-u5",
  title: "Тренажёр: что где есть",
  subtitle: "Отработка юнита «Что где есть»: there is / there are, вопросы и отрицания.",
  section: "exercise",
  stages: [
    { icon: "📦", name: "There is / are" },
    { icon: "❓", name: "Вопрос и отрицание" },
    { icon: "✅", name: "Готово" },
  ],
  steps: [
    {
      kind: "fill",
      stage: 0,
      tag: "There is",
      qBefore: "There ",
      qAfter: " a café near the hotel.",
      hintRu: "Рядом с отелем есть кафе. (кафе — одно)",
      answer: "is",
      why: "There is a café — один предмет → is.",
    },
    {
      kind: "fill",
      stage: 0,
      tag: "There are",
      qBefore: "There ",
      qAfter: " two windows in the room.",
      hintRu: "В комнате два окна. (окон — два)",
      answer: "are",
      why: "There are two windows — несколько предметов → are.",
    },
    {
      kind: "choice",
      stage: 0,
      tag: "There is / are",
      q: "«В городе много хороших ресторанов». Как сказать?",
      note: "Many restaurants — множественное число → are.",
      options: [
        { t: "There are many good restaurants in the city.", ok: true },
        { t: "There is many good restaurants in the city." },
        { t: "It has many good restaurants in the city." },
      ],
      why: "There are many good restaurants — many restaurants требует are.",
    },
    {
      kind: "choice",
      stage: 1,
      tag: "Вопрос",
      q: "Хочешь узнать, есть ли в номере wi-fi. Как спросить?",
      note: "Вопрос: Is there…? для одного предмета.",
      options: [
        { t: "Is there wi-fi in the room?", ok: true },
        { t: "There is wi-fi in the room?" },
        { t: "Is wi-fi there in the room?" },
      ],
      why: "Is there wi-fi in the room? — is выходит вперёд в вопросе.",
    },
    {
      kind: "fill",
      stage: 1,
      tag: "Вопрос",
      qBefore: "",
      qAfter: " there any towels in the bathroom?",
      hintRu: "В ванной есть полотенца? (полотенец может быть несколько)",
      answer: "Are",
      why: "Are there any towels…? — вопрос про несколько предметов начинается с Are.",
    },
    {
      kind: "choice",
      stage: 1,
      tag: "Отрицание — проблема",
      q: "Сообщаешь: «В номере нет горячей воды». Как сказать?",
      note: "there is no + предмет — отрицание без глагола not.",
      options: [
        { t: "There is no hot water in the room.", ok: true },
        { t: "There is not hot water in the room." },
        { t: "There no is hot water in the room." },
      ],
      why: "There is no hot water — устойчивая форма отрицания there is no.",
    },
    {
      kind: "assemble",
      stage: 2,
      tag: "Финал",
      q: "Собери жалобу на ресепшене: «Извините, в моём номере нет полотенец»:",
      note: "Excuse me, there are no + towels + in my room.",
      words: ["Excuse", "me,", "there", "are", "no", "towels", "in", "my", "room."],
      answer: "Excuse me, there are no towels in my room.",
      why: "Excuse me, there are no towels in my room — вежливо сообщаем о проблеме. Тренажёр пройден!",
    },
  ],
  words: [],
};

export default drills;
