import type { Chapter } from "@/lib/types";

const drills: Chapter = {
  slug: "drills-u4",
  title: "Тренажёр: покупки и описания",
  subtitle: "Отработка юнита «Покупки и описания»: место прилагательного в предложении.",
  section: "exercise",
  stages: [
    { icon: "🎨", name: "Прилагательные" },
    { icon: "🛍️", name: "На рынке" },
    { icon: "✅", name: "Готово" },
  ],
  steps: [
    {
      kind: "choice",
      stage: 0,
      tag: "Место прилагательного",
      q: "«У меня синяя куртка». Как правильно?",
      note: "Прилагательное — перед существительным.",
      options: [
        { t: "I have a blue jacket.", ok: true },
        { t: "I have a jacket blue." },
        { t: "I have blue a jacket." },
      ],
      why: "a blue jacket — цвет всегда перед словом jacket.",
    },
    {
      kind: "fill",
      stage: 0,
      tag: "Место прилагательного",
      qBefore: "It is a ",
      qAfter: " city.",
      hintRu: "Это красивый город. (прилагательное перед city)",
      answer: "beautiful",
      why: "a beautiful city — прилагательное перед существительным.",
    },
    {
      kind: "choice",
      stage: 0,
      tag: "Мн. число + прилагательное",
      q: "«Большие дома» — как правильно?",
      note: "Прилагательные не меняются по числу: big, а не bigs.",
      options: [
        { t: "big houses", ok: true },
        { t: "bigs houses" },
        { t: "houses big" },
      ],
      why: "big houses — прилагательное big не берёт -s, даже если предметов много.",
    },
    {
      kind: "assemble",
      stage: 1,
      tag: "На рынке",
      q: "Скажи продавцу: «Это слишком дорого»:",
      note: "It is + too + expensive — «это слишком дорого».",
      words: ["It", "is", "too", "expensive."],
      answer: "It is too expensive.",
      why: "It is too expensive — стандартная фраза, чтобы поторговаться.",
    },
    {
      kind: "choice",
      stage: 1,
      tag: "На рынке",
      q: "Хочешь купить старую красную сумку. Как описать её продавцу?",
      note: "Несколько прилагательных подряд — тоже перед существительным, по порядку.",
      options: [
        { t: "I want this old red bag.", ok: true },
        { t: "I want this red old bag, no wait, bag old red." },
        { t: "I want this bag old red." },
      ],
      why: "this old red bag — оба прилагательных перед словом bag.",
    },
    {
      kind: "fill",
      stage: 1,
      tag: "На рынке",
      qBefore: "Can you make it ",
      qAfter: "?",
      hintRu: "Можете сделать подешевле? (сравнительная форма слова cheap)",
      answer: "cheaper",
      why: "Can you make it cheaper? — стандартная фраза при торге на рынке.",
    },
    {
      kind: "assemble",
      stage: 2,
      tag: "Финал",
      q: "Собери фразу: «Я не хочу этот дорогой чёрный чемодан»:",
      note: "I don't want + this + прилагательные + suitcase.",
      words: ["I", "don't", "want", "this", "expensive", "black", "suitcase."],
      answer: "I don't want this expensive black suitcase.",
      why: "I don't want this expensive black suitcase — оба прилагательных перед suitcase. Тренажёр пройден!",
    },
  ],
  words: [],
};

export default drills;
