import type { Chapter } from "@/lib/types";

const drills: Chapter = {
  slug: "drills-2",
  title: "Тренажёр 2: Present Continuous и предлоги",
  subtitle:
    "Вторая тренировка уровня A1: действие «прямо сейчас», выбор между Simple и Continuous, предлоги in/on/at и счёт how much / how many.",
  section: "exercise",
  stages: [
    { icon: "⏱️", name: "Прямо сейчас" },
    { icon: "⚖️", name: "Simple или Continuous" },
    { icon: "📍", name: "Предлоги" },
    { icon: "🔢", name: "Сколько?" },
    { icon: "✅", name: "Готово" },
  ],
  steps: [
    {
      kind: "fill",
      stage: 0,
      tag: "Прямо сейчас",
      qBefore: "Quiet, please! The baby ",
      qAfter: " sleeping.",
      hintRu: "Тише, пожалуйста! Малыш спит (прямо сейчас). (связка для he/she/it)",
      note: "Процесс сейчас: am/is/are + глагол-ing. Малыш — это he/she, значит связка…",
      answer: "is",
      why: "The baby is sleeping — «Малыш спит». Is + sleeping = процесс идёт прямо сейчас.",
    },
    {
      kind: "choice",
      stage: 0,
      tag: "Прямо сейчас",
      q: "Как сказать «Я сейчас читаю»?",
      note: "I + am + глагол-ing.",
      options: [
        { t: "I am reading now.", ok: true },
        { t: "I reading now." },
        { t: "I am read now." },
      ],
      why: "I am reading now — связка am и окончание -ing обязательны вместе.",
    },
    {
      kind: "assemble",
      stage: 0,
      tag: "Прямо сейчас",
      q: "Скажи по телефону: «Мы едем домой»:",
      note: "Процесс в момент речи: We are + going + home.",
      words: ["We", "are", "going", "home", "now."],
      answer: "We are going home now.",
      why: "We are going home now — «Мы сейчас едем домой». Классика телефонного разговора.",
    },
    {
      kind: "choice",
      stage: 1,
      tag: "Simple или Continuous",
      q: "«Я пью кофе каждое утро» — какое время?",
      note: "Every morning — сигнал привычки → Present Simple.",
      options: [
        { t: "I drink coffee every morning.", ok: true },
        { t: "I am drinking coffee every morning." },
        { t: "I drinks coffee every morning." },
      ],
      why: "Every morning → привычка → I drink. Continuous здесь не нужен.",
    },
    {
      kind: "choice",
      stage: 1,
      tag: "Simple или Continuous",
      q: "«Смотри! Данияр танцует!» — какое время?",
      note: "Look! — сигнал процесса прямо сейчас → Continuous.",
      options: [
        { t: "Look! Daniyar is dancing!", ok: true },
        { t: "Look! Daniyar dances!" },
        { t: "Look! Daniyar dancing!" },
      ],
      why: "Look! → происходит на глазах → is dancing.",
    },
    {
      kind: "fill",
      stage: 2,
      tag: "Предлоги",
      qBefore: "My keys are ",
      qAfter: " my bag.",
      hintRu: "Мои ключи в сумке (внутри). (in / on / at?)",
      note: "in — внутри, on — на поверхности, at — у точки.",
      answer: "in",
      why: "The keys are in my bag — ключи ВНУТРИ сумки → in.",
    },
    {
      kind: "choice",
      stage: 2,
      tag: "Предлоги",
      q: "«Встретимся У двери в 5». Какая пара предлогов верна?",
      note: "at + точка места, at + время: at the door, at five.",
      options: [
        { t: "at the door at five", ok: true },
        { t: "in the door on five" },
        { t: "on the door in five" },
      ],
      why: "Meet me at the door at five — at для точки встречи и для времени.",
    },
    {
      kind: "choice",
      stage: 3,
      tag: "How much / many",
      q: "Спрашиваешь о количестве ДРУЗЕЙ (их можно посчитать). Какой вопрос?",
      note: "How many — сколько штук (считаемое), how much — сколько (неисчислимое) или о цене.",
      options: [
        { t: "How many friends do you have?", ok: true },
        { t: "How much friends do you have?" },
        { t: "How old friends do you have?" },
      ],
      why: "Друзей можно посчитать → how many. How much — про воду, деньги, время.",
    },
    {
      kind: "fill",
      stage: 3,
      tag: "How much / many",
      qBefore: "How ",
      qAfter: " is this jacket?",
      hintRu: "Сколько стоит эта куртка? (вопрос о цене)",
      note: "О цене всегда how much, даже если вещь одна.",
      answer: "much",
      why: "How much is this jacket? — «Сколько стоит эта куртка?» Цена = how much.",
    },
    {
      kind: "assemble",
      stage: 4,
      tag: "Финал",
      q: "Собери фразу из всех тем сразу: «Я сейчас жду автобус на остановке»:",
      note: "am + waiting (процесс) + at the bus stop (точка места).",
      words: ["I", "am", "waiting", "at", "the", "bus", "stop."],
      answer: "I am waiting at the bus stop.",
      why: "I am waiting at the bus stop — Continuous и предлог места в одной живой фразе. Тренажёр пройден!",
    },
  ],
  words: [],
};

export default drills;
