import type { Chapter } from "@/lib/types";

const drills: Chapter = {
  slug: "drills",
  title: "Тренажёр: Present Simple и вопросы",
  subtitle:
    "Отработка правил A1: -s в третьем лице, do/does, this/these, can, there is/are и предлоги. Коротко, быстро, по делу.",
  section: "exercise",
  stages: [
    { icon: "🔁", name: "Present Simple" },
    { icon: "❓", name: "Do / Does" },
    { icon: "👉", name: "Указатели" },
    { icon: "📍", name: "Предлоги" },
    { icon: "✅", name: "Готово" },
  ],
  steps: [
    {
      kind: "choice",
      stage: 0,
      tag: "-s в 3-м лице",
      q: "Выбери правильную фразу:",
      note: "С he/she/it глагол получает -s.",
      options: [
        { t: "She likes green tea.", ok: true },
        { t: "She like green tea." },
        { t: "She liking green tea." },
      ],
      why: "She likes — с she глагол берёт -s.",
    },
    {
      kind: "fill",
      stage: 0,
      tag: "-s в 3-м лице",
      qBefore: "He ",
      qAfter: " in a big company.",
      hintRu: "Он работает в большой компании. (work + правило третьего лица)",
      answer: "works",
      why: "He works — глагол с -s, потому что he.",
    },
    {
      kind: "choice",
      stage: 0,
      tag: "go → ?",
      q: "Как правильно: «Она ходит в школу»?",
      note: "После -o добавляется -es: go → goes.",
      options: [
        { t: "She goes to school.", ok: true },
        { t: "She gos to school." },
        { t: "She go to school." },
      ],
      why: "go → goes: после -o пишем -es.",
    },
    {
      kind: "fill",
      stage: 1,
      tag: "Вопрос с do",
      qBefore: "",
      qAfter: " you like London?",
      hintRu: "Тебе нравится Лондон? (помощник вопроса для you)",
      note: "Вопрос в Present Simple: Do (I/you/we/they) или Does (he/she/it) + подлежащее + глагол.",
      answer: "do",
      why: "Do you like London? — для you помощник do.",
    },
    {
      kind: "choice",
      stage: 1,
      tag: "Вопрос с does",
      q: "Как спросить «Он говорит по-английски?»",
      note: "После does глагол теряет -s — она уже внутри does!",
      options: [
        { t: "Does he speak English?", ok: true },
        { t: "Does he speaks English?" },
        { t: "Do he speak English?" },
      ],
      why: "Does he speak English? — does для he, глагол в базовой форме.",
    },
    {
      kind: "fill",
      stage: 1,
      tag: "Отрицание",
      qBefore: "She ",
      qAfter: " eat meat.",
      hintRu: "Она не ест мясо. (отрицание для she, одно слово с апострофом: doesn't)",
      answer: "doesn't",
      why: "She doesn't eat meat — отрицание через doesn't для he/she/it.",
    },
    {
      kind: "choice",
      stage: 2,
      tag: "this / these",
      q: "Туфли (их две!) у тебя в руках. Как спросить цену?",
      note: "Один предмет рядом — this, много — these.",
      options: [
        { t: "How much are these shoes?", ok: true },
        { t: "How much is this shoes?" },
        { t: "How much are that shoes?" },
      ],
      why: "these shoes + are: много предметов рядом.",
    },
    {
      kind: "assemble",
      stage: 2,
      tag: "can",
      q: "Скажи: «Я умею немного говорить по-английски»:",
      note: "can + глагол без to. A little — немного.",
      words: ["I", "can", "speak", "a", "little", "English."],
      answer: "I can speak a little English.",
      why: "I can speak… — после can глагол в базовой форме.",
    },
    {
      kind: "fill",
      stage: 3,
      tag: "there is / are",
      qBefore: "There ",
      qAfter: " two banks on this street.",
      hintRu: "На этой улице два банка. (банков — два!)",
      answer: "are",
      why: "There are two banks — несколько предметов → are.",
    },
    {
      kind: "choice",
      stage: 3,
      tag: "Предлоги",
      q: "Ключи лежат НА столе. Какой предлог?",
      note: "in — внутри, on — на поверхности, at — у точки.",
      options: [
        { t: "The keys are on the table.", ok: true },
        { t: "The keys are in the table." },
        { t: "The keys are at the table." },
      ],
      why: "on the table — на поверхности стола.",
    },
    {
      kind: "assemble",
      stage: 4,
      tag: "Финал",
      q: "Собери фразу с прилагательным на правильном месте: «Это красивый старый город»:",
      note: "Прилагательные — перед существительным: beautiful old city.",
      words: ["It", "is", "a", "beautiful", "old", "city."],
      answer: "It is a beautiful old city.",
      why: "Прилагательные встают перед словом: a beautiful old city. Тренажёр пройден!",
    },
  ],
  words: [],
};

export default drills;
