import type { Chapter } from "@/lib/types";

const drills: Chapter = {
  slug: "drills-u1",
  title: "Тренажёр: просьбы и цены",
  subtitle: "Отработка юнита «Просьбы и цены»: can для просьб и умения, how much / how many.",
  section: "exercise",
  stages: [
    { icon: "🙋", name: "Can" },
    { icon: "💰", name: "How much / many" },
    { icon: "✅", name: "Готово" },
  ],
  steps: [
    {
      kind: "choice",
      stage: 0,
      tag: "Can — просьба",
      q: "Как вежливо попросить повторить?",
      note: "Can you + действие + please? — вежливая просьба.",
      options: [
        { t: "Can you repeat, please?", ok: true },
        { t: "You can repeat, please?" },
        { t: "Repeat can you, please?" },
      ],
      why: "Can you repeat, please? — can встаёт перед you.",
    },
    {
      kind: "fill",
      stage: 0,
      tag: "Can — умение",
      qBefore: "I ",
      qAfter: " speak a little English.",
      hintRu: "Я немного говорю по-английски. (умение — модальный глагол)",
      answer: "can",
      why: "I can speak — can не меняется и не берёт -s.",
    },
    {
      kind: "choice",
      stage: 0,
      tag: "Can — разрешение",
      q: "Спрашиваешь, можно ли сесть здесь:",
      note: "Can I + действие? — просьба о разрешении.",
      options: [
        { t: "Can I sit here?", ok: true },
        { t: "Can I sits here?" },
        { t: "I can sit here?" },
      ],
      why: "Can I sit here? — после can глагол без -s, can впереди в вопросе.",
    },
    {
      kind: "choice",
      stage: 0,
      tag: "Can — отрицание",
      q: "«Она не умеет плавать». Как сказать?",
      note: "Can не меняется по лицам, но берёт't в отрицании: can't.",
      options: [
        { t: "She can't swim.", ok: true },
        { t: "She cans't swim." },
        { t: "She not can swim." },
      ],
      why: "She can't swim — can't одинаков для всех лиц.",
    },
    {
      kind: "fill",
      stage: 1,
      tag: "How much",
      qBefore: "How ",
      qAfter: " is this ticket?",
      hintRu: "Сколько стоит этот билет? (вопрос о цене)",
      answer: "much",
      why: "How much is this ticket? — о цене всегда how much.",
    },
    {
      kind: "choice",
      stage: 1,
      tag: "How many",
      q: "Спрашиваешь, сколько братьев у собеседника:",
      note: "Братьев можно посчитать → how many.",
      options: [
        { t: "How many brothers do you have?", ok: true },
        { t: "How much brothers do you have?" },
        { t: "How old brothers do you have?" },
      ],
      why: "How many brothers…? — исчисляемое (штуки) → how many.",
    },
    {
      kind: "fill",
      stage: 1,
      tag: "How much are",
      qBefore: "How much ",
      qAfter: " these shoes?",
      hintRu: "Сколько стоят эти туфли? (туфель — две, глагол во множественном числе)",
      answer: "are",
      why: "How much are these shoes? — shoes во множественном числе → are, а не is.",
    },
    {
      kind: "assemble",
      stage: 2,
      tag: "Финал",
      q: "Собери фразу: «Можно мне чашку кофе, пожалуйста? Сколько это стоит?»",
      note: "Can I have + предмет + please? затем How much is it?",
      words: ["Can", "I", "have", "a", "coffee,", "please?"],
      answer: "Can I have a coffee, please?",
      why: "Can I have a coffee, please? — вежливая просьба о вещи. Тренажёр пройден!",
    },
  ],
  words: [],
};

export default drills;
