import type { Unit } from "@/lib/types";

const units: Unit[] = [
  {
    slug: "unit-1",
    title: "Просьбы и цены",
    subtitle: "Первый день в Лондоне: как вежливо просить, заказывать и спрашивать стоимость.",
    goals: ["вежливо просить через can", "спрашивать цену", "объясняться в аэропорту и кафе"],
    ruleIds: ["can", "how-much-many"],
    exerciseSlugs: ["drills-u1"],
    questSlug: "arrival-in-london",
    textSlug: "text-crow-and-pitcher",
  },
  {
    slug: "unit-2",
    title: "Дорога и предлоги",
    subtitle: "Как спросить путь, понять ответ и не потеряться в городе.",
    goals: ["спрашивать дорогу", "использовать in, on, at", "различать this и these"],
    ruleIds: ["prepositions", "this-that"],
    exerciseSlugs: ["drills-u2"],
    questSlug: "first-day-in-the-city",
    textSlug: "text-town-mouse",
  },
  {
    slug: "unit-3",
    title: "Привычки и «прямо сейчас»",
    subtitle: "Два главных времени настоящего: что я делаю вообще и что делаю в этот момент.",
    goals: [
      "рассказывать о привычках (Present Simple)",
      "не забывать -s в третьем лице",
      "описывать, что происходит сейчас",
      "задавать вопросы через do и does",
    ],
    ruleIds: [
      "present-simple",
      "third-person-s",
      "do-does",
      "present-continuous",
      "simple-vs-continuous",
    ],
    exerciseSlugs: ["drills", "drills-2"],
    questSlug: "walk-with-daniyar",
    textSlug: "text-fox-and-grapes",
  },
  {
    slug: "unit-4",
    title: "Покупки и описания",
    subtitle: "Рынок Кэмден: как торговаться и описывать вещи прилагательными.",
    goals: ["торговаться и говорить «слишком дорого»", "ставить прилагательное на своё место"],
    ruleIds: ["adjectives"],
    exerciseSlugs: ["drills-u4"],
    questSlug: "camden-market",
    textSlug: "text-dog-and-bone",
  },
  {
    slug: "unit-5",
    title: "Что где есть: there is / there are",
    subtitle: "Как сообщить о проблеме и рассказать, что находится в комнате или городе.",
    goals: ["говорить, что где-то что-то есть", "сообщать о проблеме", "просить помощи"],
    ruleIds: ["there-is-are"],
    exerciseSlugs: ["drills-u5"],
    questSlug: "hotel-problem",
  },
  {
    slug: "unit-6",
    title: "Прощание и первое прошедшее",
    subtitle: "Финал сезона: слово was и всё, что нужно в аэропорту.",
    goals: ["говорить о прошлом через was", "благодарить и прощаться"],
    ruleIds: [],
    questSlug: "going-home",
    textSlug: "postcard-from-daniyar",
  },
];

export default units;
