import type { Chapter } from "@/lib/types";

const chapter6: Chapter = {
  slug: "edinburgh",
  title: "Эдинбург",
  subtitle:
    "Прощальное путешествие сезона: поезд на север, древний замок и обещание вернуться. Финал — повторение всего, что ты выучил!",
  goals: [
    "понимать объявления на вокзале",
    "сравнивать города и достопримечательности",
    "понимать рассказ экскурсовода о прошлом",
    "обещать и прощаться",
  ],
  stages: [
    { icon: "🚆", name: "Поезд" },
    { icon: "🏰", name: "Замок" },
    { icon: "🌄", name: "Холм Артура" },
    { icon: "🎶", name: "Вечер" },
    { icon: "🏠", name: "Финал сезона" },
  ],
  steps: [
    {
      kind: "story",
      stage: 0,
      en: "Before you fly home, one more adventure: Edinburgh, Scotland! You and Daniyar are at King's Cross station with backpacks and coffee.",
      ru: "Перед вылетом домой — ещё одно приключение: Эдинбург, Шотландия! Вы с Данияром стоите на вокзале Кингс-Кросс с рюкзаками и кофе.",
    },
    {
      kind: "listen",
      stage: 0,
      tag: "Аудирование",
      q: "Объявление на вокзале! Во сколько поезд на Эдинбург?",
      audio: "The train to Edinburgh leaves at nine.",
      note: "Leaves — отправляется. Схема как в аэропорту: лови число после at. Nine — 9, five — 5.",
      options: [{ t: "В 9", ok: true }, { t: "В 5" }, { t: "В 10" }],
      why: "The train to Edinburgh leaves at nine — «Поезд на Эдинбург отправляется в девять». Вокзалы и аэропорты ты понимаешь без переводчика.",
    },
    {
      kind: "story",
      stage: 1,
      en: "Four hours later — Edinburgh! Old stone streets, seagulls, and the castle on the rock. It is beautiful.",
      ru: "Четыре часа спустя — Эдинбург! Старинные каменные улицы, чайки и замок на скале. Красота.",
    },
    {
      kind: "fill",
      stage: 1,
      tag: "Впиши слово",
      qBefore: "Edinburgh is ",
      qAfter: " than London.",
      hintRu: "Эдинбург старше Лондона… по ощущениям! (old — старый, но нужна форма сравнения)",
      note: "Сравнение из главы про комнату: короткое слово + -er + than. Old → older.",
      rule: "comparative",
      answer: "older",
      why: "Edinburgh is older than London — «Эдинбург старше Лондона» (по духу — точно!). Формула сравнения работает с любыми словами.",
    },
    {
      kind: "choice",
      stage: 1,
      tag: "Пойми экскурсовода",
      q: "Гид в замке говорит: «This castle was built 900 years ago». О чём это?",
      note: "Was built — «был построен», years ago — лет назад. Слышишь was — речь о прошлом.",
      options: [
        { t: "Замку 900 лет", ok: true },
        { t: "Замок закрыт 900 дней" },
        { t: "В замке 900 комнат" },
      ],
      why: "This castle was built 900 years ago — «Замок построен 900 лет назад». Ago («назад») — верный спутник рассказов о прошлом.",
    },
    {
      kind: "story",
      stage: 2,
      en: "Daniyar has an idea: «Arthur's Seat! It's an old {volcano|вулкан} with the best view of the city. Let's climb it!»",
      ru: "У Данияра идея: «Трон Артура! Это древний вулкан с лучшим видом на город. Полезли наверх!»",
    },
    {
      kind: "fill",
      stage: 2,
      tag: "Впиши слово",
      qBefore: "We ",
      qAfter: " to the top of the hill!",
      hintRu: "Мы поднялись на вершину холма! (go — но в прошлом, ты выучил это слово в первой главе сезона)",
      note: "Неправильный глагол из главы «Год спустя»: go → went. Top — вершина, hill — холм.",
      answer: "went",
      why: "We went to the top of the hill! — «Мы поднялись на вершину!» Went закреплён — теперь он твой навсегда.",
    },
    {
      kind: "assemble",
      stage: 2,
      tag: "Собери фразу",
      q: "Вид с вершины — невероятный. Скажи это!",
      note: "View — вид. The best — самый лучший (good → better → the best, помнишь лесенку?).",
      words: ["This", "is", "the", "best", "view!"],
      answer: "This is the best view!",
      why: "This is the best view! — «Это лучший вид!» Весь город, море и горы — стоило подняться.",
      phrase: { en: "This is the best view!", ru: "Это лучший вид!" },
    },
    {
      kind: "story",
      stage: 3,
      en: "Evening. A small pub with live music. A local man with a guitar asks where you are from, and you talk — easily, in English, like it is nothing special. But it IS special.",
      ru: "Вечер. Маленький паб с живой музыкой. Местный музыкант с гитарой спрашивает, откуда вы, и ты болтаешь — легко, по-английски, будто это обычное дело. Но это не обычное дело. Это победа.",
    },
    {
      kind: "listen",
      stage: 3,
      tag: "Аудирование",
      q: "Музыкант поднимает стакан и говорит тост. Какой?",
      audio: "To new friends!",
      note: "To — за (в тостах), new — новые, friends — друзья. Короткий и главный шотландский тост!",
      options: [
        { t: "За новых друзей!", ok: true },
        { t: "За хорошую погоду!" },
        { t: "За музыку!" },
      ],
      why: "To new friends! — «За новых друзей!» Лучший тост для этого вечера.",
      phrase: { en: "To new friends!", ru: "За новых друзей!" },
    },
    {
      kind: "story",
      stage: 4,
      en: "The last morning. Soon — the airport, then Almaty, then your new remote job. Daniyar hugs you: «Well? Say it!»",
      ru: "Последнее утро. Скоро — аэропорт, потом Алматы, потом новая удалённая работа. Данияр обнимает тебя: «Ну? Скажи это!»",
    },
    {
      kind: "assemble",
      stage: 4,
      tag: "Собери фразу",
      q: "Пообещай вернуться — теперь ты знаешь, как обещать:",
      note: "Обещание в момент разговора = will (из главы про стажировку). Come back — вернуться, next year — в следующем году.",
      rule: "will",
      words: ["I", "will", "come", "back", "next", "year!"],
      answer: "I will come back next year!",
      why: "I will come back next year! — «Я вернусь в следующем году!» Will — обещание, и мы верим: сезон 3 будет.",
      phrase: { en: "I will come back!", ru: "Я вернусь!" },
    },
    {
      kind: "choice",
      stage: 4,
      tag: "Финал сезона",
      q: "Данияр кричит вслед: «Good luck with the new job!» Что он пожелал?",
      note: "Good luck — удачи, with — с (чем-то). Классическое пожелание перед новым делом.",
      options: [
        { t: "Удачи с новой работой", ok: true },
        { t: "Хорошей погоды в Алматы" },
        { t: "Не опоздать на самолёт" },
      ],
      why: "Good luck with the new job! — «Удачи с новой работой!» Сезон 2 завершён: у героя — работа, друзья и уровень A2. Дальше — B1!",
      phrase: { en: "Good luck!", ru: "Удачи!" },
    },
  ],
  words: [
    { en: "train / leaves", ru: "поезд / отправляется" },
    { en: "older than", ru: "старше, чем" },
    { en: "was built … years ago", ru: "был построен … лет назад" },
    { en: "the best view", ru: "лучший вид" },
    { en: "to new friends!", ru: "за новых друзей! (тост)" },
    { en: "good luck", ru: "удачи" },
  ],
};

export default chapter6;
