import type { Chapter } from "@/lib/types";

const chapter2: Chapter = {
  slug: "internship-first-day",
  title: "Первый день стажировки",
  subtitle:
    "Офис в Шордиче, менеджер Сара и новая команда. Учимся говорить о планах: going to — что задумано, will — что решил прямо сейчас.",
  goals: [
    "рассказывать о планах через going to",
    "давать обещания через will",
    "различать план и решение в моменте",
    "понимать рабочие договорённости на слух",
  ],
  stages: [
    { icon: "🏢", name: "Офис" },
    { icon: "👋", name: "Знакомство" },
    { icon: "📋", name: "Планы" },
    { icon: "💻", name: "Задача" },
    { icon: "🎉", name: "Конец дня" },
  ],
  steps: [
    {
      kind: "story",
      stage: 0,
      en: "Shoreditch, East London. Bright office, plants everywhere, a coffee machine that makes seven kinds of coffee. Your manager Sarah meets you at the door.",
      ru: "Шордич, восточный Лондон. Светлый офис, всюду растения и кофемашина с семью видами кофе. У дверей тебя встречает менеджер Сара.",
    },
    {
      kind: "story",
      stage: 1,
      who: "Сара",
      say: "Welcome to the team! What are you going to work on this summer?",
      ru: "Добро пожаловать в команду! Над чем ты собираешься работать этим летом?",
    },
    {
      kind: "choice",
      stage: 1,
      tag: "Пойми вопрос",
      q: "Сара спросила «What are you going to work on?» — о чём вопрос?",
      note: "Going to — не только «идти». Am/is/are + going to + глагол = «собираюсь сделать». Это главный способ говорить о планах!",
      options: [
        { t: "О твоих планах на работу", ok: true },
        { t: "О том, куда ты идёшь" },
        { t: "О твоей прошлой работе" },
      ],
      why: "What are you going to work on? — «Над чем собираешься работать?» Going to здесь — про план, а не про движение.",
    },
    {
      kind: "assemble",
      stage: 1,
      tag: "Собери фразу",
      q: "Ответь Саре — ты собираешься многому научиться:",
      note: "Схема плана: I am going to + действие. Learn — учиться, a lot — много.",
      rule: "going-to",
      words: ["I", "am", "going", "to", "learn", "a", "lot!"],
      answer: "I am going to learn a lot!",
      why: "I am going to learn a lot! — «Я собираюсь многому научиться!» Конструктор: I am going to + любой глагол = любой твой план.",
      phrase: { en: "I am going to learn a lot!", ru: "Я собираюсь многому научиться!" },
    },
    {
      kind: "story",
      stage: 2,
      en: "Sarah shows you the office: the kitchen, the meeting rooms, your desk with a new laptop. A colleague, Tom, waves at you.",
      ru: "Сара показывает офис: кухню, переговорки, твой стол с новым ноутбуком. Коллега Том машет тебе рукой.",
    },
    {
      kind: "listen",
      stage: 2,
      tag: "Аудирование",
      q: "Послушай Тома. Что он предлагает?",
      audio: "We are going to have lunch at one. Join us!",
      note: "Have lunch — пообедать, join us — присоединяйся. Лови время после at!",
      options: [
        { t: "Пообедать вместе в час", ok: true },
        { t: "Встретиться после работы" },
        { t: "Выпить кофе в три" },
      ],
      why: "We are going to have lunch at one. Join us! — «Мы собираемся обедать в час. Присоединяйся!» Первый день — и уже зовут 🙂",
    },
    {
      kind: "story",
      stage: 3,
      ru: "После обеда — первая задача! Она сложная, и Том это видит. «Есть второе слово для будущего, — объясняет он. — Will. Это когда решаешь помочь прямо сейчас».",
    },
    {
      kind: "story",
      stage: 3,
      who: "Том",
      say: "Don't worry! I will help you with this task.",
      ru: "Не переживай! Я помогу тебе с этой задачей.",
    },
    {
      kind: "fill",
      stage: 3,
      tag: "Впиши слово",
      qBefore: "Thank you! I ",
      qAfter: " do my best!",
      hintRu: "Спасибо! Я буду очень стараться! (обещание — прямо сейчас)",
      note: "Will — «сделаю» (решение или обещание в момент разговора). Сравни: going to — план заранее, will — решил сейчас. Do my best — стараться изо всех сил.",
      rule: "will",
      answer: "will",
      why: "I will do my best! — «Я буду очень стараться!» Отличная фраза для первого рабочего дня — и для всей жизни.",
      phrase: { en: "I will do my best!", ru: "Я буду очень стараться!" },
    },
    {
      kind: "choice",
      stage: 3,
      tag: "План или обещание?",
      q: "«I am going to visit Edinburgh in August» — это план или решение прямо сейчас?",
      note: "Проверь себя: going to — план, который был ДО разговора. Will — решение В МОМЕНТ разговора.",
      rule: "going-to-vs-will",
      options: [
        { t: "План, задуманный заранее", ok: true },
        { t: "Решение прямо сейчас" },
        { t: "Рассказ о прошлом" },
      ],
      why: "Going to = план заранее («собираюсь в августе в Эдинбург»). Если бы решил сейчас, было бы: OK, I will visit Edinburgh!",
    },
    {
      kind: "listen",
      stage: 4,
      tag: "Аудирование",
      q: "Конец дня. Сара рассказывает о планах на завтра. Во сколько встреча?",
      audio: "The team meeting is at ten tomorrow.",
      note: "Team meeting — встреча команды. Число после at — время. Ten — 10, two — 2.",
      options: [{ t: "В 10", ok: true }, { t: "В 2" }, { t: "В 6" }],
      why: "The team meeting is at ten tomorrow — «Встреча команды завтра в десять». Времена и числа ты ловишь уже на автомате!",
    },
    {
      kind: "assemble",
      stage: 4,
      tag: "Собери фразу",
      q: "Попрощайся с командой до завтра:",
      note: "Всё знакомое: see you — увидимся, at the meeting — на встрече.",
      words: ["See", "you", "at", "the", "meeting!"],
      answer: "See you at the meeting!",
      why: "See you at the meeting! — «Увидимся на встрече!» Первый день пройден. Ты — часть команды.",
      phrase: { en: "See you at the meeting!", ru: "Увидимся на встрече!" },
    },
  ],
  words: [
    { en: "going to", ru: "собираюсь (план)" },
    { en: "will", ru: "сделаю (решение, обещание)" },
    { en: "have lunch", ru: "обедать" },
    { en: "join us", ru: "присоединяйся" },
    { en: "do my best", ru: "стараться изо всех сил" },
    { en: "meeting", ru: "встреча" },
  ],
};

export default chapter2;
