import type { Chapter } from "@/lib/types";

const chapter3: Chapter = {
  slug: "room-to-rent",
  title: "Комната в аренду",
  subtitle:
    "Диван Данияра — это не навсегда: ищем свою комнату! Смотрим два варианта и учимся сравнивать: bigger, cheaper, better и the best.",
  goals: [
    "читать объявление об аренде жилья",
    "сравнивать два варианта: больше, дешевле, лучше",
    "называть самый лучший вариант",
    "договариваться о заселении",
  ],
  stages: [
    { icon: "🔍", name: "Поиск" },
    { icon: "🚪", name: "Комната №1" },
    { icon: "🏠", name: "Комната №2" },
    { icon: "⚖️", name: "Сравнение" },
    { icon: "✍️", name: "Решение" },
  ],
  steps: [
    {
      kind: "story",
      stage: 0,
      en: "Daniyar's sofa is nice, but you need your own place. You open a website and see: «ROOM TO RENT — Camden, £90 a week».",
      ru: "Диван Данияра — это мило, но нужно своё жильё. Ты открываешь сайт и видишь: «ROOM TO RENT — Camden, £90 a week».",
    },
    {
      kind: "choice",
      stage: 0,
      tag: "Пойми объявление",
      q: "Что значит «ROOM TO RENT»?",
      note: "Room — комната, rent — аренда, снимать. A week — в неделю (в Лондоне цены на жильё называют за неделю!).",
      options: [
        { t: "Сдаётся комната", ok: true },
        { t: "Комната продаётся" },
        { t: "Комната занята" },
      ],
      why: "Room to rent — «сдаётся комната». £90 a week — 90 фунтов в неделю: в Британии аренду считают неделями.",
    },
    {
      kind: "story",
      stage: 1,
      en: "The first room is in Camden. It is small, but the {landlord|хозяин жилья} is friendly. Through the window you can see the market!",
      ru: "Первая комната — в Кэмдене. Она маленькая, но хозяин дружелюбный. Из окна видно тот самый рынок!",
    },
    {
      kind: "listen",
      stage: 1,
      tag: "Аудирование",
      q: "Хозяин называет цену. Сколько стоит комната №1?",
      audio: "It's ninety pounds a week.",
      note: "Лови число: ninety — 90, nineteen — 19. Та же ловушка, что thirty/thirteen с рынка!",
      options: [{ t: "90 фунтов в неделю", ok: true }, { t: "19 фунтов в неделю" }, { t: "9 фунтов в неделю" }],
      why: "Ninety pounds a week — 90 фунтов в неделю. Ловушку -ty/-teen ты уже знаешь — она больше не работает!",
    },
    {
      kind: "story",
      stage: 2,
      en: "The second room is in Greenwich. It is far from the centre, but… wow. Big windows, a new bed, a quiet green street.",
      ru: "Вторая комната — в Гринвиче. Далеко от центра, но… вау. Большие окна, новая кровать, тихая зелёная улица.",
    },
    {
      kind: "fill",
      stage: 2,
      tag: "Впиши слово",
      qBefore: "This room is ",
      qAfter: " than the first one.",
      hintRu: "Эта комната больше, чем первая. (big — большой, но нужна форма сравнения!)",
      note: "Сравнение: короткое слово + -er + than = «…-ее, чем». Big → bigger (буква g удваивается), cheap → cheaper, small → smaller.",
      rule: "comparative",
      answer: "bigger",
      why: "This room is bigger than the first one — «Эта комната больше первой». Формула сравнения: X is …-er than Y.",
    },
    {
      kind: "choice",
      stage: 3,
      tag: "Сравни сам",
      q: "Комната №2 стоит £75, комната №1 — £90. Какая фраза верна?",
      note: "Cheap — дешёвый → cheaper — дешевле. Expensive — длинное слово, поэтому не -er, а more expensive — «более дорогая».",
      options: [
        { t: "The second room is cheaper.", ok: true },
        { t: "The second room is more expensive." },
        { t: "The rooms are the same price." },
      ],
      why: "The second room is cheaper — «Вторая комната дешевле» (75 < 90). Короткие слова + -er, длинные — more + слово.",
    },
    {
      kind: "assemble",
      stage: 3,
      tag: "Собери фразу",
      q: "Скажи Данияру своё мнение — вторая комната лучше:",
      note: "Good («хороший») — упрямое слово: сравнение не «gooder», а better — «лучше». Это надо просто запомнить.",
      words: ["The", "second", "room", "is", "better."],
      answer: "The second room is better.",
      why: "The second room is better — «Вторая комната лучше». Good → better → the best: хороший → лучше → самый лучший.",
      phrase: { en: "It's better.", ru: "Это лучше." },
    },
    {
      kind: "fill",
      stage: 4,
      tag: "Впиши слово",
      qBefore: "It's the ",
      qAfter: " room in Greenwich!",
      hintRu: "Это лучшая комната в Гринвиче! (good → better → the …?)",
      note: "«Самый …» = the + -est: the biggest — самый большой. А у good своя лесенка: good → better → the best — самый лучший.",
      rule: "superlative",
      answer: "best",
      why: "It's the best room in Greenwich! — «Лучшая комната в Гринвиче!» The best — вершина сравнения.",
      phrase: { en: "It's the best!", ru: "Это лучшее!" },
    },
    {
      kind: "listen",
      stage: 4,
      tag: "Аудирование",
      q: "Хозяйка комнаты №2 задаёт тебе вопрос. Какой?",
      audio: "When are you going to move in?",
      note: "Move in — въехать, заселиться. Слышишь going to? Значит, вопрос о планах!",
      options: [
        { t: "Когда ты собираешься въехать", ok: true },
        { t: "Сколько ты готов платить" },
        { t: "Откуда ты приехал" },
      ],
      why: "When are you going to move in? — «Когда собираешься въезжать?» Going to из прошлой главы уже работает на тебя!",
    },
    {
      kind: "assemble",
      stage: 4,
      tag: "Собери фразу",
      q: "Решение принято — комната твоя! Скажи знакомую фразу:",
      note: "Ты говорил это на рынке Кэмден про кроссовки. Теперь — про целую комнату!",
      words: ["Great!", "I'll", "take", "it!"],
      answer: "Great! I'll take it!",
      why: "I'll take it! — «Беру!» Работает и с футболкой за £10, и с комнатой в Гринвиче. Поздравляю с новым домом!",
      phrase: { en: "I'll take it!", ru: "Беру! (снова!)" },
    },
  ],
  words: [
    { en: "rent", ru: "аренда, снимать" },
    { en: "landlord", ru: "хозяин жилья" },
    { en: "bigger / smaller", ru: "больше / меньше" },
    { en: "cheaper / more expensive", ru: "дешевле / дороже" },
    { en: "good → better → the best", ru: "хороший → лучше → самый лучший" },
    { en: "move in", ru: "въехать, заселиться" },
  ],
};

export default chapter3;
