import type { Chapter } from "@/lib/types";

const chapter5: Chapter = {
  slug: "the-interview",
  title: "Собеседование",
  subtitle:
    "Стажировка заканчивается, но Сара предлагает настоящее собеседование: должность junior-разработчика с возможностью работать из Алматы! Учимся рассказывать о себе.",
  goals: [
    "коротко рассказывать о себе на собеседовании",
    "описывать свой опыт в прошедшем времени",
    "задавать уточняющие вопросы об условиях",
    "понимать вопросы работодателя на слух",
  ],
  stages: [
    { icon: "📧", name: "Письмо" },
    { icon: "👔", name: "Подготовка" },
    { icon: "🗣️", name: "Вопросы" },
    { icon: "💪", name: "О себе" },
    { icon: "🤝", name: "Решение" },
  ],
  steps: [
    {
      kind: "story",
      stage: 0,
      en: "An email from Sarah: «Your internship was great. We want to offer you an interview for a junior position — you can work from Almaty!»",
      ru: "Письмо от Сары: «Твоя стажировка прошла отлично. Мы хотим предложить тебе собеседование на junior-позицию — можно работать из Алматы!»",
    },
    {
      kind: "choice",
      stage: 0,
      tag: "Пойми письмо",
      q: "Что предлагает Сара?",
      note: "Offer — предлагать, interview — собеседование, position — должность. Work from — работать из (какого-то места).",
      options: [
        { t: "Собеседование на постоянную работу", ok: true },
        { t: "Продлить стажировку на месяц" },
        { t: "Попрощаться с командой" },
      ],
      why: "Сара предлагает interview for a junior position — собеседование на постоянную junior-должность. Это шанс!",
    },
    {
      kind: "story",
      stage: 1,
      en: "Daniyar helps you prepare. «They always ask the same questions, — he says. — Let's practise the main one!»",
      ru: "Данияр помогает подготовиться. «Они всегда задают одни и те же вопросы, — говорит он. — Давай отрепетируем главный!»",
    },
    {
      kind: "listen",
      stage: 1,
      tag: "Аудирование",
      q: "Данияр играет роль интервьюера. О чём он просит?",
      audio: "Tell me about yourself.",
      note: "Tell — расскажи, about — о, yourself — себе. Эту фразу говорят в начале ЛЮБОГО собеседования в мире.",
      options: [
        { t: "Рассказать о себе", ok: true },
        { t: "Рассказать о своём городе" },
        { t: "Задать свой вопрос" },
      ],
      why: "Tell me about yourself — «Расскажите о себе». Готовь ответ заранее — вопрос будет обязательно!",
      phrase: { en: "Tell me about yourself.", ru: "Расскажите о себе." },
    },
    {
      kind: "assemble",
      stage: 1,
      tag: "Собери фразу",
      q: "Начни рассказ о себе — коротко и сильно:",
      note: "Хороший рассказ о себе — простые факты: I work hard — я усердно работаю, I learn fast — я быстро учусь.",
      words: ["I", "work", "hard", "and", "I", "learn", "fast."],
      answer: "I work hard and I learn fast.",
      why: "I work hard and I learn fast — «Я усердно работаю и быстро учусь». Две короткие фразы звучат сильнее длинной запутанной.",
      phrase: { en: "I work hard and I learn fast.", ru: "Я усердно работаю и быстро учусь." },
    },
    {
      kind: "story",
      stage: 2,
      en: "The interview day. A video call: Sarah and the CTO, Mr Reed. He asks about your past — and you are ready, because you know Past Simple!",
      ru: "День собеседования. Видеозвонок: Сара и технический директор мистер Рид. Он спрашивает о твоём прошлом — а ты готов, потому что знаешь Past Simple!",
    },
    {
      kind: "fill",
      stage: 2,
      tag: "Впиши слово",
      qBefore: "Last year I ",
      qAfter: " two programming courses.",
      hintRu: "В прошлом году я закончил два курса программирования. (finish — но в прошлом!)",
      note: "Правило -ed из главы «Год спустя»: finish → finished. Вопрос о прошлом — ответ в прошлом.",
      answer: "finished",
      why: "I finished two programming courses — «Я закончил два курса программирования». Факты в Past Simple — лучший ответ на собеседовании.",
    },
    {
      kind: "listen",
      stage: 2,
      tag: "Аудирование",
      q: "Мистер Рид задаёт практичный вопрос. Какой?",
      audio: "When can you start?",
      note: "When — когда, start — начать. Если задают ЭТОТ вопрос — ты им понравился!",
      options: [
        { t: "Когда ты можешь начать", ok: true },
        { t: "Когда ты уезжаешь домой" },
        { t: "Когда тебе удобно созвониться" },
      ],
      why: "When can you start? — «Когда можете начать?» Вопрос-знак: решение почти принято.",
      phrase: { en: "When can you start?", ru: "Когда можете начать?" },
    },
    {
      kind: "assemble",
      stage: 3,
      tag: "Собери фразу",
      q: "Уточни важное — можно ли работать из дома:",
      note: "Всё знакомое: Can I + действие. From home — из дома.",
      words: ["Can", "I", "work", "from", "home?"],
      answer: "Can I work from home?",
      why: "Can I work from home? — «Могу я работать из дома?» Правильные вопросы на собеседовании — признак зрелости, задавай смело.",
      phrase: { en: "Can I work from home?", ru: "Могу я работать из дома?" },
    },
    {
      kind: "fill",
      stage: 3,
      tag: "Впиши слово",
      qBefore: "I ",
      qAfter: " ready to start in September!",
      hintRu: "Я готов начать в сентябре! (самая первая связка, про себя)",
      note: "Финальный аккорд собеседования — фраза из курса Starter: I am ready. Круг замкнулся!",
      answer: "am",
      why: "I am ready to start in September! — «Я готов начать в сентябре!» Ты сказал это в первый день учёбы — и говоришь на собеседовании в Лондоне.",
    },
    {
      kind: "listen",
      stage: 4,
      tag: "Аудирование",
      q: "Через час приходит голосовое от Сары. Что она говорит?!",
      audio: "Congratulations! You have the job!",
      note: "Congratulations — поздравляю! Лови главное слово: job — работа.",
      options: [
        { t: "Поздравляю, работа твоя!", ok: true },
        { t: "Нужно второе собеседование" },
        { t: "Позиция закрыта" },
      ],
      why: "Congratulations! You have the job! — «Поздравляю! Работа твоя!» 🎉",
      phrase: { en: "Congratulations!", ru: "Поздравляю!" },
    },
    {
      kind: "assemble",
      stage: 4,
      tag: "Собери фразу",
      q: "Ответь Саре — поблагодари за возможность:",
      note: "Thank you so much — «огромное спасибо» (so much усиливает). Opportunity — возможность… но можно проще: for everything!",
      words: ["Thank", "you", "so", "much!"],
      answer: "Thank you so much!",
      why: "Thank you so much! — «Огромное спасибо!» У героя теперь есть работа в лондонской компании. А у тебя — уровень A2 почти в кармане.",
      phrase: { en: "Thank you so much!", ru: "Огромное спасибо!" },
    },
  ],
  words: [
    { en: "interview", ru: "собеседование" },
    { en: "position / job", ru: "должность / работа" },
    { en: "tell me about yourself", ru: "расскажите о себе" },
    { en: "work hard / learn fast", ru: "усердно работать / быстро учиться" },
    { en: "finished", ru: "закончил" },
    { en: "congratulations", ru: "поздравляю" },
  ],
};

export default chapter5;
