import type { Chapter } from "@/lib/types";

const chapter4: Chapter = {
  slug: "at-the-doctor",
  title: "У врача",
  subtitle:
    "Лондонский дождь сделал своё дело — ты простудился. Учимся называть, что болит, записываться к врачу и понимать советы: should и could.",
  goals: [
    "говорить, что у меня болит",
    "записываться на приём и понимать время визита",
    "вежливо просить через could",
    "понимать советы врача (should / shouldn't)",
  ],
  stages: [
    { icon: "🤧", name: "Утро" },
    { icon: "📞", name: "Запись" },
    { icon: "🏥", name: "Приём" },
    { icon: "💊", name: "Советы" },
    { icon: "😌", name: "Выздоровление" },
  ],
  steps: [
    {
      kind: "story",
      stage: 0,
      en: "Monday morning. Your head hurts, your {throat|горло} hurts, and your nose… oh no. London rain — one, you — zero.",
      ru: "Утро понедельника. Болит голова, болит горло, а нос… о нет. Лондонский дождь — один, ты — ноль.",
    },
    {
      kind: "assemble",
      stage: 0,
      tag: "Собери фразу",
      q: "Напиши Саре, что у тебя болит голова:",
      note: "Болезни говорят через знакомое I have: I have a headache — «у меня болит голова» (head — голова + ache — боль).",
      words: ["I", "have", "a", "headache."],
      answer: "I have a headache.",
      why: "I have a headache — «У меня болит голова». Так же: I have a cold (простуда), I have a sore throat (болит горло).",
      phrase: { en: "I have a headache.", ru: "У меня болит голова." },
    },
    {
      kind: "story",
      stage: 1,
      who: "Сара",
      say: "Oh no! You should see a doctor. Call this number.",
      ru: "О нет! Тебе стоит показаться врачу. Позвони по этому номеру.",
    },
    {
      kind: "choice",
      stage: 1,
      tag: "Пойми совет",
      q: "«You should see a doctor» — что сказала Сара?",
      note: "Should — «стоит, следует» (мягкий совет). You should… — «тебе стоит…». See a doctor — показаться врачу.",
      options: [
        { t: "Тебе стоит сходить к врачу", ok: true },
        { t: "Ты должен работать из дома" },
        { t: "Ты выглядишь хорошо" },
      ],
      why: "You should see a doctor — «Тебе стоит сходить к врачу». Should — самое вежливое слово для совета.",
      phrase: { en: "You should see a doctor.", ru: "Тебе стоит сходить к врачу." },
    },
    {
      kind: "listen",
      stage: 1,
      tag: "Аудирование",
      q: "Ты звонишь в клинику. На какое время тебя записали?",
      audio: "The doctor can see you at four thirty.",
      note: "Four thirty — 4:30 (четыре тридцать). Время из двух чисел: первое — час, второе — минуты.",
      options: [{ t: "На 4:30", ok: true }, { t: "На 3:40" }, { t: "На 5:13" }],
      why: "The doctor can see you at four thirty — «Врач примет вас в 4:30». Час + минуты: five fifteen — 5:15, six forty — 6:40.",
    },
    {
      kind: "story",
      stage: 2,
      en: "The clinic is warm and quiet. The doctor listens, checks your throat and smiles: «Just a cold. Nothing serious!»",
      ru: "В клинике тепло и тихо. Врач слушает, смотрит горло и улыбается: «Обычная простуда. Ничего серьёзного!»",
    },
    {
      kind: "assemble",
      stage: 2,
      tag: "Собери фразу",
      q: "Попроси у врача лекарство — очень вежливо:",
      note: "Could — супервежливое can. Could you + действие + please? — так просят врачей, начальников и незнакомцев.",
      words: ["Could", "you", "give", "me", "some", "medicine,", "please?"],
      answer: "Could you give me some medicine, please?",
      why: "Could you give me some medicine, please? — «Не могли бы вы дать мне лекарство?» Could звучит мягче, чем can — идеально для официальных ситуаций.",
      phrase: { en: "Could you…, please?", ru: "Не могли бы вы…? (вежливее can)" },
    },
    {
      kind: "listen",
      stage: 3,
      tag: "Аудирование",
      q: "Врач объясняет, как принимать лекарство. Как?",
      audio: "Take this medicine twice a day.",
      note: "Take — принимать, twice — дважды, a day — в день. Once — один раз, twice — два, three times — три.",
      options: [
        { t: "Два раза в день", ok: true },
        { t: "Один раз в день" },
        { t: "Три раза в день" },
      ],
      why: "Take this medicine twice a day — «Принимайте дважды в день». Once, twice, three times — счёт повторений.",
    },
    {
      kind: "choice",
      stage: 3,
      tag: "Пойми совет",
      q: "Врач добавляет: «You shouldn't go to work tomorrow». Это значит…",
      note: "Shouldn't = should not — «не стоит». Совет наоборот: You shouldn't… — «тебе не стоит…».",
      options: [
        { t: "Завтра не стоит идти на работу", ok: true },
        { t: "Завтра нужно прийти пораньше" },
        { t: "Завтра снова приходи в клинику" },
      ],
      why: "You shouldn't go to work tomorrow — «Завтра не стоит идти на работу». Врач прописал день сериалов и чая с мёдом 🙂",
    },
    {
      kind: "fill",
      stage: 4,
      tag: "Впиши слово",
      qBefore: "You ",
      qAfter: " drink hot tea and sleep.",
      hintRu: "Тебе стоит пить горячий чай и спать. (то самое слово-совет)",
      note: "Совет = should + глагол. Без to: should drink, should sleep, should stay.",
      rule: "should",
      answer: "should",
      why: "You should drink hot tea and sleep — «Стоит пить горячий чай и спать». Лучший рецепт от простуды на любом языке.",
    },
    {
      kind: "story",
      stage: 4,
      en: "Two days later you are back in the office. Tom brings you coffee: «Welcome back! Get well soon — oh wait, you are already well!»",
      ru: "Через два дня ты снова в офисе. Том приносит тебе кофе: «С возвращением! Выздоравливай скорее — ой, ты же уже здоров!»",
    },
    {
      kind: "choice",
      stage: 4,
      tag: "Запомни фразу",
      q: "«Get well soon!» — что желают этой фразой?",
      note: "Get well — выздоравливай (дословно «становись здоровым»), soon — скоро. Это пишут заболевшим друзьям и коллегам.",
      options: [
        { t: "Скорейшего выздоровления", ok: true },
        { t: "Хорошей поездки" },
        { t: "Удачи на экзамене" },
      ],
      why: "Get well soon! — «Выздоравливай скорее!» Тёплая фраза, которая всегда кстати.",
      phrase: { en: "Get well soon!", ru: "Выздоравливай скорее!" },
    },
  ],
  words: [
    { en: "headache / sore throat / cold", ru: "головная боль / больное горло / простуда" },
    { en: "should / shouldn't", ru: "стоит / не стоит (совет)" },
    { en: "could you…?", ru: "не могли бы вы…?" },
    { en: "medicine", ru: "лекарство" },
    { en: "once / twice a day", ru: "раз / два раза в день" },
    { en: "get well soon", ru: "выздоравливай скорее" },
  ],
};

export default chapter4;
