import type { Chapter } from "@/lib/types";

const chapter1: Chapter = {
  slug: "one-year-later",
  title: "Год спустя",
  subtitle:
    "Алим снова летит в Лондон — теперь на стажировку! Данияр встречает в аэропорту. Учимся рассказывать о прошлом: was, were и первые глаголы-«неправильники».",
  goals: [
    "рассказывать, как прошло событие (was / were)",
    "говорить о прошлом через глаголы с -ed",
    "использовать неправильный глагол went",
    "задавать вопросы о прошлом через did",
  ],
  stages: [
    { icon: "✈️", name: "Прилёт" },
    { icon: "🤗", name: "Встреча" },
    { icon: "☕", name: "Кафе" },
    { icon: "📖", name: "Истории" },
    { icon: "🌃", name: "Вечер" },
  ],
  steps: [
    {
      kind: "story",
      stage: 0,
      en: "One year later. You are on the plane to London again — but now everything is different: you {won|выиграл} an internship in a London IT company!",
      ru: "Год спустя. Ты снова летишь в Лондон — но теперь всё иначе: ты выиграл стажировку в лондонской IT-компании!",
    },
    {
      kind: "story",
      stage: 1,
      who: "Данияр",
      say: "Welcome back, friend! How was your flight?",
      ru: "С возвращением, друг! Как прошёл полёт?",
    },
    {
      kind: "choice",
      stage: 1,
      tag: "Выбери ответ",
      q: "Полёт прошёл отлично. Что ответить?",
      note: "Помнишь was из финала сезона 1? Was — «был» (прошлое от is). How was…? — «как прошло…?». Отвечаем так же: It was… — «было…».",
      options: [
        { t: "It was great!", ok: true },
        { t: "It is tomorrow." },
        { t: "I am a flight." },
      ],
      why: "It was great! — «Всё было отлично!» Вопрос в прошедшем (was) — и ответ в прошедшем (was).",
      phrase: { en: "It was great!", ru: "Было отлично!" },
    },
    {
      kind: "fill",
      stage: 1,
      tag: "Впиши слово",
      qBefore: "We ",
      qAfter: " at this airport one year ago!",
      hintRu: "Мы были в этом аэропорту год назад! («мы» — это уже не один человек)",
      note: "У «был» две формы: was — для I/he/she/it, were — для you/we/they. Здесь we (мы), значит…",
      rule: "was-were",
      answer: "were",
      why: "We were at this airport one year ago — «Мы были здесь год назад». Was для одного, were для нескольких (и всегда для you).",
    },
    {
      kind: "story",
      stage: 2,
      en: "You go to your favourite café — the one from the first trip. The same table, the same tea. Daniyar wants to know everything about your year.",
      ru: "Вы идёте в ваше любимое кафе — то самое, из первой поездки. Тот же столик, тот же чай. Данияр хочет знать всё о том, как прошёл твой год.",
    },
    {
      kind: "assemble",
      stage: 2,
      tag: "Собери фразу",
      q: "Скажи, что скучал по этому городу:",
      note: "Miss — скучать. Чтобы сказать о прошлом, к обычному глаголу добавляют -ed: miss → missed («скучал»). Это Past Simple!",
      words: ["I", "missed", "this", "city!"],
      answer: "I missed this city!",
      why: "I missed this city! — «Я скучал по этому городу!» Правило простое: глагол + -ed = прошлое. Work → worked, play → played.",
      phrase: { en: "I missed this city!", ru: "Я скучал по этому городу!" },
    },
    {
      kind: "fill",
      stage: 2,
      tag: "Впиши слово",
      qBefore: "Last year I ",
      qAfter: " English every day.",
      hintRu: "В прошлом году я учил английский каждый день. (учить — study, но нужна форма прошлого!)",
      note: "Study → studied («учил»). Если глагол кончается на -y, она меняется на -ied: study → studied, try → tried.",
      rule: "past-regular",
      answer: "studied",
      why: "I studied English every day — «Я учил английский каждый день». И это видно — ты уже на A2!",
    },
    {
      kind: "story",
      stage: 3,
      ru: "«А теперь секрет, — Данияр делает загадочное лицо. — Не все глаголы любят -ed. Самые важные — упрямые: go (идти) в прошлом превращается в went. Их называют неправильными».",
    },
    {
      kind: "fill",
      stage: 3,
      tag: "Впиши слово",
      qBefore: "Last winter I ",
      qAfter: " to the mountains.",
      hintRu: "Прошлой зимой я ездил в горы. (go — но в прошлом!)",
      note: "Go — неправильный глагол: в прошлом не «goed», а went. Его нужно просто запомнить — он встречается постоянно.",
      rule: "past-irregular",
      answer: "went",
      why: "I went to the mountains — «Я ездил в горы». Went — первый неправильный глагол в твоей коллекции!",
    },
    {
      kind: "listen",
      stage: 3,
      tag: "Аудирование",
      q: "Данияр рассказывает свою новость. Что он сделал?",
      audio: "I passed all my exams!",
      note: "Pass — сдать (экзамен), passed — сдал. Exams — экзамены. Лови глагол с -ed!",
      options: [
        { t: "Сдал все экзамены", ok: true },
        { t: "Провалил экзамен" },
        { t: "Перенёс экзамены" },
      ],
      why: "I passed all my exams! — «Я сдал все экзамены!» Отличный повод сказать: Congratulations! — «Поздравляю!»",
    },
    {
      kind: "assemble",
      stage: 4,
      tag: "Собери фразу",
      q: "Теперь твоя очередь спрашивать! Узнай, что Данияр делал в прошлом году:",
      note: "Вопрос о прошлом строится со словом did: What did you do…? — «Что ты делал…?» Did — прошлое от do.",
      rule: "past-did",
      words: ["What", "did", "you", "do", "last", "year?"],
      answer: "What did you do last year?",
      why: "What did you do last year? — «Что ты делал в прошлом году?» Did — ключ ко всем вопросам о прошлом: Did you see it? Did you like it?",
      phrase: { en: "What did you do last year?", ru: "Что ты делал в прошлом году?" },
    },
    {
      kind: "story",
      stage: 4,
      en: "You talk for three hours. Tomorrow is a big day: your first day at the company. Daniyar smiles: «Sleep well. London is waiting for you — again!»",
      ru: "Вы болтаете три часа. Завтра большой день: твой первый день в компании. Данияр улыбается: «Выспись. Лондон снова ждёт тебя!»",
    },
  ],
  words: [
    { en: "was / were", ru: "был / были" },
    { en: "missed", ru: "скучал (miss + ed)" },
    { en: "studied", ru: "учил (study → studied)" },
    { en: "went", ru: "ездил, ходил (прошлое от go)" },
    { en: "passed", ru: "сдал (экзамен)" },
    { en: "did", ru: "делал; слово-ключ вопросов о прошлом" },
  ],
};

export default chapter1;
