import type { Chapter } from "@/lib/types";

const drills: Chapter = {
  slug: "drills-u2",
  title: "Тренажёр: планы и обещания",
  subtitle: "Отработка юнита «Планы и обещания»: going to для планов, will для решений в моменте.",
  section: "exercise",
  stages: [
    { icon: "📅", name: "Going to" },
    { icon: "⚡", name: "Will" },
    { icon: "⚖️", name: "Разница" },
    { icon: "✅", name: "Готово" },
  ],
  steps: [
    {
      kind: "fill",
      stage: 0,
      tag: "Going to",
      qBefore: "I am ",
      qAfter: " visit London next year.",
      hintRu: "Я собираюсь посетить Лондон в следующем году. (заранее задуманный план)",
      answer: "going to",
      why: "I am going to visit — план, о котором решили заранее.",
    },
    {
      kind: "choice",
      stage: 0,
      tag: "Going to",
      q: "«Мы собираемся снять квартиру» — заранее решённый план:",
      note: "am/is/are + going to + глагол.",
      options: [
        { t: "We are going to rent a flat.", ok: true },
        { t: "We will going to rent a flat." },
        { t: "We going to rent a flat." },
      ],
      why: "We are going to rent a flat — нужна связка are перед going to.",
    },
    {
      kind: "fill",
      stage: 1,
      tag: "Will",
      qBefore: "It ",
      qAfter: " rain tomorrow.",
      hintRu: "Завтра пойдёт дождь. (прогноз погоды)",
      answer: "will",
      why: "It will rain — прогноз строится через will.",
    },
    {
      kind: "choice",
      stage: 1,
      tag: "Will — обещание",
      q: "«Я обещаю, что позвоню тебе вечером». Как сказать?",
      note: "Обещания — через will.",
      options: [
        { t: "I will call you tonight.", ok: true },
        { t: "I am going to call you tonight, I promise, wait." },
        { t: "I call you tonight." },
      ],
      why: "I will call you tonight — простое и естественное обещание через will.",
    },
    {
      kind: "choice",
      stage: 1,
      tag: "Will — без to",
      q: "«Я помогу тебе с сумками». Выбери верный вариант:",
      note: "После will глагол без to.",
      options: [
        { t: "I will help you with the bags.", ok: true },
        { t: "I will to help you with the bags." },
        { t: "I will helping you with the bags." },
      ],
      why: "I will help — после will глагол в базовой форме, без to и без -ing.",
    },
    {
      kind: "choice",
      stage: 2,
      tag: "Going to или will?",
      q: "Друг говорит: «У нас закончилось молоко». Ты отвечаешь прямо сейчас, только что решив:",
      note: "Решение в момент речи → will, а не going to.",
      options: [
        { t: "Ok, I'll buy some.", ok: true },
        { t: "Ok, I am going to buy some, I decided this morning." },
        { t: "Ok, I buy some." },
      ],
      why: "I'll buy some — решение приняли прямо сейчас, в момент разговора → will.",
    },
    {
      kind: "choice",
      stage: 2,
      tag: "Going to или will?",
      q: "«Я собираюсь купить машину в следующем году» — план, о котором ты думал давно:",
      note: "Заранее обдуманный план → going to.",
      options: [
        { t: "I'm going to buy a car next year.", ok: true },
        { t: "I'll buy a car next year." },
        { t: "I buy a car next year." },
      ],
      why: "I'm going to buy a car — план, решённый заранее, а не в эту секунду.",
    },
    {
      kind: "assemble",
      stage: 3,
      tag: "Финал",
      q: "Собери фразу о заранее задуманном плане: «Мы собираемся изучать Python в следующем году»:",
      note: "We are going to + study + Python + next year.",
      words: ["We", "are", "going", "to", "study", "Python", "next", "year."],
      answer: "We are going to study Python next year.",
      why: "We are going to study Python next year — план, а не решение в моменте. Тренажёр пройден!",
    },
  ],
  words: [],
};

export default drills;
