import type { Chapter } from "@/lib/types";

const drills: Chapter = {
  slug: "drills",
  title: "Тренажёр: прошедшее и будущее",
  subtitle:
    "Отработка правил A2: was/were, -ed и неправильные глаголы, did, going to против will, сравнения и советы should.",
  section: "exercise",
  stages: [
    { icon: "⏪", name: "Past Simple" },
    { icon: "❓", name: "Did" },
    { icon: "⏩", name: "Будущее" },
    { icon: "⚖️", name: "Сравнение" },
    { icon: "✅", name: "Готово" },
  ],
  steps: [
    {
      kind: "fill",
      stage: 0,
      tag: "was / were",
      qBefore: "The film ",
      qAfter: " really good.",
      hintRu: "Фильм был очень хорошим. (film — это it)",
      note: "I/he/she/it → was, you/we/they → were.",
      answer: "was",
      why: "The film was good — it → was.",
    },
    {
      kind: "fill",
      stage: 0,
      tag: "was / were",
      qBefore: "We ",
      qAfter: " at home yesterday.",
      hintRu: "Вчера мы были дома. (we → ?)",
      answer: "were",
      why: "We were at home — we → were.",
    },
    {
      kind: "choice",
      stage: 0,
      tag: "Неправильный глагол",
      q: "«Она купила билет». Как правильно?",
      note: "buy — неправильный глагол: buy → bought.",
      options: [
        { t: "She bought a ticket.", ok: true },
        { t: "She buyed a ticket." },
        { t: "She buys a ticket yesterday." },
      ],
      why: "buy → bought. «Buyed» не существует.",
    },
    {
      kind: "fill",
      stage: 0,
      tag: "Неправильный глагол",
      qBefore: "Last summer I ",
      qAfter: " to the sea.",
      hintRu: "Прошлым летом я ездил на море. (go в прошлом)",
      answer: "went",
      why: "go → went — главный неправильный глагол.",
    },
    {
      kind: "choice",
      stage: 1,
      tag: "Вопрос с did",
      q: "Как спросить «Ты видел этот фильм?»",
      note: "После did глагол возвращается в базовую форму!",
      options: [
        { t: "Did you see this film?", ok: true },
        { t: "Did you saw this film?" },
        { t: "Do you saw this film?" },
      ],
      why: "Did you see…? — прошлое уже в did, глагол базовый.",
    },
    {
      kind: "fill",
      stage: 1,
      tag: "Отрицание",
      qBefore: "I ",
      qAfter: " like the hotel.",
      hintRu: "Мне не понравился отель. (отрицание прошлого, одно слово с апострофом: didn't)",
      answer: "didn't",
      why: "I didn't like the hotel — didn't + базовый глагол.",
    },
    {
      kind: "choice",
      stage: 2,
      tag: "going to / will",
      q: "«— У нас нет хлеба. — Ок, я куплю!» Какое будущее в ответе?",
      note: "Решение в момент разговора → will. План заранее → going to.",
      options: [
        { t: "OK, I will buy some!", ok: true },
        { t: "OK, I am going to buy some!" },
        { t: "OK, I bought some!" },
      ],
      why: "Решение принято прямо сейчас → will.",
    },
    {
      kind: "assemble",
      stage: 2,
      tag: "going to",
      q: "Скажи о плане: «Мы собираемся посетить Эдинбург»:",
      note: "План заранее: am/is/are + going to + глагол.",
      words: ["We", "are", "going", "to", "visit", "Edinburgh."],
      answer: "We are going to visit Edinburgh.",
      why: "We are going to visit… — план, задуманный заранее.",
    },
    {
      kind: "fill",
      stage: 3,
      tag: "Сравнение",
      qBefore: "The metro is ",
      qAfter: " than the bus.",
      hintRu: "Метро быстрее автобуса. (fast → ?)",
      note: "Короткое слово + er + than.",
      answer: "faster",
      why: "fast → faster than — быстрее, чем.",
    },
    {
      kind: "choice",
      stage: 3,
      tag: "Превосходная",
      q: "«Это ЛУЧШИЙ день!» Как правильно?",
      note: "good → better → the best (особая лесенка).",
      options: [
        { t: "It is the best day!", ok: true },
        { t: "It is the goodest day!" },
        { t: "It is the most good day!" },
      ],
      why: "good → the best. «Goodest» не существует.",
    },
    {
      kind: "assemble",
      stage: 4,
      tag: "Финал",
      q: "Дай совет: «Тебе стоит выучить эти правила»:",
      note: "should + глагол без to. Learn — учить.",
      words: ["You", "should", "learn", "these", "rules."],
      answer: "You should learn these rules.",
      why: "You should learn these rules — и ты уже это делаешь. Тренажёр пройден!",
    },
  ],
  words: [],
};

export default drills;
