import type { Chapter } from "@/lib/types";

const drills: Chapter = {
  slug: "drills-u3",
  title: "Тренажёр: сравнения",
  subtitle: "Отработка юнита «Сравнения»: сравнительная и превосходная степени прилагательных.",
  section: "exercise",
  stages: [
    { icon: "⚖️", name: "Сравнительная" },
    { icon: "🏆", name: "Превосходная" },
    { icon: "✅", name: "Готово" },
  ],
  steps: [
    {
      kind: "fill",
      stage: 0,
      tag: "Сравнительная",
      qBefore: "This room is ",
      qAfter: " than the first one.",
      hintRu: "Эта комната больше первой. (big → сравнительная степень)",
      answer: "bigger",
      why: "bigger than — короткое слово + er + than.",
    },
    {
      kind: "choice",
      stage: 0,
      tag: "Сравнительная",
      q: "«Чай здесь дешевле кофе». Как сказать?",
      note: "cheap — короткое слово: cheaper than.",
      options: [
        { t: "Tea is cheaper than coffee here.", ok: true },
        { t: "Tea is more cheap than coffee here." },
        { t: "Tea is cheapest than coffee here." },
      ],
      why: "cheaper than — короткие слова берут -er, а не more.",
    },
    {
      kind: "fill",
      stage: 0,
      tag: "Сравнительная (длинное слово)",
      qBefore: "This flat is ",
      qAfter: " expensive than that one.",
      hintRu: "Эта квартира дороже той. (expensive — длинное слово)",
      answer: "more",
      why: "more expensive than — длинные прилагательные берут more, а не -er.",
    },
    {
      kind: "choice",
      stage: 0,
      tag: "Исключения",
      q: "«Эта комната лучше той» (good → ?). Выбери верный вариант:",
      note: "good — исключение: better, а не gooder.",
      options: [
        { t: "This room is better than that one.", ok: true },
        { t: "This room is gooder than that one." },
        { t: "This room is more good than that one." },
      ],
      why: "good → better — особая форма, не по общему правилу.",
    },
    {
      kind: "fill",
      stage: 0,
      tag: "Правописание",
      qBefore: "It is ",
      qAfter: " than I expected.",
      hintRu: "Это проще, чем я ожидал. (easy → сравнительная, y меняется на i)",
      answer: "easier",
      why: "easy → easier: согласная + y → ier.",
    },
    {
      kind: "fill",
      stage: 1,
      tag: "Превосходная",
      qBefore: "It is ",
      qAfter: " café in town.",
      hintRu: "Это лучшее кафе в городе. (good → превосходная степень)",
      answer: "the best",
      why: "the best — особая превосходная форма от good.",
    },
    {
      kind: "choice",
      stage: 1,
      tag: "Превосходная",
      q: "«Это самый красивый вид, который я видел». Выбери верный вариант:",
      note: "beautiful — длинное слово: the most beautiful.",
      options: [
        { t: "This is the most beautiful view I've seen.", ok: true },
        { t: "This is the beautifulest view I've seen." },
        { t: "This is more beautiful view I've seen." },
      ],
      why: "the most beautiful — длинные прилагательные берут the most, а не -est.",
    },
    {
      kind: "fill",
      stage: 1,
      tag: "Превосходная (короткое слово)",
      qBefore: "It is the ",
      qAfter: " room in the flat.",
      hintRu: "Это самая большая комната в квартире. (big → превосходная, удвоение согласной)",
      answer: "biggest",
      why: "the biggest — короткое слово удваивает согласную перед -est.",
    },
    {
      kind: "assemble",
      stage: 2,
      tag: "Финал",
      q: "Собери фразу для объявления об аренде: «Это самая тихая и дешёвая комната в этом районе»:",
      note: "This is the quietest and cheapest room + in this area.",
      words: ["This", "is", "the", "quietest", "and", "cheapest", "room", "in", "this", "area."],
      answer: "This is the quietest and cheapest room in this area.",
      why: "the quietest and cheapest — обе превосходные степени рядом. Тренажёр пройден!",
    },
  ],
  words: [],
};

export default drills;
