import type { Chapter } from "@/lib/types";

const drills: Chapter = {
  slug: "drills-2",
  title: "Тренажёр 2: неправильные глаголы и must",
  subtitle:
    "Вторая тренировка уровня A2: самые нужные неправильные глаголы, разница must / have to / don't have to и превосходная степень.",
  section: "exercise",
  stages: [
    { icon: "🔁", name: "Неправильные" },
    { icon: "❗", name: "Must" },
    { icon: "🆓", name: "Не обязан" },
    { icon: "🏆", name: "Самый-самый" },
    { icon: "✅", name: "Готово" },
  ],
  steps: [
    {
      kind: "fill",
      stage: 0,
      tag: "Неправильный глагол",
      qBefore: "Yesterday I ",
      qAfter: " a very interesting film.",
      hintRu: "Вчера я посмотрел очень интересный фильм. (see — но в прошлом!)",
      note: "see → saw. Неправильные глаголы меняются целиком, без -ed.",
      answer: "saw",
      why: "I saw a film — see → saw. «Seed» и «seeed» не существуют.",
    },
    {
      kind: "fill",
      stage: 0,
      tag: "Неправильный глагол",
      qBefore: "She ",
      qAfter: " me a cup of tea.",
      hintRu: "Она дала мне чашку чая. (give — но в прошлом!)",
      note: "give → gave. Из басни про отца и сыновей: he gave them a bundle.",
      answer: "gave",
      why: "She gave me a cup of tea — give → gave.",
    },
    {
      kind: "choice",
      stage: 0,
      tag: "Неправильный глагол",
      q: "«Он написал мне письмо». Как правильно?",
      note: "write → wrote. «Writed» не существует.",
      options: [
        { t: "He wrote me a letter.", ok: true },
        { t: "He writed me a letter." },
        { t: "He write me a letter yesterday." },
      ],
      why: "He wrote me a letter — write → wrote.",
    },
    {
      kind: "choice",
      stage: 0,
      tag: "Неправильный глагол",
      q: "Найди ряд, где ВСЕ формы верные:",
      note: "Проверь по памяти: go, see, take, make…",
      options: [
        { t: "go → went, take → took, make → made", ok: true },
        { t: "go → goed, take → taked, make → maked" },
        { t: "go → went, take → took, make → maked" },
      ],
      why: "went, took, made — все три неправильные, и все меняются целиком.",
    },
    {
      kind: "fill",
      stage: 1,
      tag: "must",
      qBefore: "Passengers ",
      qAfter: " show their passports at the border.",
      hintRu: "Пассажиры должны показать паспорта на границе. (строгое «должны», одно слово)",
      note: "must — жёсткое правило, обязанность. После must глагол без to.",
      answer: "must",
      why: "Passengers must show their passports — правило без вариантов → must.",
    },
    {
      kind: "choice",
      stage: 1,
      tag: "mustn't",
      q: "Табличка у бассейна: «Здесь НЕЛЬЗЯ бегать». Как это по-английски?",
      note: "mustn't — строгий запрет («нельзя»).",
      options: [
        { t: "You mustn't run here.", ok: true },
        { t: "You don't have to run here.", },
        { t: "You shouldn't maybe run." },
      ],
      why: "You mustn't run here — запрет. Don't have to значило бы «можешь не бегать» — совсем другое!",
    },
    {
      kind: "choice",
      stage: 2,
      tag: "Не обязан",
      q: "«Вход бесплатный — платить НЕ ОБЯЗАТЕЛЬНО». Как это сказать?",
      note: "don't have to — «не обязан» (можно и не делать). Не путай с mustn't (запрещено)!",
      options: [
        { t: "You don't have to pay.", ok: true },
        { t: "You mustn't pay." },
        { t: "You can't pay." },
      ],
      why: "You don't have to pay — «Можешь не платить». Mustn't pay значило бы «платить запрещено» 🙂",
    },
    {
      kind: "choice",
      stage: 2,
      tag: "Проверь себя",
      q: "В чём разница между «You mustn't go» и «You don't have to go»?",
      note: "Это главная ловушка темы. Подумай, где запрет, а где свобода.",
      options: [
        { t: "Первое — «идти нельзя», второе — «можешь не идти»", ok: true },
        { t: "Это одно и то же" },
        { t: "Первое вежливее второго" },
      ],
      why: "mustn't = запрет, don't have to = отсутствие обязанности. Противоположные смыслы при похожем виде!",
    },
    {
      kind: "fill",
      stage: 3,
      tag: "Превосходная",
      qBefore: "Almaty is the ",
      qAfter: " city in Kazakhstan for me.",
      hintRu: "Алматы для меня — самый красивый город Казахстана… нет, стоп: САМЫЙ ЛУЧШИЙ! (good → better → the …)",
      note: "Лесенка good → better → the best.",
      answer: "best",
      why: "The best city — «самый лучший город». Патриотично и грамматически верно!",
    },
    {
      kind: "assemble",
      stage: 4,
      tag: "Финал",
      q: "Собери фразу с прошедшим и превосходной степенью: «Это был лучший день лета»:",
      note: "was (прошлое от is) + the best (самый лучший) + of the summer.",
      words: ["It", "was", "the", "best", "day", "of", "the", "summer."],
      answer: "It was the best day of the summer.",
      why: "It was the best day of the summer — прошедшее время и превосходная степень в одной фразе. Тренажёр пройден!",
    },
  ],
  words: [],
};

export default drills;
