import type { Chapter } from "@/lib/types";

const chapter4: Chapter = {
  slug: "if-i-were-you",
  title: "Если бы я был тобой",
  subtitle:
    "Дождливый вечер, чай и большая идея Данияра. Учимся строить условия: «если…, то…» — и давать советы мечтателям: «If I were you…».",
  goals: [
    "строить реальные условия: «если…, то…»",
    "давать совет через «на твоём месте я бы…»",
    "обсуждать риски и поддерживать друга",
    "договариваться о совместном деле",
  ],
  stages: [
    { icon: "🌧️", name: "Вечер" },
    { icon: "💡", name: "Идея" },
    { icon: "🤔", name: "Сомнения" },
    { icon: "🗣️", name: "Совет" },
    { icon: "🚀", name: "Решение" },
  ],
  steps: [
    {
      kind: "story",
      stage: 0,
      en: "A rainy London evening. Daniyar comes to your flat with pizza and a strange look in his eyes. «I have an idea, — he says. — A big one».",
      ru: "Дождливый лондонский вечер. Данияр приходит к тебе с пиццей и странным блеском в глазах. «У меня идея, — говорит он. — Большая».",
    },
    {
      kind: "story",
      stage: 1,
      who: "Данияр",
      say: "A free app for learning languages — through stories, not boring cards! If people like it, we will make it big.",
      ru: "Бесплатное приложение для изучения языков — через истории, а не скучные карточки! Если людям понравится, мы сделаем его большим.",
    },
    {
      kind: "choice",
      stage: 1,
      tag: "Пойми условие",
      q: "«If people like it, we will make it big» — как устроена эта фраза?",
      note: "Условие: If + настоящее время, will + действие. «Если понравится (сейчас) — сделаем (потом)». Запомни: после if НЕТ will!",
      options: [
        { t: "Если понравится — сделаем большим (условие → результат)", ok: true },
        { t: "Людям уже понравилось приложение" },
        { t: "Приложение уже большое" },
      ],
      why: "If people like it, we will make it big — «Если людям понравится, мы сделаем его большим». If-часть — условие, will-часть — результат.",
    },
    {
      kind: "fill",
      stage: 1,
      tag: "Впиши слово",
      qBefore: "If we work together, it ",
      qAfter: " be amazing!",
      hintRu: "Если мы будем работать вместе, это будет потрясающе! (слово-будущее в части результата)",
      note: "В условии два куска: if + настоящее (work), результат + will (will be). Will живёт только во второй части!",
      rule: "first-conditional",
      answer: "will",
      why: "If we work together, it will be amazing! — «Если будем работать вместе — будет потрясающе!» Ты только что построил условное предложение.",
      phrase: { en: "If we work together, it will be amazing!", ru: "Если будем работать вместе — будет потрясающе!" },
    },
    {
      kind: "story",
      stage: 2,
      en: "But then Daniyar's smile fades: «I don't know, man… I have a good job. A startup is risky. What would you do?»",
      ru: "Но улыбка Данияра гаснет: «Не знаю, дружище… У меня хорошая работа. Стартап — это риск. А ты бы что сделал?»",
    },
    {
      kind: "assemble",
      stage: 2,
      tag: "Собери фразу",
      q: "Дай другу совет мечты — «на твоём месте я бы попробовал»:",
      note: "Совет-фантазия: If I were you, I would… — «Если бы я был тобой, я бы…». Да, were даже с I — это специальная форма для фантазий!",
      rule: "second-conditional",
      words: ["If", "I", "were", "you,", "I", "would", "try."],
      answer: "If I were you, I would try.",
      why: "If I were you, I would try — «На твоём месте я бы попробовал». Were + would = мир фантазий и советов. Самая тёплая формула английского.",
      phrase: { en: "If I were you, I would try.", ru: "На твоём месте я бы попробовал." },
    },
    {
      kind: "listen",
      stage: 2,
      tag: "Аудирование",
      q: "Данияр задумался и спрашивает тебя о главном. О чём?",
      audio: "Would you build it with me?",
      note: "Would you…? — «А ты бы…?» (вопрос-фантазия). Build — строить, создавать. With me — со мной.",
      options: [
        { t: "Стал бы ты делать это вместе с ним", ok: true },
        { t: "Купил бы ты его приложение" },
        { t: "Уволился бы ты с работы" },
      ],
      why: "Would you build it with me? — «Ты бы стал делать это со мной?» Вот он, настоящий вопрос этого вечера.",
    },
    {
      kind: "choice",
      stage: 3,
      tag: "Поддержи друга",
      q: "Данияр всё ещё сомневается. Подбодри его!",
      note: "Give up — сдаваться. Don't give up! — «Не сдавайся!» Дословно give up — «отдать наверх» (свою мечту, например).",
      options: [
        { t: "Don't give up! Your idea is great!", ok: true },
        { t: "Give up! It's too risky!" },
        { t: "I'm afraid she is in a meeting." },
      ],
      why: "Don't give up! — «Не сдавайся!» Иногда одна фраза друга решает всё.",
      phrase: { en: "Don't give up!", ru: "Не сдавайся!" },
    },
    {
      kind: "fill",
      stage: 3,
      tag: "Впиши слово",
      qBefore: "If you need help, I ",
      qAfter: " always help you.",
      hintRu: "Если тебе понадобится помощь — я всегда помогу. (обещание в части результата)",
      note: "Снова условие: if + настоящее (need), результат + will. Обещания друзьям строятся именно так.",
      answer: "will",
      why: "If you need help, I will always help you — «Если понадобится помощь — я всегда помогу». Условие + обещание = дружба по-английски.",
      phrase: { en: "If you need help, I will help you.", ru: "Если нужна помощь — я помогу." },
    },
    {
      kind: "assemble",
      stage: 4,
      tag: "Собери фразу",
      q: "Данияр встаёт и протягивает руку. Скажи главные слова:",
      note: "Do it — сделать это, together — вместе. Let's — ты знаешь это слово с прогулки по Лондону!",
      words: ["Let's", "do", "it", "together!"],
      answer: "Let's do it together!",
      why: "Let's do it together! — «Давай сделаем это вместе!» Решение принято: по вечерам вы строите своё приложение.",
      phrase: { en: "Let's do it together!", ru: "Давай сделаем это вместе!" },
    },
    {
      kind: "story",
      stage: 4,
      en: "Midnight. Two laptops, cold pizza, the first sketch of the app on a napkin. If two friends believe in an idea… you know how this sentence ends.",
      ru: "Полночь. Два ноутбука, остывшая пицца, первый набросок приложения на салфетке. Если два друга верят в идею… ты уже знаешь, как заканчивается это предложение.",
    },
  ],
  words: [
    { en: "if + present, will…", ru: "если…, то… (реальное условие)" },
    { en: "If I were you, I would…", ru: "на твоём месте я бы…" },
    { en: "would you…?", ru: "а ты бы…?" },
    { en: "risky", ru: "рискованный" },
    { en: "don't give up", ru: "не сдавайся" },
    { en: "together", ru: "вместе" },
  ],
};

export default chapter4;
