import type { Chapter } from "@/lib/types";

const chapter2: Chapter = {
  slug: "global-team",
  title: "Команда со всего мира",
  subtitle:
    "Прия из Индии, Лукас из Бразилии, Эмма из Шотландии — теперь это твоя команда. Учимся высказывать мнение и вежливо не соглашаться.",
  goals: [
    "высказывать своё мнение",
    "вежливо не соглашаться и приводить довод",
    "предлагать компромисс",
    "поддерживать обсуждение в команде",
  ],
  stages: [
    { icon: "🏢", name: "Офис" },
    { icon: "🌍", name: "Команда" },
    { icon: "💬", name: "Дискуссия" },
    { icon: "🤝", name: "Компромисс" },
    { icon: "☕", name: "После работы" },
  ],
  steps: [
    {
      kind: "story",
      stage: 0,
      en: "Your first day as a full-time team member. Sarah introduces everyone: Priya from India, Lucas from Brazil, Emma from Scotland. Three accents, one team.",
      ru: "Первый день в штате. Сара знакомит тебя со всеми: Прия из Индии, Лукас из Бразилии, Эмма из Шотландии. Три акцента, одна команда.",
    },
    {
      kind: "story",
      stage: 1,
      en: "The team is choosing a design for the new app. Two versions on the screen: blue and green. Priya turns to you…",
      ru: "Команда выбирает дизайн для нового приложения. На экране две версии: синяя и зелёная. Прия поворачивается к тебе…",
    },
    {
      kind: "listen",
      stage: 1,
      tag: "Аудирование",
      q: "Что спросила Прия?",
      audio: "What do you think about the new design?",
      note: "What do you think about…? — «Что ты думаешь о…?» Главный вопрос любого обсуждения. Лови слово think — думать.",
      options: [
        { t: "Что ты думаешь о новом дизайне", ok: true },
        { t: "Когда будет готов дизайн" },
        { t: "Кто сделал новый дизайн" },
      ],
      why: "What do you think about the new design? — «Что думаешь о новом дизайне?» Тебя спрашивают — значит, твоё мнение важно.",
      phrase: { en: "What do you think?", ru: "Что ты думаешь?" },
    },
    {
      kind: "assemble",
      stage: 1,
      tag: "Собери фразу",
      q: "Выскажи мнение — синяя версия действительно хороша:",
      note: "Мнение начинают с I think… — «я думаю, что…». Really — действительно, по-настоящему.",
      words: ["I", "think", "the", "blue", "version", "is", "really", "good."],
      answer: "I think the blue version is really good.",
      why: "I think… — вежливый вход в любое мнение. Сравни: «Blue is good» звучит как факт, «I think blue is good» — как мнение, с которым можно спорить.",
      phrase: { en: "I think…", ru: "Я думаю, что…" },
    },
    {
      kind: "story",
      stage: 2,
      en: "Lucas shakes his head — he likes the green one. Now, this is important: how do the British disagree? Very, very politely.",
      ru: "Лукас качает головой — ему нравится зелёная. И тут важный момент: как спорят по-английски? Очень, очень вежливо.",
    },
    {
      kind: "choice",
      stage: 2,
      tag: "Вежливый спор",
      q: "Как вежливо не согласиться с Лукасом?",
      note: "Формула вежливого спора: сначала признай (I see your point — «понимаю твою мысль»), потом не согласись (but I don't agree — «но я не согласен»).",
      rule: "opinions",
      options: [
        { t: "I see your point, but I don't agree.", ok: true },
        { t: "You are wrong!" },
        { t: "No. Blue. The end." },
      ],
      why: "I see your point, but I don't agree — «Понимаю тебя, но не согласен». Уважение + несогласие = так спорят профессионалы.",
      phrase: { en: "I see your point, but I don't agree.", ru: "Понимаю вас, но не согласен." },
    },
    {
      kind: "fill",
      stage: 2,
      tag: "Впиши слово",
      qBefore: "In my ",
      qAfter: ", the blue version is easier to read.",
      hintRu: "По моему мнению, синюю версию легче читать.",
      note: "Ещё один способ ввести мнение: In my opinion… — «по моему мнению». Opinion — мнение.",
      answer: "opinion",
      why: "In my opinion… — звучит чуть весомее, чем I think. Отлично подходит для рабочих обсуждений.",
      phrase: { en: "In my opinion…", ru: "По моему мнению…" },
    },
    {
      kind: "listen",
      stage: 3,
      tag: "Аудирование",
      q: "Эмма вступает в дискуссию. На чьей она стороне?",
      audio: "I agree with Alim. Blue looks more professional.",
      note: "Agree — соглашаться. I agree with + имя — «я согласна с …». Лови имя после with!",
      options: [
        { t: "Согласна с тобой (Алимом)", ok: true },
        { t: "Согласна с Лукасом" },
        { t: "Против обеих версий" },
      ],
      why: "I agree with Alim — «Я согласна с Алимом». Твоё первое выигранное обсуждение в команде!",
      phrase: { en: "I agree with you.", ru: "Я с тобой согласен." },
    },
    {
      kind: "assemble",
      stage: 3,
      tag: "Собери фразу",
      q: "Лукас всё ещё сомневается. Предложи компромисс:",
      note: "Let's + действие — «давайте…» (ты помнишь let's go!). Both — оба, обе. Test — проверить.",
      words: ["Let's", "test", "both", "versions", "with", "users!"],
      answer: "Let's test both versions with users!",
      why: "Let's test both versions with users! — «Давайте проверим обе версии на пользователях!» Лучший аргумент в споре — данные.",
      phrase: { en: "Let's test both!", ru: "Давайте проверим оба варианта!" },
    },
    {
      kind: "choice",
      stage: 3,
      tag: "Пойми реакцию",
      q: "Лукас улыбается: «That makes sense!» Что он сказал?",
      note: "Make sense — «иметь смысл». That makes sense — реакция на разумную идею.",
      options: [
        { t: "Это разумно / логично", ok: true },
        { t: "Это бессмысленно" },
        { t: "Это смешно" },
      ],
      why: "That makes sense! — «Логично!» Спор закончился компромиссом — и все довольны. Так работают сильные команды.",
      phrase: { en: "That makes sense!", ru: "Это логично!" },
    },
    {
      kind: "story",
      stage: 4,
      en: "After work the whole team goes to a pub near the office. Priya tells stories about Mumbai, Lucas — about Rio carnivals, Emma teaches everyone Scottish words. You understand almost everything — and it feels like magic.",
      ru: "После работы вся команда идёт в паб у офиса. Прия рассказывает про Мумбаи, Лукас — про карнавалы в Рио, Эмма учит всех шотландским словечкам. Ты понимаешь почти всё — и это похоже на волшебство.",
    },
  ],
  words: [
    { en: "What do you think?", ru: "что ты думаешь?" },
    { en: "I think… / In my opinion…", ru: "я думаю… / по моему мнению…" },
    { en: "I agree / I don't agree", ru: "согласен / не согласен" },
    { en: "I see your point", ru: "понимаю вашу мысль" },
    { en: "both", ru: "оба, обе" },
    { en: "that makes sense", ru: "это логично" },
  ],
};

export default chapter2;
