import type { Chapter } from "@/lib/types";

const chapter3: Chapter = {
  slug: "calls-and-emails",
  title: "Звонок и письмо",
  subtitle:
    "Первый рабочий звонок клиенту и первое деловое письмо. Телефонные формулы, «Dear Ms Carter» и волшебное «Best regards».",
  goals: [
    "вести деловой телефонный разговор",
    "понимать секретаря и просить перезвонить",
    "писать деловое письмо по структуре",
    "договариваться о встрече",
  ],
  stages: [
    { icon: "☎️", name: "Звонок" },
    { icon: "📞", name: "Разговор" },
    { icon: "📧", name: "Письмо" },
    { icon: "✍️", name: "Ответ" },
    { icon: "✅", name: "Встреча" },
  ],
  steps: [
    {
      kind: "story",
      stage: 0,
      en: "Sarah gives you a serious task: call the client — Bright Web company — and discuss the project with Ms Carter. Your first business call in English. Deep breath!",
      ru: "Сара даёт серьёзное задание: позвонить клиенту — компании Bright Web — и обсудить проект с мисс Картер. Твой первый деловой звонок на английском. Глубокий вдох!",
    },
    {
      kind: "assemble",
      stage: 0,
      tag: "Собери фразу",
      q: "Секретарь взял трубку. Попроси соединить с мисс Картер:",
      note: "Телефонная формула: Could I speak to + имя + please? Could — то самое супервежливое can из главы про врача.",
      rule: "polite-requests",
      words: ["Could", "I", "speak", "to", "Ms", "Carter,", "please?"],
      answer: "Could I speak to Ms Carter, please?",
      why: "Could I speak to Ms Carter, please? — «Могу я поговорить с мисс Картер?» Стандартное начало любого делового звонка.",
      phrase: { en: "Could I speak to…, please?", ru: "Могу я поговорить с…?" },
    },
    {
      kind: "listen",
      stage: 1,
      tag: "Аудирование",
      q: "Что ответил секретарь?",
      audio: "Hold on a moment, please.",
      note: "Hold on — «оставайтесь на линии, подождите» (дословно «держитесь»). A moment — секундочку.",
      options: [
        { t: "Подождите минутку", ok: true },
        { t: "Перезвоните позже" },
        { t: "Вы ошиблись номером" },
      ],
      why: "Hold on a moment, please — «Подождите минутку». Услышишь в каждом втором звонке.",
      phrase: { en: "Hold on a moment, please.", ru: "Подождите минутку." },
    },
    {
      kind: "choice",
      stage: 1,
      tag: "Пойми ответ",
      q: "Секретарь возвращается: «I'm afraid she is in a meeting. Can she call you back?» Что это значит?",
      note: "I'm afraid… — «боюсь, что…» (вежливое сожаление, страха тут нет). Call back — перезвонить.",
      options: [
        { t: "Она на встрече, перезвонит вам", ok: true },
        { t: "Она боится встреч и не позвонит" },
        { t: "Она уехала из офиса навсегда" },
      ],
      why: "I'm afraid she is in a meeting. Can she call you back? — «К сожалению, она на встрече. Может она вам перезвонить?» I'm afraid — просто вежливое «увы».",
      phrase: { en: "Can I call you back?", ru: "Могу я вам перезвонить?" },
    },
    {
      kind: "fill",
      stage: 1,
      tag: "Впиши слово",
      qBefore: "Yes, of course. Please ask her to call me ",
      qAfter: " after lunch.",
      hintRu: "Да, конечно. Попросите её перезвонить мне после обеда.",
      note: "Перезвонить = call back. Back — «обратно»: call back — позвонить обратно, come back — вернуться (помнишь Данияра?).",
      answer: "back",
      why: "Call me back — «перезвоните мне». Слово back превращает действие в «обратное»: call → call back, write → write back.",
    },
    {
      kind: "story",
      stage: 2,
      en: "While you wait, Sarah suggests: «Send her an email too. Business emails have rules — let me show you». She opens her laptop.",
      ru: "Пока ждёшь звонка, Сара советует: «Отправь ей ещё и письмо. У деловых писем есть правила — сейчас покажу». Она открывает ноутбук.",
    },
    {
      kind: "choice",
      stage: 2,
      tag: "Начни письмо",
      q: "Как правильно начать деловое письмо мисс Картер?",
      note: "Деловое письмо начинают с Dear + имя («уважаемый/ая»). Dear Ms Carter, — и обязательно запятая. «Hey!» оставь для друзей.",
      rule: "business-letter",
      options: [
        { t: "Dear Ms Carter,", ok: true },
        { t: "Hey Carter!" },
        { t: "Hello my dear friend!!!" },
      ],
      why: "Dear Ms Carter, — единственно верное начало формального письма. Dear здесь не «дорогая», а «уважаемая».",
      phrase: { en: "Dear Ms Carter,", ru: "Уважаемая мисс Картер, (начало письма)" },
    },
    {
      kind: "assemble",
      stage: 2,
      tag: "Собери фразу",
      q: "Первая строка письма — объясни, о чём пишешь:",
      note: "Классическое начало: I am writing about… — «Я пишу по поводу…». Сразу к делу — англичане это ценят.",
      words: ["I", "am", "writing", "about", "our", "project."],
      answer: "I am writing about our project.",
      why: "I am writing about our project — «Пишу по поводу нашего проекта». Первая строка письма всегда отвечает на вопрос «зачем я пишу».",
      phrase: { en: "I am writing about…", ru: "Я пишу по поводу…" },
    },
    {
      kind: "fill",
      stage: 3,
      tag: "Впиши слово",
      qBefore: "Best ",
      qAfter: ",\nAlim",
      hintRu: "С уважением, Алим. (стандартная подпись делового письма)",
      note: "Деловое письмо заканчивают подписью Best regards, — «с наилучшими пожеланиями / с уважением». Regards — пожелания.",
      answer: "regards",
      why: "Best regards, — самая универсальная подпись: не слишком холодно, не слишком тепло. Запомни как единое целое.",
      phrase: { en: "Best regards,", ru: "С уважением, (подпись)" },
    },
    {
      kind: "choice",
      stage: 3,
      tag: "Проверь себя",
      q: "Собери скелет делового письма по порядку:",
      note: "Порядок всегда один: приветствие → зачем пишу → суть → подпись.",
      options: [
        { t: "Dear… → I am writing about… → суть → Best regards", ok: true },
        { t: "Best regards → суть → Dear…" },
        { t: "Hey! → шутка → суть → пока!" },
      ],
      why: "Dear + имя → I am writing about… → суть дела → Best regards + имя. Этот скелет подходит для 90% деловых писем.",
    },
    {
      kind: "listen",
      stage: 4,
      tag: "Аудирование",
      q: "Через час — голосовое от мисс Картер! Что она предлагает?",
      audio: "Thank you for your email. Let's meet on Friday at eleven.",
      note: "Лови день недели и время: Friday — пятница, eleven — 11. Monday, Tuesday, Wednesday, Thursday, Friday — рабочая неделя.",
      options: [
        { t: "Встретиться в пятницу в 11", ok: true },
        { t: "Встретиться в четверг в 10" },
        { t: "Созвониться в понедельник" },
      ],
      why: "Let's meet on Friday at eleven — «Встретимся в пятницу в 11». Заметь: on + день недели, at + время.",
    },
    {
      kind: "story",
      stage: 4,
      en: "Meeting booked, email sent, client happy. Sarah gives you a thumbs up: «Your first business call and email — done like a pro!»",
      ru: "Встреча назначена, письмо отправлено, клиент доволен. Сара показывает большой палец: «Первый деловой звонок и письмо — сделано как у профи!»",
    },
  ],
  words: [
    { en: "Could I speak to…?", ru: "могу я поговорить с…?" },
    { en: "hold on", ru: "подождите (на линии)" },
    { en: "call back", ru: "перезвонить" },
    { en: "I'm afraid…", ru: "боюсь, что… (вежливое «увы»)" },
    { en: "Dear… / Best regards", ru: "уважаемый… / с уважением (письмо)" },
    { en: "on Friday at eleven", ru: "в пятницу в 11 (on + день, at + время)" },
  ],
};

export default chapter3;
