import type { Chapter } from "@/lib/types";

const chapter1: Chapter = {
  slug: "new-life",
  title: "Новая жизнь",
  subtitle:
    "Компания зовёт Алима в Лондон насовсем! Переезд, свой район и новое время — Present Perfect: «Have you ever…?» — «А ты когда-нибудь…?»",
  goals: [
    "спрашивать об опыте: «Ты когда-нибудь…?»",
    "рассказывать, чего я никогда не делал",
    "сообщать о сделанном через already",
    "говорить, сколько времени я где-то живу или работаю",
  ],
  stages: [
    { icon: "✈️", name: "Переезд" },
    { icon: "🏙️", name: "Свой район" },
    { icon: "🛋️", name: "Квартира" },
    { icon: "🍛", name: "Ужин" },
    { icon: "🌙", name: "Первая ночь" },
  ],
  steps: [
    {
      kind: "story",
      stage: 0,
      en: "Six months of remote work — and one day a message from Sarah: «The team wants you here. Move to London!» And now you are on the plane again. This time — with a one-way ticket.",
      ru: "Полгода удалённой работы — и однажды сообщение от Сары: «Команда хочет видеть тебя здесь. Переезжай в Лондон!» И вот ты снова в самолёте. На этот раз — с билетом в один конец.",
    },
    {
      kind: "story",
      stage: 0,
      who: "Данияр",
      say: "Third time at this airport! Tell me — have you ever lived abroad?",
      ru: "Третий раз в этом аэропорту! Скажи-ка — ты когда-нибудь жил за границей?",
    },
    {
      kind: "choice",
      stage: 0,
      tag: "Пойми вопрос",
      q: "«Have you ever lived abroad?» — о чём спросил Данияр?",
      note: "Новое время — Present Perfect: have + глагол с -ed. Оно про ОПЫТ за всю жизнь. Ever — «когда-нибудь», abroad — за границей.",
      options: [
        { t: "Жил ли ты когда-нибудь за границей", ok: true },
        { t: "Где ты жил в прошлом году" },
        { t: "Хочешь ли ты жить за границей" },
      ],
      why: "Have you ever lived abroad? — «Ты когда-нибудь жил за границей?» Не «когда» и не «где» — а был ли такой опыт вообще.",
      phrase: { en: "Have you ever…?", ru: "Ты когда-нибудь…?" },
    },
    {
      kind: "fill",
      stage: 0,
      tag: "Впиши слово",
      qBefore: "No, I have ",
      qAfter: " lived abroad. This is my first time!",
      hintRu: "Нет, я никогда не жил за границей. Это первый раз!",
      note: "Ответ на Have you ever…? — часто через never («никогда»): I have never + глагол. Заметь: not не нужно, never уже отрицание.",
      rule: "perfect-signals",
      answer: "never",
      why: "I have never lived abroad — «Я никогда не жил за границей». Пара ever/never — сердце разговоров об опыте.",
      phrase: { en: "I have never…", ru: "Я никогда не…" },
    },
    {
      kind: "assemble",
      stage: 1,
      tag: "Собери фразу",
      q: "Вы едете по городу. Скажи, что мечтал об этом:",
      note: "Present Perfect соединяет прошлое с сейчас: I have dreamed — «я мечтал (и вот оно сбылось!)». Dream → dreamed.",
      rule: "present-perfect",
      words: ["I", "have", "dreamed", "about", "this!"],
      answer: "I have dreamed about this!",
      why: "I have dreamed about this! — «Я мечтал об этом!» Have + -ed говорит: прошлое, которое важно прямо сейчас.",
      phrase: { en: "I have dreamed about this!", ru: "Я мечтал об этом!" },
    },
    {
      kind: "listen",
      stage: 2,
      tag: "Аудирование",
      q: "У Данияра сюрприз. Послушай — что он уже сделал?",
      audio: "I have already found a flat for you.",
      note: "Already — «уже». Have found — нашёл (find — неправильный: find → found). Лови already — слово-сюрприз!",
      options: [
        { t: "Уже нашёл для тебя квартиру", ok: true },
        { t: "Уже купил тебе мебель" },
        { t: "Уже нашёл тебе машину" },
      ],
      why: "I have already found a flat for you — «Я уже нашёл тебе квартиру». Already + Present Perfect = приятная новость о сделанном.",
    },
    {
      kind: "story",
      stage: 2,
      en: "The flat is small but sunny, ten minutes from the office. Through the window — a park where people play football and drink flat whites.",
      ru: "Квартира маленькая, но солнечная, десять минут от офиса. За окном — парк, где играют в футбол и пьют кофе.",
    },
    {
      kind: "choice",
      stage: 2,
      tag: "Пойми фразу",
      q: "Данияр говорит: «I have lived in this area for two years». Что это значит?",
      note: "Present Perfect + for + срок = «живу уже столько-то» (начал в прошлом и ПРОДОЛЖАЮ сейчас). Area — район.",
      options: [
        { t: "Он живёт в этом районе уже два года", ok: true },
        { t: "Он жил здесь два года назад, а теперь нет" },
        { t: "Он переедет сюда через два года" },
      ],
      why: "I have lived here for two years — «Живу здесь уже два года» (и продолжаю!). Если бы уехал, сказал бы: I lived here two years ago.",
    },
    {
      kind: "story",
      stage: 3,
      en: "Evening. Daniyar takes you to his favourite place: «Brick Lane! The best curry in London. Time for a food adventure!»",
      ru: "Вечер. Данияр ведёт тебя в своё любимое место: «Брик-лейн! Лучшее карри в Лондоне. Время гастрономических приключений!»",
    },
    {
      kind: "fill",
      stage: 3,
      tag: "Впиши слово",
      qBefore: "Have you ",
      qAfter: " tried Indian food?",
      hintRu: "Ты когда-нибудь пробовал индийскую еду? (то самое слово-«когда-нибудь»)",
      note: "Вопрос об опыте: Have you ever + глагол? Ever встаёт между you и глаголом.",
      answer: "ever",
      why: "Have you ever tried Indian food? — «Ты когда-нибудь пробовал индийскую еду?» Теперь ты умеешь задавать вопросы об опыте сам.",
    },
    {
      kind: "assemble",
      stage: 3,
      tag: "Собери фразу",
      q: "Признайся честно — никогда не пробовал:",
      note: "Формула из начала главы: I have never + глагол. Tried — пробовал (try → tried).",
      words: ["I", "have", "never", "tried", "it!"],
      answer: "I have never tried it!",
      why: "I have never tried it! — «Никогда не пробовал!» Через полчаса эта фраза перестанет быть правдой 🌶️",
    },
    {
      kind: "story",
      stage: 4,
      en: "Night. Your first night in YOUR London flat. Boxes everywhere, curry in your stomach, plans in your head. A new life has started.",
      ru: "Ночь. Первая ночь в ТВОЕЙ лондонской квартире. Повсюду коробки, в животе карри, в голове планы. Новая жизнь началась.",
    },
  ],
  words: [
    { en: "have you ever…?", ru: "ты когда-нибудь…?" },
    { en: "never", ru: "никогда" },
    { en: "already", ru: "уже" },
    { en: "abroad", ru: "за границей" },
    { en: "for two years", ru: "уже два года (и до сих пор)" },
    { en: "area", ru: "район" },
  ],
};

export default chapter1;
