import type { Chapter } from "@/lib/types";

const chapter6: Chapter = {
  slug: "your-own-story",
  title: "Своя история",
  subtitle:
    "Финал сезона: вы с Данияром запускаете своё приложение. Первая тысяча пользователей, звонок из Алматы и фраза, с которой всё началось.",
  goals: [
    "рассказывать о результатах своей работы",
    "понимать отзывы пользователей",
    "говорить о том, что длится до сих пор",
    "выражать благодарность и веру в человека",
  ],
  stages: [
    { icon: "🚀", name: "Запуск" },
    { icon: "🌍", name: "Пользователи" },
    { icon: "📞", name: "Звонок домой" },
    { icon: "🎉", name: "Праздник" },
    { icon: "🌟", name: "Финал" },
  ],
  steps: [
    {
      kind: "story",
      stage: 0,
      en: "Three months of evenings and weekends — and today is the day. You and Daniyar press the big green button: your language-learning app is live. Free. For everyone.",
      ru: "Три месяца вечеров и выходных — и вот этот день. Вы с Данияром нажимаете большую зелёную кнопку: ваше приложение для изучения языков запущено. Бесплатное. Для всех.",
    },
    {
      kind: "listen",
      stage: 0,
      tag: "Аудирование",
      q: "Неделя после запуска. Данияр вбегает с новостью — какой?",
      audio: "One thousand people have joined this week!",
      note: "Thousand — тысяча. Have joined — присоединились (Present Perfect: свершилось — и это важно сейчас!).",
      options: [
        { t: "За неделю присоединилась тысяча человек", ok: true },
        { t: "За неделю пришло сто человек" },
        { t: "Приложение сломалось" },
      ],
      why: "One thousand people have joined this week! — «За эту неделю присоединилась тысяча человек!» Ваша история работает.",
    },
    {
      kind: "fill",
      stage: 0,
      tag: "Впиши слово",
      qBefore: "We ",
      qAfter: " built something important.",
      hintRu: "Мы создали что-то важное. (достижение — то самое время опыта!)",
      note: "Достижение = Present Perfect: have + built (build — неправильный: build → built). We have built — «мы построили (и вот оно, работает!)».",
      answer: "have",
      why: "We have built something important — «Мы создали что-то важное». Have + built: результат, которым живёшь прямо сейчас.",
      phrase: { en: "We have built something important.", ru: "Мы создали что-то важное." },
    },
    {
      kind: "choice",
      stage: 1,
      tag: "Пойми отзыв",
      q: "Первый отзыв пользователя: «This app has changed my English!» Что это значит?",
      note: "Has changed — изменило (Present Perfect для he/she/it — has вместо have!). Change — менять.",
      options: [
        { t: "Приложение изменило его английский", ok: true },
        { t: "Приложение поменяло язык интерфейса" },
        { t: "Пользователь просит изменить приложение" },
      ],
      why: "This app has changed my English! — «Это приложение изменило мой английский!» Заметь: it → has (не have). Лучший отзыв, о котором можно мечтать.",
    },
    {
      kind: "assemble",
      stage: 1,
      tag: "Собери фразу",
      q: "Ответь пользователю — вся суть вашего проекта в одной фразе:",
      note: "Соединяем всё, что ты знаешь: dreams — мечты, come true — сбываются, if — если, work hard — усердно работать (фраза с твоего первого собеседования!).",
      words: ["Dreams", "come", "true", "if", "you", "work", "hard."],
      answer: "Dreams come true if you work hard.",
      why: "Dreams come true if you work hard — «Мечты сбываются, если усердно работать». Условное предложение — и чистая правда твоей истории.",
      phrase: { en: "Dreams come true if you work hard.", ru: "Мечты сбываются, если усердно работать." },
    },
    {
      kind: "story",
      stage: 2,
      en: "Evening. A video call to Almaty. On the screen — Aidana, your first English teacher. She has already downloaded the app.",
      ru: "Вечер. Видеозвонок в Алматы. На экране — Айдана, твой первый учитель английского. Она уже скачала приложение.",
    },
    {
      kind: "story",
      stage: 2,
      who: "Айдана",
      say: "I have always believed in you. Always!",
      ru: "Я всегда в тебя верила. Всегда!",
    },
    {
      kind: "choice",
      stage: 2,
      tag: "Пойми фразу",
      q: "«I have always believed in you» — что сказала Айдана?",
      note: "Always — всегда, believe in — верить в (кого-то). Have + always + believed: «верила всё это время — и верю сейчас».",
      options: [
        { t: "Она всегда верила в тебя", ok: true },
        { t: "Она всегда проверяла тебя" },
        { t: "Она поверила тебе только сейчас" },
      ],
      why: "I have always believed in you — «Я всегда в тебя верила». Present Perfect с always — чувство, которое началось давно и живёт до сих пор.",
      phrase: { en: "I believe in you.", ru: "Я верю в тебя." },
    },
    {
      kind: "fill",
      stage: 2,
      tag: "Впиши слово",
      qBefore: "Thank you! Everything started with your first ",
      qAfter: ": «Hello!»",
      hintRu: "Спасибо! Всё началось с вашего первого урока: «Hello!» (lesson — урок)",
      note: "Lesson — урок. Помнишь свой первый урок в этом курсе? Он тоже начинался со слова Hello!",
      answer: "lesson",
      why: "Everything started with your first lesson — «Всё началось с вашего первого урока». Первое слово было Hello — и посмотри, куда оно привело.",
    },
    {
      kind: "story",
      stage: 3,
      en: "Friday night. The whole team celebrates in your favourite pub: Sarah, Tom, Priya, Lucas, Emma — and Daniyar, of course. Emma raises her glass…",
      ru: "Вечер пятницы. Вся команда празднует в вашем любимом пабе: Сара, Том, Прия, Лукас, Эмма — и, конечно, Данияр. Эмма поднимает бокал…",
    },
    {
      kind: "listen",
      stage: 3,
      tag: "Аудирование",
      q: "Тост Эммы! За что пьёт команда?",
      audio: "To Alim — the man who came here with one suitcase and built a new life!",
      note: "Suitcase — чемодан (самое первое слово сезона 1!). Built — построил. Слушай внимательно — это тост про твой путь.",
      options: [
        { t: "За Алима, который приехал с одним чемоданом и построил новую жизнь", ok: true },
        { t: "За новое приложение команды" },
        { t: "За пятницу и выходные" },
      ],
      why: "«За Алима — человека, который приехал с одним чемоданом и построил новую жизнь!» Where is my suitcase? — помнишь? Вот куда привёл тот чемодан.",
    },
    {
      kind: "assemble",
      stage: 4,
      tag: "Собери фразу",
      q: "Твой ответный тост — последняя фраза сезона:",
      note: "Beginning — начало (от begin — начинать). Only — только, лишь.",
      words: ["This", "is", "only", "the", "beginning!"],
      answer: "This is only the beginning!",
      why: "This is only the beginning! — «Это только начало!» Сезон 3 завершён: у героя есть команда, своё дело и язык, на котором он живёт. Дальше — B2, финал большой истории.",
      phrase: { en: "This is only the beginning!", ru: "Это только начало!" },
    },
    {
      kind: "story",
      stage: 4,
      en: "Somewhere in Almaty, a student opens your app and reads the first word: «Hello!» A new story begins — exactly like yours once did.",
      ru: "Где-то в Алматы студент открывает ваше приложение и читает первое слово: «Hello!» Начинается новая история — точно так же, как когда-то началась твоя.",
    },
  ],
  words: [
    { en: "have / has + done", ru: "сделал (опыт, результат сейчас)" },
    { en: "one thousand", ru: "тысяча" },
    { en: "believe in you", ru: "верить в тебя" },
    { en: "dreams come true", ru: "мечты сбываются" },
    { en: "lesson", ru: "урок" },
    { en: "beginning", ru: "начало" },
  ],
};

export default chapter6;
