import type { Chapter } from "@/lib/types";

const chapter5: Chapter = {
  slug: "dream-job",
  title: "Работа мечты",
  subtitle:
    "В компании открылась позиция тимлида — и Сара говорит: «Подавайся!» Большое собеседование уровня B1: опыт, сильные стороны и правильные вопросы.",
  goals: [
    "подавать заявку на должность",
    "рассказывать о достижениях через Present Perfect",
    "называть свои сильные стороны",
    "задавать вопросы работодателю",
  ],
  stages: [
    { icon: "📢", name: "Вакансия" },
    { icon: "📝", name: "Заявка" },
    { icon: "🗣️", name: "Интервью" },
    { icon: "💼", name: "Опыт" },
    { icon: "🎯", name: "Решение" },
  ],
  steps: [
    {
      kind: "story",
      stage: 0,
      en: "Monday. A company announcement: «Junior Team Lead position open». Sarah stops by your desk: «You have grown so much this year. You should apply!»",
      ru: "Понедельник. Объявление в компании: «Открыта позиция Junior Team Lead». Сара подходит к твоему столу: «Ты так вырос за этот год. Подавайся!»",
    },
    {
      kind: "choice",
      stage: 0,
      tag: "Пойми слово",
      q: "Сара сказала «You should apply». Что значит apply?",
      note: "Apply for a job — подать заявку на работу. Application — сама заявка. Should ты помнишь — «стоит» (совет врача!).",
      options: [
        { t: "Подать заявку на позицию", ok: true },
        { t: "Отказаться от позиции" },
        { t: "Придумать позицию" },
      ],
      why: "Apply — подать заявку. You should apply! — «Тебе стоит подать заявку!» Когда так говорит твой менеджер — это знак.",
      phrase: { en: "I want to apply for this job.", ru: "Я хочу подать заявку на эту работу." },
    },
    {
      kind: "assemble",
      stage: 1,
      tag: "Собери фразу",
      q: "В заявке — главный факт о твоём опыте здесь:",
      note: "Present Perfect + for из главы «Новая жизнь»: I have worked here for… — «работаю здесь уже…» (и продолжаю!).",
      rule: "perfect-signals",
      words: ["I", "have", "worked", "here", "for", "one", "year."],
      answer: "I have worked here for one year.",
      why: "I have worked here for one year — «Я работаю здесь уже год». Опыт, который продолжается, — это всегда have + -ed + for.",
      phrase: { en: "I have worked here for one year.", ru: "Я работаю здесь уже год." },
    },
    {
      kind: "story",
      stage: 2,
      en: "Interview day. This time it's not a video call — a real meeting room, and opposite you sit Mr Reed and the HR director, Ms Osei.",
      ru: "День собеседования. На этот раз не видеозвонок — настоящая переговорка, а напротив мистер Рид и HR-директор мисс Осей.",
    },
    {
      kind: "listen",
      stage: 2,
      tag: "Аудирование",
      q: "Первый вопрос мисс Осей. О чём он?",
      audio: "What are your strengths?",
      note: "Strengths — сильные стороны (от strong — сильный). Классика собеседований: спросят обязательно, готовь ответ заранее.",
      options: [
        { t: "О твоих сильных сторонах", ok: true },
        { t: "О твоих слабостях" },
        { t: "О твоей зарплате" },
      ],
      why: "What are your strengths? — «Какие у вас сильные стороны?» Вопрос-близнец: What are your weaknesses? — о слабых.",
      phrase: { en: "What are your strengths?", ru: "Какие у вас сильные стороны?" },
    },
    {
      kind: "fill",
      stage: 2,
      tag: "Впиши слово",
      qBefore: "I have ",
      qAfter: " three big projects this year.",
      hintRu: "В этом году я завершил три больших проекта. (finish — но с have, опыт-достижение!)",
      note: "Достижения на собеседовании — через Present Perfect: I have finished, I have built, I have learned. Have + -ed = «сделал, и это важно сейчас».",
      answer: "finished",
      why: "I have finished three big projects this year — «Я завершил три больших проекта в этом году». Факты + Present Perfect = сильный ответ.",
    },
    {
      kind: "assemble",
      stage: 3,
      tag: "Собери фразу",
      q: "Мистер Рид спрашивает, почему ты хочешь быть тимлидом. Ответь честно:",
      note: "Enjoy + действие с -ing — «получать удовольствие от…»: I enjoy working — мне нравится работать. Помогать — help.",
      rule: "verb-patterns",
      words: ["I", "enjoy", "helping", "people", "grow."],
      answer: "I enjoy helping people grow.",
      why: "I enjoy helping people grow — «Мне нравится помогать людям расти». После enjoy глагол всегда с -ing: enjoy working, enjoy learning.",
      phrase: { en: "I enjoy helping people.", ru: "Мне нравится помогать людям." },
    },
    {
      kind: "choice",
      stage: 3,
      tag: "Задай свой вопрос",
      q: "В конце спрашивают: «Do you have any questions?» Хороший кандидат…",
      note: "«Do you have any questions?» — финал любого интервью. Отсутствие вопросов читается как отсутствие интереса!",
      options: [
        { t: "…задаёт вопрос о команде и задачах", ok: true },
        { t: "…говорит «нет вопросов» и уходит" },
        { t: "…спрашивает, где здесь кофемашина" },
      ],
      why: "Вопросы о команде, задачах и целях показывают интерес. Например: What will be my first project? — «Каким будет мой первый проект?»",
    },
    {
      kind: "assemble",
      stage: 3,
      tag: "Собери фразу",
      q: "Задай свой вопрос — про первый проект:",
      note: "Вопрос о будущем: What will + подлежащее + be…? My first project — мой первый проект.",
      words: ["What", "will", "my", "first", "project", "be?"],
      answer: "What will my first project be?",
      why: "What will my first project be? — «Каким будет мой первый проект?» Такой вопрос запоминается интервьюерам.",
    },
    {
      kind: "listen",
      stage: 4,
      tag: "Аудирование",
      q: "Прощаясь, мисс Осей говорит важное. Когда будет решение?",
      audio: "We have really enjoyed this conversation. You will hear from us on Wednesday.",
      note: "Hear from us — «получите от нас весточку». Лови день: Wednesday — среда, Friday — пятница.",
      options: [
        { t: "В среду", ok: true },
        { t: "В пятницу" },
        { t: "Через месяц" },
      ],
      why: "You will hear from us on Wednesday — «Мы свяжемся с вами в среду». И заметь: We have really enjoyed this conversation — это очень хороший знак!",
    },
    {
      kind: "fill",
      stage: 4,
      tag: "Впиши слово",
      qBefore: "Thank you for your ",
      qAfter: "!",
      hintRu: "Спасибо за ваше время! (вежливое завершение любой встречи)",
      note: "Финальная вежливость: Thank you for your time — «спасибо за уделённое время». Time — время.",
      answer: "time",
      why: "Thank you for your time! — «Спасибо за ваше время!» Идеальная последняя фраза собеседования, звонка и встречи.",
      phrase: { en: "Thank you for your time!", ru: "Спасибо за ваше время!" },
    },
    {
      kind: "story",
      stage: 4,
      en: "Wednesday, 9:00. An email: «Congratulations, Team Lead!» You read it three times. Then you call two people: your mother — and Daniyar.",
      ru: "Среда, 9:00. Письмо: «Поздравляем, тимлид!» Ты перечитываешь его три раза. Потом звонишь двум людям: маме — и Данияру.",
    },
  ],
  words: [
    { en: "apply (for a job)", ru: "подать заявку (на работу)" },
    { en: "strengths / weaknesses", ru: "сильные / слабые стороны" },
    { en: "I have worked here for…", ru: "я работаю здесь уже…" },
    { en: "enjoy + -ing", ru: "нравится (делать что-то)" },
    { en: "hear from us", ru: "получить от нас ответ" },
    { en: "thank you for your time", ru: "спасибо за ваше время" },
  ],
};

export default chapter5;
