import type { Chapter } from "@/lib/types";

const drills: Chapter = {
  slug: "drills-2",
  title: "Тренажёр 2: спутники Perfect и вежливые формы",
  subtitle:
    "Вторая тренировка уровня B1: just / yet / already, have been to, would like, глагольные связки и структура делового письма.",
  section: "exercise",
  stages: [
    { icon: "⏳", name: "Just / yet" },
    { icon: "🌍", name: "Have been to" },
    { icon: "🎩", name: "Вежливость" },
    { icon: "🧩", name: "Связки" },
    { icon: "✅", name: "Готово" },
  ],
  steps: [
    {
      kind: "fill",
      stage: 0,
      tag: "just",
      qBefore: "Don't call him — he has ",
      qAfter: " fallen asleep.",
      hintRu: "Не звони ему — он только что уснул. (слово-«только что» между has и глаголом)",
      note: "just — «только что», ставится между have/has и третьей формой.",
      answer: "just",
      why: "He has just fallen asleep — «Он только что уснул». Have/has + just + V3.",
    },
    {
      kind: "choice",
      stage: 0,
      tag: "yet",
      q: "«Ты уже поел?» Куда встаёт yet?",
      note: "yet живёт в КОНЦЕ вопросов и отрицаний.",
      options: [
        { t: "Have you eaten yet?", ok: true },
        { t: "Have you yet eaten?" },
        { t: "Yet have you eaten?" },
      ],
      why: "Have you eaten yet? — yet всегда в конце. В отрицании так же: I haven't eaten yet.",
    },
    {
      kind: "fill",
      stage: 0,
      tag: "already",
      qBefore: "We have ",
      qAfter: " finished the project!",
      hintRu: "Мы уже закончили проект! (слово-«уже» внутри Perfect)",
      note: "already — «уже», между have и глаголом. Приятное слово хороших новостей.",
      answer: "already",
      why: "We have already finished — «Мы уже закончили». Have + already + V3.",
    },
    {
      kind: "choice",
      stage: 1,
      tag: "have been to",
      q: "«Я дважды бывал в Италии». Как правильно?",
      note: "Опыт поездок: have been to + место. Been — третья форма be.",
      options: [
        { t: "I have been to Italy twice.", ok: true },
        { t: "I have gone to Italy twice." },
        { t: "I was to Italy twice." },
      ],
      why: "have been to — «бывал и вернулся». Have gone to значило бы «уехал и сейчас там».",
    },
    {
      kind: "choice",
      stage: 1,
      tag: "been или gone",
      q: "Сары нет в офисе — она уехала в банк и ещё не вернулась. Что скажешь коллеге?",
      note: "gone to — уехал и ещё там; been to — съездил и вернулся.",
      options: [
        { t: "She has gone to the bank.", ok: true },
        { t: "She has been to the bank." },
        { t: "She is been to the bank." },
      ],
      why: "She has gone to the bank — уехала и пока там. Been была бы, если бы уже вернулась.",
    },
    {
      kind: "fill",
      stage: 2,
      tag: "Вежливое «хочу»",
      qBefore: "I ",
      qAfter: " like to book a table for two, please.",
      hintRu: "Я хотел бы забронировать столик на двоих. (вежливое «хотел бы», одно слово)",
      note: "would like = вежливое want: I would like to… (сокращённо I'd like to…).",
      answer: "would",
      why: "I would like to book a table — «Я хотел бы забронировать столик». Так говорят в ресторанах всего мира.",
    },
    {
      kind: "choice",
      stage: 2,
      tag: "Вежливый вопрос",
      q: "Предложи гостю кофе — максимально вежливо:",
      note: "Would you like…? — «Не хотите ли…?» Вежливее, чем Do you want…?",
      options: [
        { t: "Would you like some coffee?", ok: true },
        { t: "You want coffee?" },
        { t: "Coffee?" },
      ],
      why: "Would you like some coffee? — форма, уместная и с гостем, и с клиентом, и с директором.",
    },
    {
      kind: "choice",
      stage: 3,
      tag: "Связки глаголов",
      q: "Выбери фразу без ошибки:",
      note: "decide → to + глагол; keep → глагол + -ing.",
      options: [
        { t: "We decided to stay and kept working.", ok: true },
        { t: "We decided staying and kept to work." },
        { t: "We decided stay and kept work." },
      ],
      why: "decided to stay (to после decide) + kept working (-ing после keep) — у каждого глагола своя связка.",
    },
    {
      kind: "fill",
      stage: 3,
      tag: "Письмо",
      qBefore: "Dear Mr Reed, I am ",
      qAfter: " about our meeting on Friday.",
      hintRu: "Уважаемый мистер Рид, пишу по поводу нашей встречи в пятницу. (писать — с окончанием -ing)",
      note: "Первая строка делового письма: I am writing about… — «пишу по поводу…».",
      answer: "writing",
      why: "I am writing about our meeting — классическое начало делового письма.",
    },
    {
      kind: "assemble",
      stage: 4,
      tag: "Финал",
      q: "Собери фразу-визитку уровня B1 — об опыте, который продолжается:",
      note: "Perfect + for: изучаю уже долго и продолжаю.",
      words: ["I", "have", "already", "learned", "a", "lot", "this", "year."],
      answer: "I have already learned a lot this year.",
      why: "I have already learned a lot this year — «В этом году я уже многому научился». И это чистая правда. Тренажёр пройден!",
    },
  ],
  words: [],
};

export default drills;
