import type { Chapter } from "@/lib/types";

const drills: Chapter = {
  slug: "drills-u4",
  title: "Тренажёр: условные предложения",
  subtitle: "Отработка юнита «Условные предложения»: первое (реальное) и второе (нереальное) условное.",
  section: "exercise",
  stages: [
    { icon: "☔", name: "Первое условное" },
    { icon: "🌙", name: "Второе условное" },
    { icon: "✅", name: "Готово" },
  ],
  steps: [
    {
      kind: "fill",
      stage: 0,
      tag: "Первое условное",
      qBefore: "If it ",
      qAfter: " tomorrow, we will stay at home.",
      hintRu: "Если завтра пойдёт дождь, мы останемся дома. (после if — настоящее время)",
      answer: "rains",
      why: "If it rains — после if используется настоящее время, а не will.",
    },
    {
      kind: "choice",
      stage: 0,
      tag: "Первое условное",
      q: "«Если понадобится помощь, я помогу». Как правильно?",
      note: "If + настоящее, will + глагол.",
      options: [
        { t: "If you need help, I will help you.", ok: true },
        { t: "If you will need help, I will help you." },
        { t: "If you need help, I help you." },
      ],
      why: "If you need help… will help — will нельзя ставить после if.",
    },
    {
      kind: "assemble",
      stage: 0,
      tag: "Первое условное",
      q: "Собери фразу: «Если людям понравится, мы сделаем его большим»:",
      note: "If people like it, we will make it big.",
      words: ["If", "people", "like", "it,", "we", "will", "make", "it", "big."],
      answer: "If people like it, we will make it big.",
      why: "If people like it… will make — реальное условие + результат через will.",
    },
    {
      kind: "fill",
      stage: 1,
      tag: "Второе условное",
      qBefore: "If I ",
      qAfter: " you, I would apply.",
      hintRu: "На твоём месте я бы подал заявку. (were — особая форма для всех лиц)",
      answer: "were",
      why: "If I were you — were используется со всеми лицами в фантазиях, даже с I.",
    },
    {
      kind: "choice",
      stage: 1,
      tag: "Второе условное",
      q: "«Будь у меня больше времени, я бы путешествовал». Выбери верный вариант:",
      note: "If + прошедшее, would + глагол — нереальная ситуация.",
      options: [
        { t: "If I had more time, I would travel.", ok: true },
        { t: "If I have more time, I will travel." },
        { t: "If I would have more time, I would travel." },
      ],
      why: "If I had… would travel — прошедшее в if-части, would в результате.",
    },
    {
      kind: "choice",
      stage: 1,
      tag: "Второе условное — совет",
      q: "Друг сомневается, менять ли работу. Как дать совет через второе условное?",
      note: "If I were you, I would… — классика совета.",
      options: [
        { t: "If I were you, I would talk to your manager first.", ok: true },
        { t: "If I am you, I will talk to your manager first." },
        { t: "If I were you, I talk to your manager first." },
      ],
      why: "If I were you, I would talk… — оба элемента (were и would) обязательны.",
    },
    {
      kind: "fill",
      stage: 1,
      tag: "Второе условное — вопрос",
      qBefore: "What ",
      qAfter: " you do in my place?",
      hintRu: "Что бы ты сделал на моём месте? (would в вопросе)",
      answer: "would",
      why: "What would you do…? — вопрос о нереальной ситуации строится через would.",
    },
    {
      kind: "assemble",
      stage: 2,
      tag: "Финал",
      q: "Собери обе идеи разом: «Если у нас будет время, мы поедем; но будь у меня выбор, я бы остался»:",
      note: "If we have time, we will go — реальное условие с if + настоящее + will.",
      words: ["If", "we", "have", "time,", "we", "will", "go."],
      answer: "If we have time, we will go.",
      why: "If we have time, we will go — реальное условие. Тренажёр пройден!",
    },
  ],
  words: [],
};

export default drills;
