import type { Chapter } from "@/lib/types";

const drills: Chapter = {
  slug: "drills",
  title: "Тренажёр: Present Perfect и условные",
  subtitle:
    "Отработка правил B1: have/has + V3, ever/never/for/since, выбор Perfect против Past, условные if-предложения и связки want to / enjoy doing.",
  section: "exercise",
  stages: [
    { icon: "🔗", name: "Perfect" },
    { icon: "⚖️", name: "Perfect vs Past" },
    { icon: "🔀", name: "Условные" },
    { icon: "🧩", name: "Связки" },
    { icon: "✅", name: "Готово" },
  ],
  steps: [
    {
      kind: "fill",
      stage: 0,
      tag: "have / has",
      qBefore: "She ",
      qAfter: " already finished the report.",
      hintRu: "Она уже закончила отчёт. (помощник Perfect для she)",
      note: "Present Perfect: have (I/you/we/they) или has (he/she/it) + третья форма.",
      answer: "has",
      why: "She has finished — с she помощник has.",
    },
    {
      kind: "choice",
      stage: 0,
      tag: "Третья форма",
      q: "«Я никогда не БЫЛ в Париже». Какая форма be?",
      note: "be → was/were → been. В Perfect нужна третья.",
      options: [
        { t: "I have never been to Paris.", ok: true },
        { t: "I have never was in Paris." },
        { t: "I have never be to Paris." },
      ],
      why: "have been — третья форма be. «Have been to» — бывал где-то.",
    },
    {
      kind: "fill",
      stage: 0,
      tag: "for / since",
      qBefore: "We have known each other ",
      qAfter: " ten years.",
      hintRu: "Мы знакомы уже десять лет. (предлог перед ОТРЕЗКОМ времени)",
      note: "for + отрезок (for ten years), since + точка (since 2015).",
      answer: "for",
      why: "for ten years — десять лет это отрезок времени.",
    },
    {
      kind: "fill",
      stage: 0,
      tag: "for / since",
      qBefore: "He has lived here ",
      qAfter: " 2020.",
      hintRu: "Он живёт здесь с 2020 года. (предлог перед ТОЧКОЙ отсчёта)",
      answer: "since",
      why: "since 2020 — год это точка отсчёта.",
    },
    {
      kind: "choice",
      stage: 1,
      tag: "Perfect или Past?",
      q: "Выбери грамматически верную фразу:",
      note: "Точное время (last week) → только Past Simple.",
      options: [
        { t: "I visited Rome last week.", ok: true },
        { t: "I have visited Rome last week." },
        { t: "I visit Rome last week." },
      ],
      why: "С last week — Past Simple: I visited. Perfect с точным временем не дружит.",
    },
    {
      kind: "choice",
      stage: 1,
      tag: "Perfect или Past?",
      q: "Результат важен прямо сейчас: ключи потеряны, войти не можешь. Что скажешь?",
      note: "Результат «на сейчас» без указания времени → Present Perfect.",
      options: [
        { t: "I have lost my keys!", ok: true },
        { t: "I lost my keys in 2020." },
        { t: "I lose my keys!" },
      ],
      why: "I have lost my keys! — потерял, и результат актуален: войти нельзя.",
    },
    {
      kind: "fill",
      stage: 2,
      tag: "1-е условное",
      qBefore: "If you practise every day, you ",
      qAfter: " speak English soon.",
      hintRu: "Если будешь заниматься каждый день, скоро заговоришь. (будущее в части результата)",
      note: "If + настоящее, will + глагол. Will живёт только во второй части!",
      answer: "will",
      why: "If you practise…, you will speak — классическое первое условное.",
    },
    {
      kind: "choice",
      stage: 2,
      tag: "2-е условное",
      q: "«На твоём месте я бы отдохнул». Как правильно?",
      note: "Совет-фантазия: If I were you, I would…",
      options: [
        { t: "If I were you, I would rest.", ok: true },
        { t: "If I am you, I will rest." },
        { t: "If I was be you, I rest." },
      ],
      why: "If I were you, I would rest — were + would, мир фантазий.",
    },
    {
      kind: "choice",
      stage: 3,
      tag: "Связки глаголов",
      q: "Выбери правильную пару:",
      note: "want → to + глагол; enjoy → глагол + -ing.",
      options: [
        { t: "I want to learn / I enjoy learning", ok: true },
        { t: "I want learning / I enjoy to learn" },
        { t: "I want learn / I enjoy learn" },
      ],
      why: "want to learn, но enjoy learning — у каждого глагола своя связка.",
    },
    {
      kind: "fill",
      stage: 3,
      tag: "Наречия",
      qBefore: "She speaks English very ",
      qAfter: ".",
      hintRu: "Она очень хорошо говорит по-английски. (наречие от good — особое слово!)",
      note: "good — прилагательное, а наречие «хорошо» — well.",
      answer: "well",
      why: "She speaks well — good превращается в well.",
    },
    {
      kind: "assemble",
      stage: 4,
      tag: "Финал",
      q: "Собери фразу уровня B1 — про свой опыт:",
      note: "Present Perfect + for: опыт, который продолжается.",
      words: ["I", "have", "studied", "English", "for", "two", "years."],
      answer: "I have studied English for two years.",
      why: "I have studied English for two years — и прогресс налицо. Тренажёр пройден!",
    },
  ],
  words: [],
};

export default drills;
