import type { Chapter } from "@/lib/types";

const drills: Chapter = {
  slug: "drills-u5",
  title: "Тренажёр: глагольные связки",
  subtitle: "Отработка юнита «Работа мечты»: want to do против enjoy doing.",
  section: "exercise",
  stages: [
    { icon: "➡️", name: "+ to" },
    { icon: "🔁", name: "+ -ing" },
    { icon: "✅", name: "Готово" },
  ],
  steps: [
    {
      kind: "fill",
      stage: 0,
      tag: "+ to",
      qBefore: "I want ",
      qAfter: " a new language this year.",
      hintRu: "Я хочу выучить новый язык в этом году. (want требует to)",
      answer: "to learn",
      why: "want to learn — после want идёт to + глагол.",
    },
    {
      kind: "choice",
      stage: 0,
      tag: "+ to",
      q: "«Мы решили делать это вместе». Как правильно?",
      note: "decide требует to.",
      options: [
        { t: "We decided to build it together.", ok: true },
        { t: "We decided building it together." },
        { t: "We decided build it together." },
      ],
      why: "decided to build — после decide всегда to + глагол.",
    },
    {
      kind: "fill",
      stage: 0,
      tag: "+ to",
      qBefore: "I hope ",
      qAfter: " you at the interview.",
      hintRu: "Надеюсь увидеть тебя на собеседовании. (hope требует to)",
      answer: "to see",
      why: "hope to see — hope тоже требует to + глагол.",
    },
    {
      kind: "fill",
      stage: 1,
      tag: "+ -ing",
      qBefore: "I enjoy ",
      qAfter: " people.",
      hintRu: "Мне нравится помогать людям. (enjoy требует -ing)",
      answer: "helping",
      why: "enjoy helping — после enjoy глагол с -ing, а не to.",
    },
    {
      kind: "choice",
      stage: 1,
      tag: "+ -ing",
      q: "«Она наконец закончила писать отчёт». Как правильно?",
      note: "finish требует -ing.",
      options: [
        { t: "She finally finished writing the report.", ok: true },
        { t: "She finally finished to write the report." },
        { t: "She finally finished write the report." },
      ],
      why: "finished writing — после finish всегда -ing.",
    },
    {
      kind: "choice",
      stage: 1,
      tag: "+ -ing",
      q: "«Перестань волноваться». Как сказать?",
      note: "stop требует -ing.",
      options: [
        { t: "Stop worrying.", ok: true },
        { t: "Stop to worry." },
        { t: "Stop worry." },
      ],
      why: "Stop worrying — после stop глагол с -ing.",
    },
    {
      kind: "choice",
      stage: 1,
      tag: "Смешанный выбор",
      q: "«Я продолжаю учиться каждый день». Какой глагол верный?",
      note: "keep требует -ing.",
      options: [
        { t: "I keep learning every day.", ok: true },
        { t: "I keep to learn every day." },
        { t: "I keep learn every day." },
      ],
      why: "keep learning — keep требует -ing, как enjoy и finish.",
    },
    {
      kind: "assemble",
      stage: 2,
      tag: "Финал",
      q: "Собери фразу с обеими связками: «Я планирую остаться и мне нравится решать сложные задачи»:",
      note: "I plan to stay + and I enjoy solving hard problems.",
      words: ["I", "plan", "to", "stay", "and", "I", "enjoy", "solving", "hard", "problems."],
      answer: "I plan to stay and I enjoy solving hard problems.",
      why: "plan to stay (+to) и enjoy solving (+-ing) — обе модели в одной фразе. Тренажёр пройден!",
    },
  ],
  words: [],
};

export default drills;
