import type { Chapter } from "@/lib/types";

const drills: Chapter = {
  slug: "drills-u2",
  title: "Тренажёр: мнения и наречия",
  subtitle: "Отработка юнита «Мнения и обсуждения»: выражение мнения, вежливое несогласие, наречия на -ly.",
  section: "exercise",
  stages: [
    { icon: "💭", name: "Мнение" },
    { icon: "🤝", name: "Несогласие" },
    { icon: "🏃", name: "Наречия" },
    { icon: "✅", name: "Готово" },
  ],
  steps: [
    {
      kind: "choice",
      stage: 0,
      tag: "Мнение",
      q: "Как вежливо начать высказывать своё мнение?",
      note: "In my opinion — «по моему мнению» звучит как позиция, не приговор.",
      options: [
        { t: "In my opinion, this plan is risky.", ok: true },
        { t: "This plan is risky, everybody knows it." },
        { t: "This plan is risky, full stop." },
      ],
      why: "In my opinion — мягко вводит личную точку зрения.",
    },
    {
      kind: "fill",
      stage: 0,
      tag: "Мнение",
      qBefore: "I ",
      qAfter: " that we should wait a bit longer.",
      hintRu: "Я думаю, что нам стоит подождать ещё немного. (стандартное слово «думаю»)",
      answer: "think",
      why: "I think that… — базовая формула для мнения.",
    },
    {
      kind: "choice",
      stage: 1,
      tag: "Вежливое несогласие",
      q: "Коллега предложил идею, тебе она не нравится. Как вежливо возразить?",
      note: "Сначала признание, потом возражение — формула вежливого спора.",
      options: [
        { t: "I see your point, but I don't agree.", ok: true },
        { t: "No, that's a bad idea." },
        { t: "I don't agree, you are wrong." },
      ],
      why: "I see your point, but I don't agree — сначала признание позиции собеседника, потом мягкое возражение.",
    },
    {
      kind: "assemble",
      stage: 1,
      tag: "Вежливое несогласие",
      q: "Собери вежливое согласие: «Это логично»:",
      note: "That makes sense — устойчивая фраза согласия.",
      words: ["That", "makes", "sense."],
      answer: "That makes sense.",
      why: "That makes sense — «Это логично», короткая и естественная реакция.",
    },
    {
      kind: "fill",
      stage: 2,
      tag: "Наречия",
      qBefore: "She speaks slowly and ",
      qAfter: ".",
      hintRu: "Она говорит медленно и чётко. (clear → наречие)",
      answer: "clearly",
      why: "clear → clearly: прилагательное + ly.",
    },
    {
      kind: "choice",
      stage: 2,
      tag: "Наречия-исключения",
      q: "«Она поёт хорошо». Как правильно?",
      note: "good — прилагательное, наречие «хорошо» — особая форма well.",
      options: [
        { t: "She sings well.", ok: true },
        { t: "She sings good." },
        { t: "She sings goodly." },
      ],
      why: "She sings well — good не превращается в goodly, наречие — well.",
    },
    {
      kind: "choice",
      stage: 2,
      tag: "Наречия-исключения",
      q: "«Он усердно работает и быстро учится». Выбери верный вариант:",
      note: "hard и fast — одинаковы и как прилагательное, и как наречие.",
      options: [
        { t: "He works hard and learns fast.", ok: true },
        { t: "He works hardly and learns fastly." },
        { t: "He works hard and learns fastly." },
      ],
      why: "hard и fast не меняются в наречия через -ly — это исключения.",
    },
    {
      kind: "assemble",
      stage: 3,
      tag: "Финал",
      q: "Собери фразу: «По моему мнению, он объясняет ясно, но я вежливо не согласен с планом»:",
      note: "In my opinion, he explains clearly, but I politely disagree.",
      words: ["In", "my", "opinion,", "he", "explains", "clearly,", "but", "I", "politely", "disagree."],
      answer: "In my opinion, he explains clearly, but I politely disagree.",
      why: "In my opinion… clearly… but I disagree — мнение, наречие и вежливое возражение в одной фразе. Тренажёр пройден!",
    },
  ],
  words: [],
};

export default drills;
