import type { Chapter } from "@/lib/types";

const chapter2: Chapter = {
  slug: "idioms",
  title: "Идиомы: говори как местный",
  subtitle:
    "Вечер в пабе, и Эмма объявляет урок «настоящего английского»: идиомы, которые не переводятся дословно — от «куска торта» до «дождя из кошек и собак».",
  goals: [
    "понимать идиомы в живой речи",
    "использовать идиомы уместно",
    "догадываться о смысле по контексту",
    "звучать естественно, а не по учебнику",
  ],
  stages: [
    { icon: "🍻", name: "Паб" },
    { icon: "🍰", name: "Проще простого" },
    { icon: "🌧️", name: "Погода" },
    { icon: "🎭", name: "Удача" },
    { icon: "🎯", name: "В точку" },
  ],
  steps: [
    {
      kind: "story",
      stage: 0,
      en: "Friday evening, the team pub. Emma bangs the table: «Alim, your grammar is perfect. But do you speak REAL English? Time for idioms — phrases that make no sense… until they do!»",
      ru: "Вечер пятницы, командный паб. Эмма стучит по столу: «Алим, твоя грамматика идеальна. Но говоришь ли ты на НАСТОЯЩЕМ английском? Время идиом — фраз, которые не имеют смысла… пока не обретут его!»",
    },
    {
      kind: "choice",
      stage: 1,
      tag: "Первая идиома",
      q: "Том говорит о твоей задаче: «It was a piece of cake!» Что он имел в виду?",
      note: "A piece of cake — дословно «кусок торта». Но идиомы не переводят дословно! Смысл: что-то очень лёгкое.",
      rule: "idioms",
      options: [
        { t: "Задача была проще простого", ok: true },
        { t: "За задачу дали торт" },
        { t: "Задача была сладкой, но вредной" },
      ],
      why: "It was a piece of cake! — «Это было проще простого!» Съесть кусок торта легко — отсюда и смысл.",
      phrase: { en: "It's a piece of cake!", ru: "Проще простого!" },
    },
    {
      kind: "listen",
      stage: 2,
      tag: "Аудирование",
      q: "Эмма смотрит в окно и говорит про погоду. Что там происходит?",
      audio: "Look! It's raining cats and dogs!",
      note: "Raining cats and dogs — дословно «дождь из кошек и собак». Британская классика о погоде. Догадайся по смыслу!",
      options: [
        { t: "Льёт как из ведра", ok: true },
        { t: "На улице гуляют кошки и собаки" },
        { t: "Дождь закончился" },
      ],
      why: "It's raining cats and dogs! — «Льёт как из ведра!» Никто не знает точно, откуда пошла эта фраза, но говорят её все.",
      phrase: { en: "It's raining cats and dogs!", ru: "Льёт как из ведра!" },
    },
    {
      kind: "choice",
      stage: 2,
      tag: "Редкость",
      q: "Прия говорит: «Lucas cooks once in a blue moon». Как часто готовит Лукас?",
      note: "Once in a blue moon — дословно «раз в голубую луну». «Голубая луна» — редчайшее астрономическое явление…",
      options: [
        { t: "Очень редко", ok: true },
        { t: "Каждое полнолуние" },
        { t: "Только по ночам" },
      ],
      why: "Once in a blue moon — «очень редко, раз в сто лет». Голубая луна бывает раз в несколько лет — отсюда смысл.",
      phrase: { en: "once in a blue moon", ru: "очень редко" },
    },
    {
      kind: "story",
      stage: 3,
      en: "Emma leans in: «Now the most important one. Next week you have the big conference talk. So remember: we never say 'good luck' to performers — we say something… stranger».",
      ru: "Эмма наклоняется ближе: «А теперь самая важная. На следующей неделе у тебя большое выступление на конференции. Запомни: выступающим никогда не желают 'good luck' — им говорят кое-что… постраннее».",
    },
    {
      kind: "assemble",
      stage: 3,
      tag: "Собери идиому",
      q: "Пожелай удачи перед выступлением — по-актёрски:",
      note: "Break a leg! — дословно «сломай ногу»! Так актёры желают удачи перед сценой (как наше «ни пуха ни пера»). Отвечать «спасибо» можно 🙂",
      words: ["Break", "a", "leg", "at", "the", "conference!"],
      answer: "Break a leg at the conference!",
      why: "Break a leg! — «Ни пуха ни пера!» Театральная примета: пожелать удачи прямо — плохой знак, поэтому желают… перелом 🙂",
      phrase: { en: "Break a leg!", ru: "Ни пуха ни пера!" },
    },
    {
      kind: "fill",
      stage: 3,
      tag: "Впиши слово",
      qBefore: "It's late. Let's hit the ",
      qAfter: "!",
      hintRu: "Уже поздно. Пора в путь! (идиома: «ударить по дороге»)",
      note: "Hit the road — дословно «ударить дорогу», по смыслу — «отправиться в путь, выдвигаться». Road — дорога.",
      answer: "road",
      why: "Let's hit the road! — «Пора выдвигаться!» Есть даже знаменитая песня: Hit the road, Jack!",
      phrase: { en: "Let's hit the road!", ru: "Пора в путь!" },
    },
    {
      kind: "listen",
      stage: 4,
      tag: "Аудирование",
      q: "Ты сказал, что успех приложения — заслуга всей команды. Реакция Эммы?",
      audio: "You hit the nail on the head!",
      note: "Hit the nail on the head — дословно «ударить гвоздь по шляпке». Что делает мастер, когда попадает точно?",
      options: [
        { t: "«Ты попал в самую точку!»", ok: true },
        { t: "«Ты всё испортил!»" },
        { t: "«Ты работаешь как молоток!»" },
      ],
      why: "You hit the nail on the head! — «В самую точку!» Точный удар по гвоздю = точная мысль.",
      phrase: { en: "You hit the nail on the head!", ru: "В самую точку!" },
    },
    {
      kind: "choice",
      stage: 4,
      tag: "Финальный тест",
      q: "Эмма проверяет: «The conference talk will be a piece of cake if you practise». Переведи!",
      note: "Две вещи в одной фразе: идиома из начала вечера + условие if из сезона B1. Собери смысл целиком.",
      options: [
        { t: "Выступление будет проще простого, если ты потренируешься", ok: true },
        { t: "На конференции будут угощать тортом" },
        { t: "Выступление отменят, если пойдёт дождь" },
      ],
      why: "«Выступление будет проще простого, если потренируешься». Идиомы + грамматика = живой английский. Урок Эммы усвоен!",
    },
    {
      kind: "story",
      stage: 4,
      en: "You walk home through the wet streets and smile: today English stopped being a subject. It became an inside joke between you and seven million Londoners.",
      ru: "Ты идёшь домой по мокрым улицам и улыбаешься: сегодня английский перестал быть предметом. Он стал общей шуткой между тобой и семью миллионами лондонцев.",
    },
  ],
  words: [
    { en: "a piece of cake", ru: "проще простого" },
    { en: "raining cats and dogs", ru: "льёт как из ведра" },
    { en: "once in a blue moon", ru: "очень редко" },
    { en: "break a leg", ru: "ни пуха ни пера" },
    { en: "hit the road", ru: "отправиться в путь" },
    { en: "hit the nail on the head", ru: "попасть в точку" },
  ],
};

export default chapter2;
