import type { Chapter } from "@/lib/types";

const chapter3: Chapter = {
  slug: "the-presentation",
  title: "Презентация",
  subtitle:
    "EdTech-конференция в Лондоне, полный зал — и вы с Данияром на сцене рассказываете историю своего приложения. Учимся выступать: структура, фразы-мостики и ответы на вопросы.",
  goals: [
    "строить выступление: сначала — затем — в конце",
    "начинать презентацию и вести зал за собой",
    "отвечать на вопросы и брать паузу профессионально",
    "красиво завершать выступление",
  ],
  stages: [
    { icon: "🎤", name: "Сцена" },
    { icon: "📖", name: "История" },
    { icon: "📊", name: "Цифры" },
    { icon: "🙋", name: "Вопросы" },
    { icon: "👏", name: "Финал" },
  ],
  steps: [
    {
      kind: "story",
      stage: 0,
      en: "EdTech London. Three hundred people in the hall. Your slides are ready, Daniyar is nervous, and Emma's «Break a leg!» still rings in your ears. The host announces your names…",
      ru: "Конференция EdTech London. Триста человек в зале. Слайды готовы, Данияр нервничает, а «Break a leg!» от Эммы всё ещё звенит в ушах. Ведущий объявляет ваши имена…",
    },
    {
      kind: "choice",
      stage: 0,
      tag: "Структура",
      q: "Эмма учила: у хорошего выступления три слова-скелета. Какие?",
      note: "Скелет любой презентации: First… (сначала) → Then… (затем) → Finally… (в конце). Эти слова ведут слушателя за руку.",
      options: [
        { t: "First… Then… Finally…", ok: true },
        { t: "Hello… Goodbye… Thanks…" },
        { t: "Yes… No… Maybe…" },
      ],
      why: "First → Then → Finally — карта выступления. Слушатель всегда знает, где вы находитесь и сколько осталось.",
      phrase: { en: "First… Then… Finally…", ru: "Сначала… Затем… В конце… (скелет выступления)" },
    },
    {
      kind: "assemble",
      stage: 1,
      tag: "Начни выступление",
      q: "Первая фраза со сцены — пригласи зал в свою историю:",
      note: "Let me + действие — «позвольте мне…». Мягкое и уверенное начало: Let me tell you… — «Позвольте рассказать вам…».",
      words: ["First,", "let", "me", "tell", "you", "our", "story."],
      answer: "First, let me tell you our story.",
      why: "First, let me tell you our story — «Сначала позвольте рассказать нашу историю». Истории работают лучше цифр — начинай с неё.",
      phrase: { en: "Let me tell you our story.", ru: "Позвольте рассказать нашу историю." },
    },
    {
      kind: "story",
      stage: 1,
      en: "You tell them everything: the ticket to London, «Where is my suitcase?», the rainy evening when two friends drew an app on a napkin. The hall is silent — they are listening.",
      ru: "Ты рассказываешь им всё: билет в Лондон, «Where is my suitcase?», дождливый вечер, когда два друга нарисовали приложение на салфетке. Зал молчит — они слушают.",
    },
    {
      kind: "fill",
      stage: 2,
      tag: "Цифры",
      qBefore: "Then — the numbers. One hundred thousand people ",
      qAfter: " joined our app!",
      hintRu: "Затем — цифры. Сто тысяч человек присоединились к нашему приложению! (результат, важный сейчас)",
      note: "Достижение «на сегодня» — Present Perfect: люди (they) + have + joined. Hundred thousand — сто тысяч.",
      answer: "have",
      why: "One hundred thousand people have joined our app! — «К приложению присоединились сто тысяч человек!» Have joined — результат, которым вы живёте сейчас.",
    },
    {
      kind: "listen",
      stage: 3,
      tag: "Аудирование",
      q: "Время вопросов. Мужчина в третьем ряду поднимает руку. О чём он спрашивает?",
      audio: "How do you make money if the app is free?",
      note: "Make money — зарабатывать. If — если. Классический вопрос любому бесплатному проекту!",
      options: [
        { t: "Как вы зарабатываете, если приложение бесплатное", ok: true },
        { t: "Сколько стоит подписка на приложение" },
        { t: "Когда приложение станет платным" },
      ],
      why: "How do you make money if the app is free? — «Как вы зарабатываете, если приложение бесплатное?» Вопрос-ловушка — но у тебя есть ответ.",
    },
    {
      kind: "choice",
      stage: 3,
      tag: "Выиграй секунды",
      q: "Тебе нужно две секунды собраться с мыслями. Какая фраза даст паузу и прозвучит профессионально?",
      note: "Фраза-мостик: That's a great question — «Отличный вопрос». Даёт время подумать и делает комплимент спросившему. Все спикеры мира пользуются ею!",
      options: [
        { t: "That's a great question.", ok: true },
        { t: "Next question, please." },
        { t: "I don't know. Daniyar?" },
      ],
      why: "That's a great question — «Отличный вопрос». Пауза + уважение к залу. Теперь спокойно отвечай.",
      phrase: { en: "That's a great question.", ru: "Отличный вопрос. (фраза-пауза)" },
    },
    {
      kind: "assemble",
      stage: 3,
      tag: "Твой ответ",
      q: "Ответь залу — вся миссия проекта в трёх словах:",
      note: "Should из главы про врача — «должно, следует». Knowledge — знания. Free — бесплатный. Сложи вашу миссию!",
      words: ["Knowledge", "should", "be", "free."],
      answer: "Knowledge should be free.",
      why: "Knowledge should be free — «Знания должны быть бесплатными». Зал начинает аплодировать. Иногда три слова сильнее трёхсот.",
      phrase: { en: "Knowledge should be free.", ru: "Знания должны быть бесплатными." },
    },
    {
      kind: "fill",
      stage: 4,
      tag: "Заверши выступление",
      qBefore: "Finally, thank you ",
      qAfter: " listening!",
      hintRu: "И в конце — спасибо, что выслушали! (предлог перед действием-с-ing)",
      note: "Thank you for + действие-ing: thank you for listening — «спасибо, что слушали», thank you for coming — «спасибо, что пришли».",
      answer: "for",
      why: "Thank you for listening! — «Спасибо, что выслушали!» Классическая последняя фраза любой презентации в мире.",
      phrase: { en: "Thank you for listening!", ru: "Спасибо, что выслушали!" },
    },
    {
      kind: "listen",
      stage: 4,
      tag: "Аудирование",
      q: "После выступления к вам подходит организатор конференции. Что она говорит?",
      audio: "That was the best talk of the day. Well done!",
      note: "Talk — здесь «выступление, доклад». The best — ты знаешь эту лесенку! Well done — молодцы.",
      options: [
        { t: "Это было лучшее выступление дня", ok: true },
        { t: "Выступление было слишком длинным" },
        { t: "Следующее выступление через час" },
      ],
      why: "That was the best talk of the day. Well done! — «Это был лучший доклад дня. Молодцы!» The best — та самая вершина good → better → the best.",
      phrase: { en: "Well done!", ru: "Молодец! / Отличная работа!" },
    },
    {
      kind: "story",
      stage: 4,
      en: "Backstage, Daniyar can't stop smiling: «Three hundred people, man. And you told OUR story in YOUR English». Somewhere in the hall, a man in an expensive suit writes down your names…",
      ru: "За кулисами Данияр не может перестать улыбаться: «Триста человек, дружище. И ты рассказал НАШУ историю на СВОЁМ английском». А где-то в зале мужчина в дорогом костюме записывает ваши имена…",
    },
  ],
  words: [
    { en: "first / then / finally", ru: "сначала / затем / в конце" },
    { en: "let me tell you…", ru: "позвольте рассказать вам…" },
    { en: "make money", ru: "зарабатывать" },
    { en: "that's a great question", ru: "отличный вопрос (фраза-пауза)" },
    { en: "thank you for listening", ru: "спасибо, что выслушали" },
    { en: "well done", ru: "молодец, отличная работа" },
  ],
};

export default chapter3;
