import type { Chapter } from "@/lib/types";

const chapter1: Chapter = {
  slug: "all-tenses-one-day",
  title: "Все времена за один день",
  subtitle:
    "Один рабочий день тимлида Алима — и все главные времена английского в живой речи: привычки, «прямо сейчас», прошлое, опыт и планы.",
  goals: [
    "выбирать время по сигнальным словам",
    "различать Past Simple и Present Perfect",
    "говорить о процессе прямо сейчас",
    "рассказывать о планах команды",
  ],
  stages: [
    { icon: "🌅", name: "Утро" },
    { icon: "💻", name: "Прямо сейчас" },
    { icon: "🐞", name: "Вчерашний баг" },
    { icon: "📈", name: "Достижения" },
    { icon: "🌆", name: "Планы" },
  ],
  steps: [
    {
      kind: "story",
      stage: 0,
      en: "You are a team lead now, and your English works on autopilot. But today Daniyar has a challenge for you: «One day — all the tenses. Let's see how you use them without thinking!»",
      ru: "Ты теперь тимлид, и твой английский работает на автопилоте. Но Данияр придумал испытание: «Один день — все времена. Посмотрим, как ты используешь их не задумываясь!»",
    },
    {
      kind: "choice",
      stage: 0,
      tag: "Привычки",
      q: "Какая фраза говорит о ПРИВЫЧКЕ — о том, что ты делаешь каждый день?",
      note: "Привычки и факты — Present Simple (глагол без изменений): I drink tea every day. Сигнальные слова: every day, always, usually.",
      options: [
        { t: "I check my emails every morning.", ok: true },
        { t: "I am checking my emails now." },
        { t: "I checked my emails yesterday." },
      ],
      why: "I check my emails every morning — «Я проверяю почту каждое утро». Every morning выдаёт привычку → Present Simple.",
    },
    {
      kind: "fill",
      stage: 1,
      tag: "Прямо сейчас",
      qBefore: "Sorry, I can't talk — I ",
      qAfter: " working on a report right now.",
      hintRu: "Извини, не могу говорить — я работаю над отчётом прямо сейчас. (связка для I + процесс)",
      note: "«Прямо сейчас» — Present Continuous: am/is/are + глагол-ing. Right now — сигнал этого времени. Здесь I, значит связка…",
      answer: "am",
      why: "I am working right now — «Я работаю прямо сейчас». Формула процесса: am/is/are + -ing.",
    },
    {
      kind: "listen",
      stage: 1,
      tag: "Аудирование",
      q: "Прия пробегает мимо. Что происходит прямо сейчас?",
      audio: "Emma is talking to a big client at the moment.",
      note: "At the moment — «в данный момент» (ещё один сигнал Continuous). Лови, КТО и ЧТО делает.",
      options: [
        { t: "Эмма сейчас говорит с крупным клиентом", ok: true },
        { t: "Эмма говорила с клиентом вчера" },
        { t: "Эмма каждый день говорит с клиентами" },
      ],
      why: "Emma is talking to a big client at the moment — «Эмма сейчас разговаривает с крупным клиентом». Is + talking = процесс идёт.",
    },
    {
      kind: "fill",
      stage: 2,
      tag: "Прошлое",
      qBefore: "Yesterday I ",
      qAfter: " a serious bug in the app.",
      hintRu: "Вчера я нашёл серьёзный баг в приложении. (find — но в прошлом!)",
      note: "Yesterday — сигнал Past Simple. Find — неправильный глагол: find → found (ты слышал его в «I have already found a flat»).",
      answer: "found",
      why: "Yesterday I found a serious bug — «Вчера я нашёл серьёзный баг». Find → found — в копилку неправильных глаголов, к go → went.",
    },
    {
      kind: "assemble",
      stage: 2,
      tag: "Опыт-результат",
      q: "Успокой Данияра — баг уже починен:",
      note: "Результат, важный сейчас — Present Perfect: have + already + починил. Fix — чинить (ты просил Can you fix it? ещё в отеле!).",
      words: ["I", "have", "already", "fixed", "it."],
      answer: "I have already fixed it.",
      why: "I have already fixed it — «Я его уже починил». Сравни: I fixed it yesterday (просто факт из прошлого) и I have fixed it (результат: сейчас всё работает!).",
      phrase: { en: "I have already fixed it.", ru: "Я это уже починил." },
    },
    {
      kind: "choice",
      stage: 3,
      tag: "Почувствуй разницу",
      q: "В чём разница: «I fixed it yesterday» и «I have fixed it»?",
      note: "Past Simple (fixed) — факт с точным временем в прошлом. Present Perfect (have fixed) — результат без времени, важный сейчас. С yesterday Present Perfect не дружит!",
      rule: "tense-map",
      options: [
        { t: "Первое — факт со временем «вчера», второе — результат, важный сейчас", ok: true },
        { t: "Никакой разницы, это синонимы" },
        { t: "Первое — о будущем, второе — о прошлом" },
      ],
      why: "Точное время (yesterday, last week) → Past Simple. Результат «на сейчас» без времени → Present Perfect. Это главный водораздел двух времён.",
    },
    {
      kind: "listen",
      stage: 4,
      tag: "Аудирование",
      q: "Вечерняя планёрка. Какие планы объявляет Сара?",
      audio: "We are going to release the new version on Friday.",
      note: "Release — выпустить (версию). Going to — план заранее. Лови день недели!",
      options: [
        { t: "В пятницу выйдет новая версия", ok: true },
        { t: "В пятницу будет вечеринка" },
        { t: "В понедельник начнут новый проект" },
      ],
      why: "We are going to release the new version on Friday — «Мы выпускаем новую версию в пятницу». План команды → going to.",
    },
    {
      kind: "fill",
      stage: 4,
      tag: "Обещание",
      qBefore: "Don't worry, I ",
      qAfter: " test everything before Friday!",
      hintRu: "Не волнуйся, я всё протестирую до пятницы! (решение-обещание в момент разговора)",
      note: "Решил прямо сейчас и обещаешь → will. План заранее → going to. Это правило из сезона A2 — оно навсегда.",
      answer: "will",
      why: "I will test everything before Friday! — «Я всё протестирую до пятницы!» Will — твоё слово, данное в моменте.",
    },
    {
      kind: "choice",
      stage: 4,
      tag: "Финальный экзамен",
      q: "Данияр подводит итог дня. Собери карту времён — какой ряд верный?",
      note: "Проверь себя по сигналам: every day / right now / yesterday / already / on Friday.",
      options: [
        { t: "every day → check; right now → am checking; yesterday → checked; already → have checked", ok: true },
        { t: "every day → am checking; yesterday → have checked; already → checked" },
        { t: "right now → checked; yesterday → will check; already → check" },
      ],
      why: "Привычка → Present Simple, процесс → Continuous, вчера → Past, результат → Perfect. Экзамен Данияра сдан!",
    },
    {
      kind: "story",
      stage: 4,
      en: "Daniyar closes his notebook: «You didn't even notice — you used five tenses today. Naturally, like breathing. THIS is level B2».",
      ru: "Данияр закрывает блокнот: «Ты даже не заметил — сегодня ты использовал пять времён. Естественно, как дыхание. ВОТ что такое уровень B2».",
    },
  ],
  words: [
    { en: "every day / usually", ru: "каждый день / обычно (сигнал Present Simple)" },
    { en: "right now / at the moment", ru: "прямо сейчас (сигнал Continuous)" },
    { en: "yesterday / last week", ru: "вчера / на прошлой неделе (сигнал Past)" },
    { en: "already / ever / never", ru: "уже / когда-либо / никогда (сигнал Perfect)" },
    { en: "found", ru: "нашёл (find → found)" },
    { en: "release", ru: "выпустить (версию, продукт)" },
  ],
};

export default chapter1;
