import type { Chapter } from "@/lib/types";

const chapter5: Chapter = {
  slug: "british-humour",
  title: "Британский юмор",
  subtitle:
    "Финальный уровень языка — понимать, когда британец шутит. Преуменьшения, ирония о погоде, вечное «sorry» и почему «not bad» — это высшая похвала.",
  goals: [
    "расшифровывать британские преуменьшения",
    "распознавать иронию в разговоре",
    "поддерживать светскую беседу",
    "вежливо переспрашивать, если не расслышал",
  ],
  stages: [
    { icon: "🎩", name: "Урок Эммы" },
    { icon: "😏", name: "Преуменьшение" },
    { icon: "☔", name: "Погода" },
    { icon: "🙇", name: "Sorry" },
    { icon: "🏆", name: "Экзамен" },
  ],
  steps: [
    {
      kind: "story",
      stage: 0,
      en: "Emma declares your final lesson: «Grammar — done. Idioms — done. Now the hardest part: understanding when a British person is joking. Spoiler: almost always».",
      ru: "Эмма объявляет твой финальный урок: «Грамматика — есть. Идиомы — есть. Теперь самое сложное: понимать, когда британец шутит. Спойлер: почти всегда».",
    },
    {
      kind: "choice",
      stage: 1,
      tag: "Преуменьшение",
      q: "Мистер Рид посмотрел твой годовой отчёт и сказал: «Not bad!» Что он на самом деле имел в виду?",
      note: "Understatement — великое британское преуменьшение. Чем сдержаннее слова, тем сильнее чувство. Not bad (дословно «неплохо») в устах британца — почти восторг!",
      rule: "understatement",
      options: [
        { t: "«Отличная работа!» — это высокая похвала", ok: true },
        { t: "«Так себе» — он разочарован" },
        { t: "«Плохо» — он злится" },
      ],
      why: "Not bad! от британца ≈ «блестяще!». Шкала такая: not bad — отлично, quite good — прекрасно, interesting — сомнительно 🙂",
      phrase: { en: "Not bad!", ru: "Неплохо! (у британцев — высокая похвала)" },
    },
    {
      kind: "listen",
      stage: 1,
      tag: "Аудирование",
      q: "Том опоздал на час и говорит о причине. Как понять его слова?",
      audio: "Sorry, the traffic was a bit of a nightmare.",
      note: "A bit of a — «немножко» (то самое преуменьшение!), nightmare — кошмар. «Немножко кошмар» — это как?",
      options: [
        { t: "Пробки были ужасные (a bit — преуменьшение)", ok: true },
        { t: "Пробок почти не было" },
        { t: "Ему приснился кошмар" },
      ],
      why: "A bit of a nightmare — «слегка кошмарно» = «полная катастрофа». Британец добавляет a bit, когда всё совсем плохо.",
      phrase: { en: "a bit of a nightmare", ru: "«слегка кошмарно» = очень плохо" },
    },
    {
      kind: "choice",
      stage: 2,
      tag: "Ирония о погоде",
      q: "Ливень стеной. Эмма выглядывает на улицу: «Lovely weather, isn't it?» Что происходит?",
      note: "Lovely — прекрасный. Isn't it? — «хвостик»-вопрос («не так ли?»). Британская ирония: хвалить погоду именно тогда, когда она ужасна.",
      rule: "tag-questions",
      options: [
        { t: "Она иронизирует: погода отвратительная", ok: true },
        { t: "Ей правда нравится дождь" },
        { t: "Она прощается" },
      ],
      why: "Lovely weather, isn't it? под ливнем — чистая ирония. Правильный ответ — подыграть: Absolutely wonderful! («Совершенно прекрасная!»)",
      phrase: { en: "Lovely weather, isn't it?", ru: "Прекрасная погода, не так ли? (ирония)" },
    },
    {
      kind: "assemble",
      stage: 2,
      tag: "Подыграй!",
      q: "Ответь Эмме в том же духе — «отличная погода… для уток»:",
      note: "Nice weather for ducks — классическая шутка о дожде: уткам-то дождь нравится! Duck — утка.",
      words: ["Nice", "weather", "for", "ducks!"],
      answer: "Nice weather for ducks!",
      why: "Nice weather for ducks! — «Отличная погода для уток!» Эмма смеётся: ты пошутил по-британски. Это выше уровня B2!",
      phrase: { en: "Nice weather for ducks!", ru: "Отличная погода для уток! (шутка о дожде)" },
    },
    {
      kind: "story",
      stage: 3,
      en: "Emma's next topic: «The magic word — sorry. We say it when YOU step on OUR foot. We say it to chairs we bump into. It's not an apology. It's a way of life».",
      ru: "Следующая тема Эммы: «Волшебное слово — sorry. Мы говорим его, когда ТЫ наступаешь НАМ на ногу. Мы извиняемся перед стульями, на которые наткнулись. Это не извинение. Это образ жизни».",
    },
    {
      kind: "choice",
      stage: 3,
      tag: "Культурный код",
      q: "В метро ТЫ наступил британцу на ногу. Что, скорее всего, скажет ОН?",
      note: "Британский рефлекс: sorry говорят обе стороны любого столкновения — и виноватый, и пострадавший. Это смазка вежливости, а не признание вины.",
      options: [
        { t: "«Sorry!» — извинится сам", ok: true },
        { t: "«Watch out!» — возмутится" },
        { t: "Промолчит и отвернётся" },
      ],
      why: "Он скажет Sorry! первым — за то, что его нога оказалась под твоей 🙂 Британское sorry — рефлекс вежливости.",
    },
    {
      kind: "fill",
      stage: 3,
      tag: "Впиши слово",
      qBefore: "Sorry, could you ",
      qAfter: " that, please? The music is too loud.",
      hintRu: "Извините, не могли бы вы повторить? Музыка слишком громкая. (repeat — повторить)",
      note: "Не расслышал — не паникуй, а вежливо переспроси: Sorry, could you repeat that, please? Работает везде и всегда.",
      answer: "repeat",
      why: "Sorry, could you repeat that, please? — «Извините, не могли бы вы повторить?» Фраза-спасатель для любого разговора.",
      phrase: { en: "Could you repeat that, please?", ru: "Не могли бы вы повторить?" },
    },
    {
      kind: "listen",
      stage: 4,
      tag: "Аудирование",
      q: "Выпускной экзамен Эммы! Вы у двери паба, она пропускает тебя вперёд. Что она говорит?",
      audio: "After you!",
      note: "Дословно «после вас». Два слова — целый ритуал британской вежливости у любой двери.",
      options: [
        { t: "«Только после вас» — пропускает вперёд", ok: true },
        { t: "«Догоняй» — убегает вперёд" },
        { t: "«Закрой дверь» — просит о помощи" },
      ],
      why: "After you! — «Только после вас!» Ответить можно так же вежливо: Thank you! — и пройти. Или устроить вежливую дуэль: No, after YOU! 🙂",
      phrase: { en: "After you!", ru: "Только после вас!" },
    },
    {
      kind: "choice",
      stage: 4,
      tag: "Диплом Эммы",
      q: "Финальный вопрос. Британец говорит о твоём приложении: «It's quite good, actually». Твоя реакция?",
      note: "Собери всё: quite good — преуменьшение, actually («вообще-то») усиливает искренность. Расшифруй настоящий смысл!",
      options: [
        { t: "Радоваться: это искренняя высокая похвала", ok: true },
        { t: "Расстроиться: ему не понравилось" },
        { t: "Уточнить, что именно плохо" },
      ],
      why: "It's quite good, actually = «Это правда здорово». Actually выдаёт искреннее удивление и одобрение. Ты сдал экзамен по британскому юмору!",
    },
    {
      kind: "story",
      stage: 4,
      en: "Emma shakes your hand with fake seriousness: «Congratulations. You now understand the British. Even we don't always manage that». It's the funniest compliment you have ever received.",
      ru: "Эмма с наигранной серьёзностью жмёт тебе руку: «Поздравляю. Теперь ты понимаешь британцев. Даже у нас самих это не всегда получается». Это самый смешной комплимент в твоей жизни.",
    },
  ],
  words: [
    { en: "not bad (брит.)", ru: "отлично! (преуменьшение)" },
    { en: "a bit of a nightmare", ru: "«слегка кошмар» = катастрофа" },
    { en: "lovely weather, isn't it?", ru: "ирония о плохой погоде" },
    { en: "sorry", ru: "извините (британский рефлекс вежливости)" },
    { en: "could you repeat that?", ru: "не могли бы вы повторить?" },
    { en: "after you!", ru: "только после вас!" },
  ],
};

export default chapter5;
