import type { Chapter } from "@/lib/types";

const chapter6: Chapter = {
  slug: "full-circle",
  title: "Полный круг",
  subtitle:
    "Финал всей истории. Алим летит домой — открывать бесплатный клуб английского в Алматы. Там, где всё началось со слова «Hello», начнётся чья-то новая история.",
  goals: [
    "рассказывать о своём жизненном опыте",
    "понимать объявления и речь в обычном темпе",
    "говорить о переменах в жизни",
    "передавать свои знания другим",
  ],
  stages: [
    { icon: "🛬", name: "Домой" },
    { icon: "🏙️", name: "Алматы" },
    { icon: "🏫", name: "Клуб" },
    { icon: "👧", name: "Первый урок" },
    { icon: "🌟", name: "The End" },
  ],
  steps: [
    {
      kind: "story",
      stage: 0,
      en: "Autumn. The app has grown, the team works like a Swiss watch — and you have a dream that won't let you sleep: a free English club in Almaty. For kids like you once were. Daniyar's answer took one second: «I'm in».",
      ru: "Осень. Приложение выросло, команда работает как швейцарские часы — а тебе не даёт спать одна мечта: бесплатный клуб английского в Алматы. Для таких ребят, каким был ты. Ответ Данияра занял одну секунду: «Я в деле».",
    },
    {
      kind: "listen",
      stage: 0,
      tag: "Аудирование",
      q: "Самолёт снижается. Что объявляет пилот?",
      audio: "Welcome to Almaty. The local time is six o'clock.",
      note: "Local time — местное время. Ты ловишь такие объявления с самой первой главы — теперь это просто фон.",
      options: [
        { t: "Добро пожаловать в Алматы, местное время — шесть", ok: true },
        { t: "Рейс задерживается на шесть часов" },
        { t: "Посадка в Лондоне через шесть минут" },
      ],
      why: "Welcome to Almaty. The local time is six o'clock — «Добро пожаловать в Алматы. Местное время — шесть часов». Когда-то ты не понял бы ни слова. Сегодня — каждое.",
    },
    {
      kind: "fill",
      stage: 1,
      tag: "Впиши слово",
      qBefore: "I ",
      qAfter: " been to London many times, but home is home.",
      hintRu: "Я много раз бывал в Лондоне, но дом есть дом. (опыт за всю жизнь + I)",
      note: "Опыт «за жизнь» — Present Perfect: I + have + been. Been — «бывал» (особая форма be для перфекта). Many times — много раз.",
      answer: "have",
      why: "I have been to London many times, but home is home — «Я много раз бывал в Лондоне, но дом есть дом». Have been to — «бывал где-то» — жемчужина Present Perfect.",
      phrase: { en: "I have been to London many times.", ru: "Я много раз бывал в Лондоне." },
    },
    {
      kind: "story",
      stage: 1,
      en: "Almaty. The mountains are golden, the air smells like childhood. Aidana meets you at the airport — of course she does. She has already found a room for the club: bright, warm, with a whiteboard.",
      ru: "Алматы. Горы золотые, воздух пахнет детством. В аэропорту тебя встречает Айдана — а как же иначе. Она уже нашла помещение для клуба: светлое, тёплое, с маркерной доской.",
    },
    {
      kind: "assemble",
      stage: 2,
      tag: "Собери фразу",
      q: "Вы стоите посреди пустого класса. Скажи Айдане, с чего всё началось:",
      note: "It all started with… — «всё началось с…». Одно слово, один урок, одна поездка — большие истории начинаются с малого.",
      words: ["It", "all", "started", "with", "one", "word."],
      answer: "It all started with one word.",
      why: "It all started with one word — «Всё началось с одного слова». И ты помнишь, с какого.",
      phrase: { en: "It all started with one word.", ru: "Всё началось с одного слова." },
    },
    {
      kind: "choice",
      stage: 2,
      tag: "Пойми фразу",
      q: "Айдана улыбается: «The student has become the teacher». Что она сказала?",
      note: "Become — становиться (become → has become). Has — потому что the student — он/она/оно. Фраза-церемония: так говорят, когда круг замкнулся.",
      options: [
        { t: "«Ученик стал учителем»", ok: true },
        { t: "«Ученику нужен учитель»" },
        { t: "«Учитель стал учеником»" },
      ],
      why: "The student has become the teacher — «Ученик стал учителем». Present Perfect, потому что это случилось — и это правда прямо сейчас.",
      phrase: { en: "The student has become the teacher.", ru: "Ученик стал учителем." },
    },
    {
      kind: "story",
      stage: 3,
      en: "Saturday, 10:00. The first lesson of the free English club. Twelve kids at the desks. One girl in the front row raises her hand before you even start…",
      ru: "Суббота, 10:00. Первый урок бесплатного клуба английского. За партами двенадцать детей. Девочка с первого ряда тянет руку ещё до начала…",
    },
    {
      kind: "listen",
      stage: 3,
      tag: "Аудирование",
      q: "Девочка набирается смелости и говорит свою первую фразу. Какую?",
      audio: "Hello! My name is Amina!",
      note: "Ты знаешь эту фразу. Это была ТВОЯ первая фраза — в самом первом уроке, целую жизнь назад.",
      options: [
        { t: "«Привет! Меня зовут Амина!»", ok: true },
        { t: "«Извините, я опоздала!»" },
        { t: "«Можно выйти?»" },
      ],
      why: "Hello! My name is Amina! — «Привет! Меня зовут Амина!» Первая фраза новой истории. У тебя когда-то была точно такая же.",
    },
    {
      kind: "assemble",
      stage: 3,
      tag: "Собери фразу",
      q: "Ответь Амине — как когда-то ответили тебе:",
      note: "Ты собирал эту фразу в самой первой главе Starter. Тогда — по слогам. Сейчас — не глядя.",
      words: ["Nice", "to", "meet", "you,", "Amina!"],
      answer: "Nice to meet you, Amina!",
      why: "Nice to meet you, Amina! — «Приятно познакомиться, Амина!» Та же фраза, тот же смысл — но теперь её говорит учитель.",
      phrase: { en: "Nice to meet you!", ru: "Приятно познакомиться! (снова — но уже как учитель)" },
    },
    {
      kind: "fill",
      stage: 4,
      tag: "Последнее задание",
      qBefore: "My story began with the word «",
      qAfter: "» — and so will yours.",
      hintRu: "Моя история началась со слова «…» — и твоя начнётся с него же. (самое первое слово этого курса!)",
      note: "Самое первое слово самого первого урока. Ты знаешь его лучше всех слов на свете.",
      answer: "hello",
      why: "My story began with the word «Hello» — and so will yours. — «Моя история началась со слова „Hello“ — и твоя начнётся с него же».",
    },
    {
      kind: "assemble",
      stage: 4,
      tag: "Финал",
      q: "Напиши на доске девиз клуба — последняя фраза всей истории:",
      note: "Never — никогда, stop — переставать, learning — учиться. Три слова, которые привели героя из Алматы в Лондон и обратно.",
      words: ["Never", "stop", "learning!"],
      answer: "Never stop learning!",
      why: "Never stop learning! — «Никогда не переставай учиться!» История Алима закончена. Твоя — продолжается.",
      phrase: { en: "Never stop learning!", ru: "Никогда не переставай учиться!" },
    },
    {
      kind: "story",
      stage: 4,
      en: "The kids copy the motto into their notebooks. Somewhere in London, Emma waters the office plants, Sarah opens a new project, and Daniyar books two tickets to Almaty for the club's first graduation. THE END — and twelve new beginnings.",
      ru: "Дети переписывают девиз в тетради. Где-то в Лондоне Эмма поливает офисные цветы, Сара открывает новый проект, а Данияр берёт два билета в Алматы — на первый выпускной клуба. КОНЕЦ — и двенадцать новых начал.",
    },
  ],
  words: [
    { en: "I have been to…", ru: "я бывал в…" },
    { en: "local time", ru: "местное время" },
    { en: "it all started with…", ru: "всё началось с…" },
    { en: "become → has become", ru: "становиться → стал" },
    { en: "the student has become the teacher", ru: "ученик стал учителем" },
    { en: "never stop learning", ru: "никогда не переставай учиться" },
  ],
};

export default chapter6;
