import type { Chapter } from "@/lib/types";

const chapter4: Chapter = {
  slug: "negotiations",
  title: "Переговоры",
  subtitle:
    "Мужчина в дорогом костюме — инвестор, и он хочет купить ваше приложение. Самые сложные переговоры — те, где на кону мечта. Учимся вести их достойно.",
  goals: [
    "уточнять условия предложения",
    "брать паузу на обдумывание",
    "вежливо, но твёрдо отказывать",
    "объяснять свою позицию собеседнику",
  ],
  stages: [
    { icon: "📩", name: "Приглашение" },
    { icon: "🏦", name: "Предложение" },
    { icon: "🤔", name: "Пауза" },
    { icon: "⚖️", name: "Решение" },
    { icon: "🤝", name: "Уважение" },
  ],
  steps: [
    {
      kind: "story",
      stage: 0,
      en: "Monday. An email from «Stone Capital»: Mr Stone saw your talk and invites you to his office — glass tower, 30th floor, a view over the whole City of London.",
      ru: "Понедельник. Письмо от «Stone Capital»: мистер Стоун видел ваше выступление и приглашает в свой офис — стеклянная башня, 30-й этаж, вид на весь лондонский Сити.",
    },
    {
      kind: "listen",
      stage: 1,
      tag: "Аудирование",
      q: "Мистер Стоун не тратит время. Что он предлагает?",
      audio: "We would like to buy your app.",
      note: "Would like to — вежливое «хотели бы» (мягче, чем want). Лови главный глагол после to!",
      options: [
        { t: "Купить ваше приложение", ok: true },
        { t: "Протестировать ваше приложение" },
        { t: "Разрекламировать ваше приложение" },
      ],
      why: "We would like to buy your app — «Мы хотели бы купить ваше приложение». Would like to — стандарт деловых переговоров.",
      phrase: { en: "We would like to…", ru: "Мы хотели бы… (вежливое намерение)" },
    },
    {
      kind: "assemble",
      stage: 1,
      tag: "Уточни условия",
      q: "Не соглашайся и не отказывайся — сначала спроси детали:",
      note: "В переговорах побеждает тот, кто задаёт вопросы. Exactly — «именно, точно»: What exactly…? — «Что именно…?». Offer — предлагать.",
      words: ["What", "exactly", "do", "you", "offer?"],
      answer: "What exactly do you offer?",
      why: "What exactly do you offer? — «Что именно вы предлагаете?» Никогда не отвечай на предложение, пока не узнал его целиком.",
      phrase: { en: "What exactly do you offer?", ru: "Что именно вы предлагаете?" },
    },
    {
      kind: "story",
      stage: 1,
      en: "The offer is serious: a lot of money for you and Daniyar. But one condition — the app will have a paid subscription. «Free apps don't make money», Mr Stone smiles.",
      ru: "Предложение серьёзное: большие деньги для вас с Данияром. Но одно условие — в приложении появится платная подписка. «Бесплатные приложения не приносят денег», — улыбается мистер Стоун.",
    },
    {
      kind: "choice",
      stage: 2,
      tag: "Возьми паузу",
      q: "Решение слишком важное, чтобы принимать его сразу. Как попросить время подумать?",
      note: "Think it over — «обдумать» (over добавляет основательности). Let me think it over — «дайте мне это обдумать». В переговорах пауза — сила, а не слабость.",
      options: [
        { t: "Let me think it over.", ok: true },
        { t: "Yes! Where do I sign?!" },
        { t: "No. Goodbye." },
      ],
      why: "Let me think it over — «Позвольте мне это обдумать». Профессионалы никогда не решают большие вопросы на месте.",
      phrase: { en: "Let me think it over.", ru: "Позвольте мне это обдумать." },
    },
    {
      kind: "story",
      stage: 2,
      en: "That evening you and Daniyar walk along the Thames — the same route as three years ago. The money could change your families' lives. But you both remember a student in Almaty opening the app: «Hello!»",
      ru: "Вечером вы с Данияром идёте вдоль Темзы — тем же маршрутом, что три года назад. Эти деньги могли бы изменить жизнь ваших семей. Но вы оба помните студента в Алматы, который открывает приложение: «Hello!»",
    },
    {
      kind: "fill",
      stage: 3,
      tag: "Ваше решение",
      qBefore: "Our app will always be ",
      qAfter: ". That is our answer.",
      hintRu: "Наше приложение всегда будет бесплатным. Это наш ответ. (главное слово вашей миссии)",
      note: "Free — бесплатный. Will always be — «всегда будет» (will + always + be). Иногда самое сильное слово в переговорах — то, от которого не отступаешь.",
      answer: "free",
      why: "Our app will always be free — «Наше приложение всегда будет бесплатным». Решение принято — вместе, как всё в этой истории.",
      phrase: { en: "It will always be free.", ru: "Это всегда будет бесплатным." },
    },
    {
      kind: "choice",
      stage: 3,
      tag: "Вежливый отказ",
      q: "Как отказать мистеру Стоуну — твёрдо, но уважительно?",
      note: "Формула вежливого «нет»: поблагодари (thank you for your offer) + откажись (but…). Отказ без благодарности звучит как грубость, благодарность без отказа — как «да».",
      options: [
        { t: "Thank you for your offer, but our answer is no.", ok: true },
        { t: "Your offer is bad and you should feel bad." },
        { t: "Maybe yes, maybe no, who knows…" },
      ],
      why: "Thank you for your offer, but our answer is no — «Спасибо за предложение, но наш ответ — нет». Твёрдое «нет» в вежливой упаковке — высший пилотаж переговоров.",
      phrase: { en: "Thank you for your offer, but…", ru: "Спасибо за предложение, но… (вежливый отказ)" },
    },
    {
      kind: "assemble",
      stage: 3,
      tag: "Объясни причину",
      q: "Мистер Стоун поднимает бровь: «Почему?» Ответь ему:",
      note: "Everything — всё (ты знаешь его с отеля!). Простая истина, которая объясняет ваш отказ лучше любых цифр.",
      words: ["Money", "is", "not", "everything."],
      answer: "Money is not everything.",
      why: "Money is not everything — «Деньги — это не всё». Три года назад ты не смог бы это сказать. Теперь можешь — на двух языках.",
      phrase: { en: "Money is not everything.", ru: "Деньги — это не всё." },
    },
    {
      kind: "listen",
      stage: 4,
      tag: "Аудирование",
      q: "Долгая пауза… и неожиданная реакция мистера Стоуна. Какая?",
      audio: "I respect your decision. Good luck, gentlemen!",
      note: "Respect — уважать, decision — решение. Gentlemen — джентльмены (вежливое обращение к мужчинам).",
      options: [
        { t: "Он уважает ваше решение и желает удачи", ok: true },
        { t: "Он повышает цену в два раза" },
        { t: "Он обещает создать конкурента" },
      ],
      why: "I respect your decision. Good luck, gentlemen! — «Я уважаю ваше решение. Удачи, джентльмены!» Сильные люди уважают тех, кто знает себе цену.",
      phrase: { en: "I respect your decision.", ru: "Я уважаю ваше решение." },
    },
    {
      kind: "story",
      stage: 4,
      en: "In the lift, Daniyar exhales: «We just said no to a fortune. Why do I feel like we won?» You press the ground-floor button: «Because we did».",
      ru: "В лифте Данияр выдыхает: «Мы только что отказались от состояния. Почему я чувствую, что мы победили?» Ты нажимаешь кнопку первого этажа: «Потому что так и есть».",
    },
  ],
  words: [
    { en: "would like to…", ru: "хотели бы… (вежливо)" },
    { en: "offer", ru: "предложение, предлагать" },
    { en: "what exactly…?", ru: "что именно…?" },
    { en: "let me think it over", ru: "позвольте это обдумать" },
    { en: "respect / decision", ru: "уважать / решение" },
    { en: "money is not everything", ru: "деньги — это не всё" },
  ],
};

export default chapter4;
