import type { Chapter } from "@/lib/types";

const drills: Chapter = {
  slug: "drills-u6",
  title: "Тренажёр: пассив и косвенная речь",
  subtitle: "Отработка юнита «Пассив и косвенная речь»: страдательный залог и передача чужих слов.",
  section: "exercise",
  stages: [
    { icon: "🏛️", name: "Пассив" },
    { icon: "💬", name: "Косвенная речь" },
    { icon: "✅", name: "Готово" },
  ],
  steps: [
    {
      kind: "fill",
      stage: 0,
      tag: "Пассив",
      qBefore: "This castle ",
      qAfter: " built 900 years ago.",
      hintRu: "Этот замок построен 900 лет назад. (be + третья форма, прошедшее время)",
      answer: "was",
      why: "This castle was built — was + третья форма (built) = пассив в прошлом.",
    },
    {
      kind: "choice",
      stage: 0,
      tag: "Пассив",
      q: "«На английском говорят везде». Как сказать?",
      note: "Исполнитель неважен — пассив в настоящем времени: is spoken.",
      options: [
        { t: "English is spoken everywhere.", ok: true },
        { t: "English speaks everywhere." },
        { t: "English is speaking everywhere." },
      ],
      why: "English is spoken — is + speak в третьей форме (spoken).",
    },
    {
      kind: "choice",
      stage: 0,
      tag: "Пассив + by",
      q: "«Приложение создано двумя друзьями». Как указать исполнителя?",
      note: "Если исполнитель важен, добавляем by.",
      options: [
        { t: "The app was made by two friends.", ok: true },
        { t: "The app was made from two friends." },
        { t: "The app made by two friends." },
      ],
      why: "was made by — by вводит исполнителя действия в пассиве.",
    },
    {
      kind: "fill",
      stage: 1,
      tag: "Косвенная речь",
      qBefore: "Tom said he ",
      qAfter: " tired.",
      hintRu: "Том сказал, что устал. («I am tired» → сдвиг am в прошлое)",
      answer: "was",
      why: "«I am tired» → he was tired — am сдвигается в was в косвенной речи.",
    },
    {
      kind: "choice",
      stage: 1,
      tag: "Косвенная речь",
      q: "Она сказала: «I will call back». Как передать её слова?",
      note: "will → would при сдвиге в косвенную речь.",
      options: [
        { t: "She said she would call back.", ok: true },
        { t: "She said she will call back." },
        { t: "She said she calls back." },
      ],
      why: "will → would — стандартный сдвиг времени в косвенной речи.",
    },
    {
      kind: "choice",
      stage: 1,
      tag: "Косвенная речь",
      q: "Он сказал: «I have a new job». Как передать это Тому?",
      note: "have a job → had a new job (сдвиг в прошлое).",
      options: [
        { t: "He told me he had a new job.", ok: true },
        { t: "He told me he has a new job." },
        { t: "He told me he have a new job." },
      ],
      why: "He told me he had a new job — has/have сдвигается в had.",
    },
    {
      kind: "assemble",
      stage: 2,
      tag: "Финал",
      q: "Собери фразу с пассивом: «Приложение было создано, чтобы знания были доступны каждому»:",
      note: "The app was made + so that knowledge would be available to everyone.",
      words: ["The", "app", "was", "made", "to", "help", "everyone", "learn", "for", "free."],
      answer: "The app was made to help everyone learn for free.",
      why: "The app was made — пассив описывает результат, не важно кем именно. Тренажёр пройден — курс английского закончен!",
    },
  ],
  words: [],
};

export default drills;
