import type { Chapter } from "@/lib/types";

const drills: Chapter = {
  slug: "drills-2",
  title: "Тренажёр 2: косвенная речь и Passive",
  subtitle:
    "Вторая тренировка уровня B2: передача чужих слов, страдательный залог во всех временах, Past Perfect и расшифровка британских преуменьшений.",
  section: "exercise",
  stages: [
    { icon: "💬", name: "Косвенная речь" },
    { icon: "🏛️", name: "Passive" },
    { icon: "⏮️", name: "Past Perfect" },
    { icon: "🎩", name: "Расшифровка" },
    { icon: "✅", name: "Готово" },
  ],
  steps: [
    {
      kind: "choice",
      stage: 0,
      tag: "Косвенная речь",
      q: "Эмма сказала: «I will call you». Передай её слова:",
      note: "При пересказе will сдвигается в would.",
      options: [
        { t: "Emma said she would call me.", ok: true },
        { t: "Emma said she will call I." },
        { t: "Emma said I will call you." },
      ],
      why: "will → would, I → she, you → me. Три сдвига — и чужие слова переданы правильно.",
    },
    {
      kind: "fill",
      stage: 0,
      tag: "Косвенная речь",
      qBefore: "Tom said he ",
      qAfter: " tired after the long flight.",
      hintRu: "Том сказал, что устал после долгого перелёта. (was — сдвиг из «I am tired»)",
      note: "Прямая речь: «I am tired». В пересказе am сдвигается на шаг назад.",
      answer: "was",
      why: "Tom said he was tired — am → was при передаче чужих слов.",
    },
    {
      kind: "choice",
      stage: 0,
      tag: "Косвенная речь",
      q: "Сара сказала: «I can help». Как передать?",
      note: "can сдвигается в could.",
      options: [
        { t: "Sarah said she could help.", ok: true },
        { t: "Sarah said she can helped." },
        { t: "Sarah said I can help." },
      ],
      why: "can → could: Sarah said she could help.",
    },
    {
      kind: "fill",
      stage: 1,
      tag: "Passive настоящего",
      qBefore: "This dish ",
      qAfter: " made from rice and meat.",
      hintRu: "Это блюдо готовится из риса и мяса. (Passive настоящего для it)",
      note: "Passive настоящего: is/are + V3. Блюдо — it.",
      answer: "is",
      why: "This dish is made from rice and meat — is + made, классический Passive.",
    },
    {
      kind: "choice",
      stage: 1,
      tag: "Passive прошлого",
      q: "«Телефон изобрели в 1876 году». Как правильно?",
      note: "Passive прошлого: was/were + V3. Изобретатель не важен — важен факт.",
      options: [
        { t: "The telephone was invented in 1876.", ok: true },
        { t: "The telephone invented in 1876." },
        { t: "The telephone is invent in 1876." },
      ],
      why: "was invented — «был изобретён». Кто изобрёл — за кадром, поэтому Passive.",
    },
    {
      kind: "choice",
      stage: 1,
      tag: "Passive с by",
      q: "Хочешь назвать автора: «Эта книга написана Чеховым». Как?",
      note: "Если исполнитель важен, добавь by: … by Chekhov.",
      options: [
        { t: "This book was written by Chekhov.", ok: true },
        { t: "This book was written from Chekhov." },
        { t: "Chekhov was written this book." },
      ],
      why: "was written by Chekhov — by вводит автора действия.",
    },
    {
      kind: "fill",
      stage: 2,
      tag: "Past Perfect",
      qBefore: "When we arrived, the film ",
      qAfter: " already started.",
      hintRu: "Когда мы пришли, фильм уже начался (ДО нашего прихода). (had — прошлое до прошлого)",
      note: "Два прошлых события: фильм начался РАНЬШЕ прихода → had + V3.",
      answer: "had",
      why: "The film had already started — сначала начался фильм, потом пришли мы. Had расставляет порядок.",
    },
    {
      kind: "choice",
      stage: 2,
      tag: "Past Perfect",
      q: "Выбери фразу, где порядок событий передан верно: «Я потерял ключи, которые купил утром»:",
      note: "Покупка была раньше потери → покупка в Past Perfect.",
      options: [
        { t: "I lost the keys that I had bought in the morning.", ok: true },
        { t: "I had lost the keys that I bought in the morning." },
        { t: "I lose the keys that I had buy in the morning." },
      ],
      why: "Сначала had bought (купил), потом lost (потерял). Более раннее событие получает had.",
    },
    {
      kind: "choice",
      stage: 3,
      tag: "Расшифровка",
      q: "Британский коллега о твоём плане: «Interesting…» Что это на самом деле значит?",
      note: "Шкала преуменьшений из главы о британском юморе. Interesting — слово-ловушка!",
      options: [
        { t: "«Сомнительно» — он не в восторге", ok: true },
        { t: "«Гениально» — он восхищён" },
        { t: "«Мне всё равно»" },
      ],
      why: "Interesting… у британца чаще значит вежливое сомнение. Восторг звучал бы как «Not bad at all!»",
    },
    {
      kind: "choice",
      stage: 3,
      tag: "Расшифровка",
      q: "Британец: «I might be a little late». К чему готовиться?",
      note: "a little — то самое преуменьшение.",
      options: [
        { t: "Он опоздает сильно", ok: true },
        { t: "Он придёт на пару минут позже" },
        { t: "Он придёт раньше" },
      ],
      why: "I might be a little late = «сильно опоздаю». Чем мягче слова — тем серьёзнее факт.",
    },
    {
      kind: "assemble",
      stage: 4,
      tag: "Финал",
      q: "Собери фразу с Passive — она про тебя: «Эта платформа была создана для таких учеников, как ты»:",
      note: "was created — Passive прошлого, for learners like you — для учеников, как ты.",
      words: ["This", "platform", "was", "created", "for", "learners", "like", "you."],
      answer: "This platform was created for learners like you.",
      why: "This platform was created for learners like you — и это правда. Тренажёр пройден!",
    },
  ],
  words: [],
};

export default drills;
