import type { Chapter } from "@/lib/types";

const drills: Chapter = {
  slug: "drills",
  title: "Тренажёр: все времена и живая речь",
  subtitle:
    "Отработка правил B2: выбор времени по сигналам, страдательный залог, косвенная речь, хвостовые вопросы, идиомы и регистры вежливости.",
  section: "exercise",
  stages: [
    { icon: "🗺️", name: "Выбор времени" },
    { icon: "🏛️", name: "Passive" },
    { icon: "💬", name: "Речь" },
    { icon: "🎭", name: "Идиомы" },
    { icon: "✅", name: "Готово" },
  ],
  steps: [
    {
      kind: "choice",
      stage: 0,
      tag: "Выбор времени",
      q: "«Смотри! Дождь …» Какое время?",
      note: "Look! — сигнал процесса прямо сейчас.",
      options: [
        { t: "Look! It is raining.", ok: true },
        { t: "Look! It rains." },
        { t: "Look! It rained." },
      ],
      why: "Look! → процесс сейчас → Present Continuous: it is raining.",
    },
    {
      kind: "choice",
      stage: 0,
      tag: "Выбор времени",
      q: "«Я работаю здесь уже три года (и продолжаю)». Какое время?",
      note: "Начал в прошлом + продолжается сейчас + for = Present Perfect.",
      options: [
        { t: "I have worked here for three years.", ok: true },
        { t: "I worked here for three years." },
        { t: "I work here for three years." },
      ],
      why: "have worked + for — опыт, который длится до сих пор.",
    },
    {
      kind: "fill",
      stage: 0,
      tag: "Past Continuous",
      qBefore: "I ",
      qAfter: " walking home when it started to rain.",
      hintRu: "Я шёл домой, когда начался дождь. (процесс в прошлом для I)",
      note: "Past Continuous: was/were + -ing. Длинное действие прервано коротким.",
      answer: "was",
      why: "I was walking when it started — процесс (was walking) прерван событием (started).",
    },
    {
      kind: "choice",
      stage: 1,
      tag: "Passive",
      q: "«Этот мост построен 100 лет назад». Как правильно?",
      note: "Passive прошлого: was/were + третья форма.",
      options: [
        { t: "This bridge was built 100 years ago.", ok: true },
        { t: "This bridge built 100 years ago." },
        { t: "This bridge is build 100 years ago." },
      ],
      why: "was built — страдательный залог: важно ЧТО сделано, а не кем.",
    },
    {
      kind: "fill",
      stage: 1,
      tag: "Passive",
      qBefore: "English ",
      qAfter: " spoken all over the world.",
      hintRu: "На английском говорят по всему миру. (Passive настоящего для English = it)",
      answer: "is",
      why: "English is spoken — is + V3, настоящий Passive.",
    },
    {
      kind: "choice",
      stage: 2,
      tag: "Косвенная речь",
      q: "Том сказал: «I am tired». Как передать его слова?",
      note: "В косвенной речи время сдвигается назад: am → was.",
      options: [
        { t: "Tom said he was tired.", ok: true },
        { t: "Tom said he is tired yesterday." },
        { t: "Tom said I am tired." },
      ],
      why: "Tom said he was tired — am сдвинулось в was, I стало he.",
    },
    {
      kind: "choice",
      stage: 2,
      tag: "Хвостовой вопрос",
      q: "Заверши по правилу зеркала: «You like tea, …?»",
      note: "Положительная фраза → отрицательный хвост с тем же помощником.",
      options: [
        { t: "don't you?", ok: true },
        { t: "do you?" },
        { t: "aren't you?" },
      ],
      why: "You like tea, don't you? — Present Simple → хвост с don't.",
    },
    {
      kind: "fill",
      stage: 2,
      tag: "Регистр",
      qBefore: "We ",
      qAfter: " like to discuss the details.",
      hintRu: "Мы хотели бы обсудить детали. (вежливое «хотели бы», одно слово)",
      note: "Деловое «хотим» = would like to.",
      answer: "would",
      why: "We would like to discuss — стандарт деловых переговоров.",
    },
    {
      kind: "choice",
      stage: 3,
      tag: "Идиомы",
      q: "«The test was a piece of cake» — тест был…",
      options: [
        { t: "…очень лёгким", ok: true },
        { t: "…про торты" },
        { t: "…очень сложным" },
      ],
      why: "a piece of cake — проще простого.",
    },
    {
      kind: "choice",
      stage: 3,
      tag: "Understatement",
      q: "Британец о твоём проекте: «Quite good, actually». Это значит…",
      note: "Британское преуменьшение: сдержанные слова = сильная похвала.",
      options: [
        { t: "«Правда здорово» — искренняя похвала", ok: true },
        { t: "«Так себе» — вежливый отказ" },
        { t: "«Неплохо для новичка» — снисхождение" },
      ],
      why: "Quite good, actually — высокая оценка в британской упаковке.",
    },
    {
      kind: "assemble",
      stage: 4,
      tag: "Финал",
      q: "Собери финальную фразу тренажёра — хвостовой вопрос:",
      note: "It is + хвост-зеркало isn't it.",
      words: ["English", "is", "easy", "now,", "isn't", "it?"],
      answer: "English is easy now, isn't it?",
      why: "English is easy now, isn't it? — и это уже не вопрос, а факт. Тренажёр пройден!",
    },
  ],
  words: [],
};

export default drills;
