import type { Chapter } from "@/lib/types";

const chapter5: Chapter = {
  slug: "editing-the-press-release",
  title: "Редактура пресс-релиза",
  subtitle:
    "Партнёрство подтверждено — фонд просит совместный пресс-релиз. Носитель языка-редактор помогает сделать текст компактнее и естественнее.",
  goals: [
    "сокращать предложения через причастные обороты",
    "использовать редуцированные придаточные",
    "редактировать текст в сторону более естественного звучания",
  ],
  stages: [
    { icon: "📰", name: "Черновик" },
    { icon: "✂️", name: "Причастные обороты" },
    { icon: "🔧", name: "Редуцированные" },
    { icon: "🖋️", name: "Финальная правка" },
    { icon: "✅", name: "Готово" },
  ],
  steps: [
    {
      kind: "story",
      stage: 0,
      en: "The foundation's editor, Emma, video-calls you. «Your draft is great content-wise. But it reads a bit heavy — too many short sentences in a row. Let's tighten it up.»",
      ru: "Редактор фонда, Эмма, звонит по видеосвязи. «Твой черновик отлично написан по содержанию. Но читается немного тяжело — слишком много коротких предложений подряд. Давай сожмём текст».",
    },
    {
      kind: "choice",
      stage: 0,
      tag: "Причастный оборот",
      q: "Эмма предлагает объединить: «After I finished the report, I sent it to the team». Как сократить через причастный оборот?",
      note: "Having + V3 заменяет придаточное с одним и тем же подлежащим.",
      options: [
        { t: "Having finished the report, I sent it to the team.", ok: true },
        { t: "Finished the report, I sent it to the team." },
        { t: "Having finish the report, I sent it to the team." },
      ],
      why: "Having finished the report — Having + V3 показывает, что действие завершилось раньше основного.",
    },
    {
      kind: "fill",
      stage: 1,
      tag: "Причастный оборот",
      qBefore: "",
      qAfter: " for years in international education, Emma understood exactly what the foundation needed.",
      hintRu: "Проработав годы в международном образовании, Эмма точно понимала, что нужно фонду. (having + третья форма work)",
      note: "Having worked — причастный оборот вместо «Because she had worked…».",
      answer: "Having worked",
      why: "Having worked for years… — сокращает «Because she had worked for years…» в компактный оборот.",
    },
    {
      kind: "choice",
      stage: 1,
      tag: "Причастный оборот -ing",
      q: "«Зная, насколько это рискованно, мы всё равно согласились». Как сказать через причастие?",
      note: "V-ing показывает одновременность или причину без Having, если действия происходят почти одновременно.",
      options: [
        { t: "Knowing how risky it was, we still agreed.", ok: true },
        { t: "Known how risky it was, we still agreed." },
        { t: "Having know how risky it was, we still agreed." },
      ],
      why: "Knowing how risky it was — V-ing заменяет «Because we knew…», действие и причина одновременны.",
    },
    {
      kind: "story",
      stage: 1,
      who: "Эмма",
      say: "Good. Now — this sentence: «The article, which was published last week, got a lot of attention.» Too heavy. Cut the which was.",
      ru: "Отлично. Теперь вот это предложение: «Статья, которая была опубликована на прошлой неделе, привлекла много внимания». Слишком тяжело. Убери «которая была».",
    },
    {
      kind: "assemble",
      stage: 2,
      tag: "Редуцированное придаточное",
      q: "Сократи предложение Эммы, убрав which was:",
      note: "The article published last week — which was исчезает, published остаётся как причастие.",
      words: ["The", "article", "published", "last", "week", "got", "a", "lot", "of", "attention."],
      answer: "The article published last week got a lot of attention.",
      why: "The article published last week — редуцированное придаточное: which was убрано, published работает само по себе.",
    },
    {
      kind: "choice",
      stage: 2,
      tag: "Редуцированное придаточное",
      q: "«Любой, кто заинтересован в проекте, может с нами связаться» — сократи фразу:",
      note: "who is убирается перед причастием interested.",
      options: [
        { t: "Anyone interested in the project can contact us.", ok: true },
        { t: "Anyone who interested in the project can contact us." },
        { t: "Anyone interesting in the project can contact us." },
      ],
      why: "Anyone interested… — who is убрано, interested остаётся как редуцированное придаточное.",
    },
    {
      kind: "fill",
      stage: 2,
      tag: "Редуцированное придаточное",
      qBefore: "The team ",
      qAfter: " the platform is based in three countries.",
      hintRu: "Команда, стоящая за платформой, базируется в трёх странах. (building → причастие, сокращённое «that builds»)",
      note: "the team building the platform = the team that builds the platform.",
      answer: "building",
      why: "The team building the platform — редуцированное придаточное вместо «that builds».",
    },
    {
      kind: "choice",
      stage: 3,
      tag: "Финальная правка",
      q: "Эмма читает финальный абзац вслух. Какая версия звучит наиболее естественно и компактно для пресс-релиза?",
      note: "Хороший пресс-релиз опирается на причастные обороты и редуцированные придаточные — они убирают лишние which/that/who is.",
      options: [
        { t: "Having grown entirely through word of mouth, the platform now serves learners in over forty countries.", ok: true },
        { t: "The platform, which has grown entirely through word of mouth, and which now serves learners who are in over forty countries." },
        { t: "The platform grew through word of mouth. It now serves learners. They are in forty countries." },
      ],
      why: "Having grown entirely through word of mouth… — компактно и естественно, ровно то, чему учит Эмма.",
    },
    {
      kind: "assemble",
      stage: 4,
      tag: "Финал",
      q: "Собери финальное предложение пресс-релиза: «Основанная одним человеком, платформа теперь развивается благодаря глобальной команде добровольцев»:",
      note: "Founded by one person, the platform now grows thanks to a global team of volunteers.",
      words: ["Founded", "by", "one", "person,", "the", "platform", "now", "grows", "thanks", "to", "a", "global", "team", "of", "volunteers."],
      answer: "Founded by one person, the platform now grows thanks to a global team of volunteers.",
      why: "Founded by one person — причастный оборот в начале, компактно заменяющий «Which was founded by one person».",
    },
    {
      kind: "story",
      stage: 4,
      en: "Emma sends the final version back with one comment: «Much better. This actually sounds like it was written by someone who's fluent, not someone who's translating.»",
      ru: "Эмма присылает финальную версию с одним комментарием: «Намного лучше. Теперь это звучит так, будто писал человек, свободно владеющий языком, а не тот, кто переводит в уме».",
    },
  ],
  words: [
    { en: "to tighten up (a text)", ru: "сжать, сделать компактнее (текст)" },
    { en: "draft", ru: "черновик" },
    { en: "content-wise", ru: "по содержанию" },
    { en: "to grow through word of mouth", ru: "расти благодаря сарафанному радио" },
    { en: "volunteer", ru: "доброволец" },
  ],
};

export default chapter5;
