import type { Chapter } from "@/lib/types";

const chapter1: Chapter = {
  slug: "the-journalist-calls",
  title: "Звонок от журналиста",
  subtitle:
    "Корреспондент международного издания хочет взять интервью о CodeNTalk — вопросы уходят в прошлое, а ответы требуют гипотез.",
  goals: [
    "строить смешанные условные о прошлом и настоящем",
    "предполагать о прошлом через must/might/can't have",
    "давать интервью, не теряясь в вопросах о «а что если бы»",
  ],
  stages: [
    { icon: "📞", name: "Звонок" },
    { icon: "🌀", name: "Что если бы…" },
    { icon: "🔍", name: "Предположения" },
    { icon: "🎙️", name: "На камеру" },
    { icon: "✅", name: "Финал" },
  ],
  steps: [
    {
      kind: "story",
      stage: 0,
      en: "Your phone rings. An unknown number, London area code. «Hello, is this Alim? I'm calling from a tech magazine — we'd love to do a feature on CodeNTalk.»",
      ru: "Звонит телефон. Незнакомый номер, лондонский код. «Здравствуйте, это Алим? Я звоню из технологического журнала — мы хотели бы сделать материал о CodeNTalk».",
    },
    {
      kind: "choice",
      stage: 0,
      tag: "Смешанное условное",
      q: "Журналист спрашивает: «Что было бы, если бы вы не ушли с прежней работы?» Как ответить, используя смешанное условное (прошлое → настоящее)?",
      note: "If + Past Perfect (причина в прошлом), would + глагол (результат сейчас).",
      options: [
        { t: "If I hadn't quit my job, I wouldn't be here today.", ok: true },
        { t: "If I didn't quit my job, I wouldn't be here today." },
        { t: "If I hadn't quit my job, I won't be here today." },
      ],
      why: "If I hadn't quit my job, I wouldn't be here today — причина (уход с работы) в прошлом требует Past Perfect, результат (где ты сейчас) — would + глагол.",
    },
    {
      kind: "fill",
      stage: 1,
      tag: "Что если бы…",
      qBefore: "If Aidana ",
      qAfter: " believed in the idea, we wouldn't have started at all.",
      hintRu: "Если бы Айдана не поверила в идею, мы бы вообще не начали. (причина в прошлом — Past Perfect)",
      note: "Причина в прошлом (Айдана поверила тогда) → Past Perfect в if-части: hadn't believed.",
      answer: "hadn't",
      why: "If Aidana hadn't believed the idea… — Past Perfect в условии, потому что решение было в прошлом.",
    },
    {
      kind: "choice",
      stage: 1,
      tag: "Настоящее → прошлое",
      q: "«Если бы он не был таким упрямым, он бы не бросил тогда учёбу». Смешанное условное наоборот — какой вариант верный?",
      note: "Постоянное свойство сейчас (упрямство) → Past Simple. Результат в прошлом → would have + V3.",
      options: [
        { t: "If he weren't so stubborn, he wouldn't have quit.", ok: true },
        { t: "If he wasn't so stubborn, he wouldn't quit." },
        { t: "If he weren't so stubborn, he didn't quit." },
      ],
      why: "If he weren't so stubborn (постоянное свойство), he wouldn't have quit (результат в прошлом) — второй тип смешанного условного.",
    },
    {
      kind: "story",
      stage: 1,
      who: "Журналист",
      say: "Interesting. And how do you feel about turning down that investor last year?",
      ru: "Интересно. А как вы относитесь к тому, что отказали тому инвестору в прошлом году?",
    },
    {
      kind: "assemble",
      stage: 2,
      tag: "Предположение о прошлом",
      q: "Журналист говорит: «Вы, должно быть, сильно рисковали». Собери его фразу:",
      note: "must have + V3 — почти уверен, что так и было.",
      words: ["You", "must", "have", "taken", "a", "big", "risk."],
      answer: "You must have taken a big risk.",
      why: "must have taken — уверенное предположение о прошлом.",
      phrase: { en: "You must have taken a big risk.", ru: "Вы, должно быть, сильно рисковали." },
    },
    {
      kind: "choice",
      stage: 2,
      tag: "Предположение — сомнение",
      q: "Ты хочешь сказать: «Не может быть, чтобы они это уже читали — слишком быстро». Как правильно?",
      note: "can't have + V3 — почти уверен, что НЕТ.",
      options: [
        { t: "They can't have read it already — it's too fast.", ok: true },
        { t: "They mustn't have read it already — it's too fast." },
        { t: "They don't have read it already — it's too fast." },
      ],
      why: "can't have read — уверенность, что событие НЕ произошло, а не запрет (mustn't).",
    },
    {
      kind: "fill",
      stage: 2,
      tag: "Возможность",
      qBefore: "She ",
      qAfter: " have seen the article — I'm not sure.",
      hintRu: "Она, возможно, видела статью — я не уверен. (просто возможность, не уверенность)",
      note: "might/could have — просто ВОЗМОЖНО, в отличие от уверенного must have.",
      answer: "might",
      why: "She might have seen the article — возможность, а не уверенность (must have звучало бы категоричнее).",
    },
    {
      kind: "listen",
      stage: 3,
      tag: "Аудирование",
      q: "Журналист резюмирует твой ответ. Что он понял?",
      audio: "If you hadn't said no to that investor, the app wouldn't be free today.",
      note: "Слушай, что в Past Perfect (причина), а что в результате.",
      options: [
        { t: "Если бы ты не отказал инвестору, приложение не было бы бесплатным сейчас", ok: true },
        { t: "Если ты не откажешь инвестору, приложение не будет бесплатным" },
        { t: "Ты отказал инвестору, и приложение стало платным" },
      ],
      why: "If you hadn't said no… wouldn't be free today — смешанное условное: решение в прошлом определило результат сейчас.",
    },
    {
      kind: "choice",
      stage: 3,
      tag: "На камеру",
      q: "Финальный вопрос: «Что бы вы сказали себе три года назад?» Выбери наиболее естественный ответ уровня C1:",
      note: "Смешивание mixed conditional и past modal speculation — уровень C1 в действии.",
      options: [
        { t: "I would tell myself that even the scariest decisions can turn out to be the right ones.", ok: true },
        { t: "I will tell myself the decisions are right." },
        { t: "I am telling myself the decisions are right." },
      ],
      why: "I would tell myself… — гипотетический совет самому себе, естественная C1-конструкция без опоры на if.",
    },
    {
      kind: "assemble",
      stage: 4,
      tag: "Финал",
      q: "Собери свою финальную реплику для интервью: «Если бы я не рискнул, ничего из этого не случилось бы»:",
      note: "If I hadn't taken the risk, none of this would have happened.",
      words: ["If", "I", "hadn't", "taken", "the", "risk,", "none", "of", "this", "would", "have", "happened."],
      answer: "If I hadn't taken the risk, none of this would have happened.",
      why: "If I hadn't taken the risk… would have happened — смешанное условное о прошлом, определившем прошлое (обычный третий тип, но звучит естественно рядом со смешанными формами).",
    },
    {
      kind: "story",
      stage: 4,
      en: "The journalist laughs. «That's a great line. Mind if I use it as the headline?» You smile — this interview is going somewhere.",
      ru: "Журналист смеётся. «Отличная фраза. Не против, если возьму её в заголовок?» Ты улыбаешься — это интервью выходит на что-то большее.",
    },
  ],
  words: [
    { en: "to quit", ru: "уйти, бросить (работу)" },
    { en: "to take a risk", ru: "рисковать" },
    { en: "stubborn", ru: "упрямый" },
    { en: "to turn down", ru: "отклонить (предложение)" },
    { en: "headline", ru: "заголовок" },
    { en: "none of this", ru: "ничего из этого" },
  ],
};

export default chapter1;
