import type { Chapter } from "@/lib/types";

const chapter6: Chapter = {
  slug: "the-world-is-listening",
  title: "Голос, который слышат",
  subtitle:
    "Финал сезона: главная речь на международной конференции — и звонок из Алматы, который напоминает, зачем всё это было нужно.",
  goals: [
    "использовать приёмы убедительной речи (правило трёх, анафора)",
    "строить риторические вопросы",
    "произносить речь, которую запомнят",
  ],
  stages: [
    { icon: "🎤", name: "Сцена" },
    { icon: "🔁", name: "Анафора" },
    { icon: "❔", name: "Риторический вопрос" },
    { icon: "📱", name: "Звонок домой" },
    { icon: "🏁", name: "Финал" },
  ],
  steps: [
    {
      kind: "story",
      stage: 0,
      en: "The lights come up. A thousand people, a dozen languages, one shared silence waiting for you to speak. You take a breath and remember Daniyar's advice: never open with an apology.",
      ru: "Загорается свет. Тысяча человек, десяток языков, одна общая тишина в ожидании твоих слов. Ты делаешь вдох и вспоминаешь совет Данияра: никогда не начинай с извинений.",
    },
    {
      kind: "choice",
      stage: 0,
      tag: "Открытие",
      q: "Ты открываешь речь инверсией, отрепетированной ещё дома. Какая строка это была?",
      note: "Never had I imagined — сильное открытие через инверсию.",
      options: [
        { t: "Never had I imagined we would reach a million users.", ok: true },
        { t: "I never imagined we would reach a million users, honestly." },
        { t: "So, we reached a million users, which I never imagined." },
      ],
      why: "Never had I imagined… — та самая инверсия из юнита 2, теперь произнесённая перед залом.",
    },
    {
      kind: "fill",
      stage: 1,
      tag: "Правило трёх",
      qBefore: "We built it for students. We built it ",
      qAfter: " teachers. We built it for anyone who ever felt left out.",
      hintRu: "Мы создали это для студентов. Мы создали это для учителей. Мы создали это для каждого, кто когда-либо чувствовал себя лишним. (правило трёх)",
      note: "Три параллельные фразы подряд — приём анафоры (повтор в начале) и правила трёх.",
      answer: "for",
      why: "We built it for… — троекратный повтор создаёт ритм и убедительность.",
    },
    {
      kind: "choice",
      stage: 1,
      tag: "Анафора",
      q: "Какая версия использует анафору (повтор в начале фраз) сильнее всего?",
      note: "Анафора — повтор одной и той же конструкции в начале нескольких предложений подряд.",
      options: [
        { t: "It is free. It is simple. It is open to everyone.", ok: true },
        { t: "It is free, simple, and it's open to everyone, too." },
        { t: "Everyone can use it because it's free and simple." },
      ],
      why: "It is free. It is simple. It is open to everyone — три коротких, ритмичных повтора It is.",
    },
    {
      kind: "assemble",
      stage: 2,
      tag: "Риторический вопрос",
      q: "Собери риторический вопрос для зала: «Почему у знаний должна быть цена?»",
      note: "Риторический вопрос вовлекает слушателя, не требуя ответа вслух.",
      words: ["Why", "should", "knowledge", "have", "a", "price?"],
      answer: "Why should knowledge have a price?",
      why: "Why should knowledge have a price? — риторический вопрос, на который зал отвечает молчанием, а не голосом.",
      phrase: { en: "Why should knowledge have a price?", ru: "Почему у знаний должна быть цена?" },
    },
    {
      kind: "choice",
      stage: 2,
      tag: "Риторический вопрос",
      q: "Ты хочешь закончить основную мысль вопросом, который заставит зал задуматься. Какой вариант сильнее?",
      note: "Риторический вопрос звучит сильнее прямого утверждения в кульминации речи.",
      options: [
        { t: "If not now, then when?", ok: true },
        { t: "We should probably do this now, I think." },
        { t: "It's a good idea to do this now." },
      ],
      why: "If not now, then when? — классический риторический вопрос для кульминации выступления.",
    },
    {
      kind: "story",
      stage: 3,
      en: "Applause. You step off stage, phone buzzing in your pocket. A video call — Aidana, calling from the free club in Almaty.",
      ru: "Аплодисменты. Ты сходишь со сцены, в кармане вибрирует телефон. Видеозвонок — Айдана звонит из бесплатного клуба в Алматы.",
    },
    {
      kind: "story",
      stage: 3,
      who: "Айдана",
      say: "Someone wants to say hi. Go on, Amina — he can actually understand you now, in English.",
      ru: "Кто-то хочет с тобой поздороваться. Давай, Амина — он теперь и правда понимает тебя по-английски.",
    },
    {
      kind: "listen",
      stage: 3,
      tag: "Аудирование",
      q: "Амина, ученица клуба, говорит короткую фразу в камеру. Что она сказала?",
      audio: "Hello! I saw your speech. I want to build something free one day too.",
      note: "Простая, короткая фраза от начинающей ученицы — контраст с формальной речью, только что произнесённой тобой.",
      options: [
        { t: "Она видела речь и тоже хочет когда-нибудь создать что-то бесплатное", ok: true },
        { t: "Она просит помочь с домашним заданием" },
        { t: "Она спрашивает, когда ты приедешь в Алматы" },
      ],
      why: "I want to build something free one day too — тот же принцип, что звучал со сцены минуту назад, теперь произнесённый ребёнком.",
    },
    {
      kind: "choice",
      stage: 4,
      tag: "Финал",
      q: "Что ты отвечаешь Амине — используя приём, который сегодня выучил весь зал?",
      note: "Расщеплённое предложение для финальной, самой личной мысли сезона.",
      options: [
        { t: "It was people like you who made me want to build it in the first place.", ok: true },
        { t: "You made me want to build it, I guess." },
        { t: "I built it, and people like you use it now." },
      ],
      why: "It was people like you who made me want to build it — расщеплённая конструкция ставит акцент именно на Амине, не на тебе.",
    },
    {
      kind: "story",
      stage: 4,
      en: "The call ends. Somewhere in Almaty, a twelve-year-old just watched a stranger from a conference stage speak the same language she's only just beginning to learn. The circle, once again, is complete.",
      ru: "Звонок заканчивается. Где-то в Алматы двенадцатилетняя девочка только что увидела, как незнакомец со сцены конференции говорит на том же языке, который она только начинает учить. Круг снова замкнулся.",
    },
  ],
  words: [
    { en: "to feel left out", ru: "чувствовать себя лишним, исключённым" },
    { en: "applause", ru: "аплодисменты" },
    { en: "to buzz (a phone)", ru: "вибрировать (о телефоне)" },
    { en: "if not now, then when", ru: "если не сейчас, то когда" },
  ],
};

export default chapter6;
