import type { Chapter } from "@/lib/types";

const chapter3: Chapter = {
  slug: "the-partnership-proposal",
  title: "Заявка на партнёрство",
  subtitle:
    "Международный образовательный фонд заинтересовался CodeNTalk — пора писать формальную заявку на партнёрство.",
  goals: [
    "заменять глаголы существительными (номинализация)",
    "смягчать утверждения через hedging",
    "использовать формальные связки вместо разговорных",
  ],
  stages: [
    { icon: "📄", name: "Заявка" },
    { icon: "🧮", name: "Номинализация" },
    { icon: "🎩", name: "Hedging" },
    { icon: "🔗", name: "Связки" },
    { icon: "✅", name: "Финал" },
  ],
  steps: [
    {
      kind: "story",
      stage: 0,
      en: "A foundation focused on global education emails you: «We'd like to explore a possible partnership. Could you send us a short proposal outlining your approach?»",
      ru: "Фонд, занимающийся глобальным образованием, пишет тебе: «Мы хотели бы обсудить возможное партнёрство. Не могли бы вы прислать короткую заявку с описанием вашего подхода?»",
    },
    {
      kind: "choice",
      stage: 0,
      tag: "Официальный тон",
      q: "Первая строка заявки. Какой вариант звучит достаточно формально?",
      note: "В официальном тексте избегай разговорных сокращений и простых предложений.",
      options: [
        { t: "We are writing to propose a partnership between CodeNTalk and your foundation.", ok: true },
        { t: "So, we wanna team up with you guys." },
        { t: "Hey, let's partner up!" },
      ],
      why: "We are writing to propose… — стандартная официальная формула открытия делового письма.",
    },
    {
      kind: "fill",
      stage: 1,
      tag: "Номинализация",
      qBefore: "Our ",
      qAfter: " to keep the app free led to rapid growth.",
      hintRu: "Наше решение сделать приложение бесплатным привело к быстрому росту. (decide → существительное)",
      note: "decide → decision: номинализация делает фразу компактнее и весомее.",
      answer: "decision",
      why: "Our decision to keep the app free… — существительное decision вместо глагола decided.",
    },
    {
      kind: "choice",
      stage: 1,
      tag: "Номинализация",
      q: "«Улучшение вовлечённости было значительным» — как правильно выразить это существительным?",
      note: "improve → improvement.",
      options: [
        { t: "The improvement in engagement was significant.", ok: true },
        { t: "The improving in engagement was significant." },
        { t: "We improved engagement was significant." },
      ],
      why: "improvement — существительное от improve, стандартная номинализация для отчётов.",
    },
    {
      kind: "fill",
      stage: 2,
      tag: "Hedging",
      qBefore: "It ",
      qAfter: " be argued that free access is what made this project succeed.",
      hintRu: "Можно утверждать, что именно бесплатный доступ сделал проект успешным. (смягчённая формулировка)",
      note: "It could be argued that… — смягчает категоричное утверждение.",
      answer: "could",
      why: "It could be argued that… — hedging делает заявление более взвешенным, не абсолютным.",
    },
    {
      kind: "choice",
      stage: 2,
      tag: "Hedging",
      q: "«Это может говорить о том, что рынок больше, чем мы ожидали». Выбери формальный вариант:",
      note: "This may suggest that… — типичная hedging-конструкция.",
      options: [
        { t: "This may suggest that the market is bigger than we expected.", ok: true },
        { t: "This means the market is definitely bigger than we expected." },
        { t: "The market is bigger, we are 100% sure." },
      ],
      why: "This may suggest that… — осторожная формулировка вместо категоричного заявления.",
    },
    {
      kind: "story",
      stage: 2,
      who: "Данияр",
      say: "Don't oversell it. Foundations trust careful language more than big claims.",
      ru: "Не переусердствуй с обещаниями. Фонды больше доверяют осторожным формулировкам, чем громким заявлениям.",
    },
    {
      kind: "fill",
      stage: 3,
      tag: "Формальная связка",
      qBefore: "The market is competitive. ",
      qAfter: ", our approach is unique.",
      hintRu: "Рынок конкурентный. Тем не менее наш подход уникален. (формальная связка вместо but)",
      answer: "Nevertheless",
      why: "Nevertheless — формальный эквивалент but, уместный в деловом тексте.",
    },
    {
      kind: "choice",
      stage: 3,
      tag: "Формальная связка",
      q: "«Несмотря на трудности, проект продвигался вперёд». Выбери самый формальный вариант:",
      note: "Notwithstanding — книжный, более формальный эквивалент despite.",
      options: [
        { t: "Notwithstanding the challenges, the project moved forward.", ok: true },
        { t: "Despite the challenges, the project moved forward, no big deal." },
        { t: "But there were challenges, and the project moved forward." },
      ],
      why: "Notwithstanding the challenges — самый формальный вариант из трёх, уместный в заявке фонду.",
    },
    {
      kind: "choice",
      stage: 3,
      tag: "Furthermore",
      q: "Ты хочешь добавить ещё один аргумент после основного. Какое слово подходит?",
      note: "Furthermore/Moreover — формальные аналоги also.",
      options: [
        { t: "Furthermore, our model has already been tested across five countries.", ok: true },
        { t: "Also, our model has already been tested across five countries." },
        { t: "Plus, our model has already been tested across five countries." },
      ],
      why: "Furthermore — формальная связка, уместная в официальном документе, в отличие от also/plus.",
    },
    {
      kind: "assemble",
      stage: 4,
      tag: "Финал",
      q: "Собери финальное предложение заявки: «Мы хотели бы обсудить детали в удобное для вас время»:",
      note: "We would welcome the opportunity to discuss the details at your convenience.",
      words: ["We", "would", "welcome", "the", "opportunity", "to", "discuss", "the", "details", "at", "your", "convenience."],
      answer: "We would welcome the opportunity to discuss the details at your convenience.",
      why: "We would welcome the opportunity… at your convenience — образцовая формальная фраза для завершения деловой заявки.",
    },
    {
      kind: "story",
      stage: 4,
      en: "You read the proposal one last time, fix a comma, and hit send. Somewhere, a very careful, very formal email just left for a foundation that might change everything.",
      ru: "Ты в последний раз перечитываешь заявку, исправляешь запятую и нажимаешь «отправить». Где-то только что улетело очень аккуратное, очень формальное письмо фонду, который, возможно, изменит всё.",
    },
  ],
  words: [
    { en: "proposal", ru: "заявка, предложение" },
    { en: "foundation", ru: "фонд" },
    { en: "to outline", ru: "обрисовать, описать в общих чертах" },
    { en: "engagement", ru: "вовлечённость" },
    { en: "at your convenience", ru: "в удобное для вас время" },
  ],
};

export default chapter3;
