import type { Chapter } from "@/lib/types";

const chapter4: Chapter = {
  slug: "dinner-with-collaborators",
  title: "Ужин с коллегами",
  subtitle:
    "После конференции — неформальный ужин с международной командой. Пора переключиться с делового языка на живую, естественную речь.",
  goals: [
    "использовать продвинутые фразовые глаголы и коллокации",
    "понимать эллипсис и замещение в живой речи",
    "поддерживать непринуждённую беседу с носителями",
  ],
  stages: [
    { icon: "🍽️", name: "Ужин" },
    { icon: "🧩", name: "Фразовые глаголы" },
    { icon: "💬", name: "Живая речь" },
    { icon: "🥂", name: "Тост" },
    { icon: "✅", name: "Финал" },
  ],
  steps: [
    {
      kind: "story",
      stage: 0,
      en: "The conference is over. Someone suggests dinner — «somewhere loud, not another hotel restaurant». You end up at a small table with people from four different countries, and suddenly the formal English of the day feels far away.",
      ru: "Конференция закончилась. Кто-то предлагает поужинать — «где-нибудь шумно, только не в очередном ресторане отеля». Ты оказываешься за маленьким столом с людьми из четырёх разных стран, и формальный английский дня внезапно кажется далёким.",
    },
    {
      kind: "choice",
      stage: 0,
      tag: "Фразовый глагол",
      q: "Коллега рассказывает, как команда придумала идею. Какой фразовый глагол он использует?",
      note: "come up with — придумать (идею).",
      options: [
        { t: "We came up with the idea during a walk.", ok: true },
        { t: "We came down with the idea during a walk." },
        { t: "We came into the idea during a walk." },
      ],
      why: "come up with — стандартный фразовый глагол для «придумать идею».",
    },
    {
      kind: "fill",
      stage: 1,
      tag: "Фразовый глагол",
      qBefore: "Let's ",
      qAfter: " tomorrow to sort out the last details.",
      hintRu: "Давай завтра свяжемся, чтобы уладить последние детали. (коротко связаться)",
      note: "touch base — коротко связаться, обычно по работе.",
      answer: "touch base",
      why: "touch base — короткая связь для сверки деталей, очень частый деловой фразовый глагол.",
    },
    {
      kind: "choice",
      stage: 1,
      tag: "Фразовый глагол",
      q: "«Мы ещё не уладили все разногласия по контракту». Какой глагол подходит?",
      note: "iron out — уладить (детали, разногласия).",
      options: [
        { t: "We still need to iron out a few disagreements in the contract.", ok: true },
        { t: "We still need to iron up a few disagreements in the contract." },
        { t: "We still need to iron over a few disagreements in the contract." },
      ],
      why: "iron out — «уладить», дословно «разгладить утюгом».",
    },
    {
      kind: "fill",
      stage: 1,
      tag: "Фразовый глагол",
      qBefore: "Can I ",
      qAfter: " this idea by you before the meeting?",
      hintRu: "Можно я обсужу с тобой эту идею перед встречей? (посоветоваться, показать на проверку)",
      note: "run something by someone — посоветоваться, показать идею кому-то на проверку.",
      answer: "run",
      why: "run this idea by you — просьба быстро посоветоваться перед официальной встречей.",
    },
    {
      kind: "story",
      stage: 2,
      who: "Прия",
      say: "Wait, you already sent the proposal? — I did too, this morning.",
      ru: "Погоди, ты уже отправил заявку? — Я тоже, сегодня утром.",
    },
    {
      kind: "choice",
      stage: 2,
      tag: "Эллипсис",
      q: "«I did too» — что здесь опущено?",
      note: "I did too = I sent it too. Повтор всей фразы опускается в живой речи.",
      options: [
        { t: "Повтор глагола send — «I sent it too»", ok: true },
        { t: "Ничего, это отдельное короткое предложение" },
        { t: "Опущено отрицание" },
      ],
      why: "I did too — короткая замена вместо повтора «I sent the proposal too». Так носители экономят слова в живой речи.",
    },
    {
      kind: "choice",
      stage: 2,
      tag: "Замещение",
      q: "Кто-то спрашивает: «Are you coming to the after-party?» Естественный короткий ответ:",
      note: "I think so — «думаю, да», замещает целую фразу без повтора.",
      options: [
        { t: "I think so.", ok: true },
        { t: "I think that I am coming to the after-party." },
        { t: "Yes, I am thinking about coming to the after-party." },
      ],
      why: "I think so — естественная разговорная замена длинной фразы, характерная для C1-уровня беглости.",
    },
    {
      kind: "fill",
      stage: 2,
      tag: "Эллипсис в вопросе",
      qBefore: "",
      qAfter: " some?",
      hintRu: "Хочешь? (сокращённый вопрос вместо «Do you want some coffee?»)",
      note: "В непринуждённой речи очевидные слова опускаются: Want some? вместо Do you want some?",
      answer: "Want",
      why: "Want some? — типичное сокращение в неформальной беседе за столом.",
    },
    {
      kind: "listen",
      stage: 3,
      tag: "Аудирование",
      q: "Кто-то предлагает масштабировать сотрудничество. Что именно он говорит?",
      audio: "If we can scale this up together, it could reach ten times more people.",
      note: "scale up — расширить, масштабировать.",
      options: [
        { t: "Совместное масштабирование могло бы охватить в десять раз больше людей", ok: true },
        { t: "Проект нужно сократить в десять раз" },
        { t: "Масштабирование уже невозможно" },
      ],
      why: "scale this up — расширить проект; typical коллокация в разговоре о росте.",
    },
    {
      kind: "assemble",
      stage: 4,
      tag: "Тост",
      q: "Кто-то просит тебя сказать тост. Собери короткую, тёплую фразу: «За тех, кто верил в это с самого начала»:",
      note: "To everyone who believed in this from the very start.",
      words: ["To", "everyone", "who", "believed", "in", "this", "from", "the", "very", "start."],
      answer: "To everyone who believed in this from the very start.",
      why: "To everyone who believed… — классическая короткая формула тоста, естественная и тёплая.",
      phrase: { en: "To everyone who believed in this from the very start.", ru: "За тех, кто верил в это с самого начала." },
    },
    {
      kind: "story",
      stage: 4,
      en: "Glasses clink. Someone laughs too loudly at their own joke. For the first time all week, you're not translating in your head — you're just talking.",
      ru: "Звенят бокалы. Кто-то слишком громко смеётся над своей же шуткой. Впервые за всю неделю ты не переводишь в голове — ты просто разговариваешь.",
    },
  ],
  words: [
    { en: "to come up with", ru: "придумать (идею)" },
    { en: "to touch base", ru: "коротко связаться" },
    { en: "to iron out", ru: "уладить (разногласия, детали)" },
    { en: "to run something by someone", ru: "посоветоваться, показать на проверку" },
    { en: "to scale up", ru: "расширить, масштабировать" },
  ],
};

export default chapter4;
