import type { Chapter } from "@/lib/types";

const chapter2: Chapter = {
  slug: "the-keynote-invitation",
  title: "Приглашение на конференцию",
  subtitle:
    "Международная EdTech-конференция зовёт тебя выступить с ключевым докладом — пора учиться расставлять акценты в речи.",
  goals: [
    "выделять мысль через it was… that / what… was",
    "использовать инверсию после never, not only",
    "готовить выступление с чёткими акцентами",
  ],
  stages: [
    { icon: "📧", name: "Приглашение" },
    { icon: "🎯", name: "Что важно" },
    { icon: "⚡", name: "Инверсия" },
    { icon: "✍️", name: "Черновик речи" },
    { icon: "✅", name: "Финал" },
  ],
  steps: [
    {
      kind: "story",
      stage: 0,
      en: "An email arrives: «We would be honoured if you could deliver the opening keynote at this year's Global EdTech Summit.» You read it three times before it sinks in.",
      ru: "Приходит письмо: «Для нас была бы честью, если бы вы выступили с открывающим докладом на этом Global EdTech Summit». Ты перечитываешь его трижды, прежде чем осознаёшь смысл.",
    },
    {
      kind: "choice",
      stage: 0,
      tag: "Расщеплённое предложение",
      q: "Ты хочешь подчеркнуть: именно Айдана первой поверила в идею — не кто-то другой. Как это выделить?",
      note: "It was + выделяемое + that… — выносит конкретный элемент на первый план.",
      options: [
        { t: "It was Aidana who believed in this idea first.", ok: true },
        { t: "Aidana was who believed in this idea first." },
        { t: "It was who believed in this idea first, Aidana." },
      ],
      why: "It was Aidana who believed… — расщеплённая конструкция ставит акцент именно на Айдане.",
    },
    {
      kind: "fill",
      stage: 1,
      tag: "What… is/was",
      qBefore: "What surprised me most ",
      qAfter: " how fast it grew.",
      hintRu: "Больше всего меня удивило, как быстро это выросло. (глагол-связка после what-конструкции)",
      note: "What + подлежащее + глагол + is/was… — эта часть выносит идею вперёд.",
      answer: "was",
      why: "What surprised me most was how fast it grew — was связывает вынесенную мысль с её содержанием.",
    },
    {
      kind: "choice",
      stage: 1,
      tag: "Что важно",
      q: "Ты формулируешь главную мысль доклада: «Чего я на самом деле хотел — сделать это бесплатным для всех». Как сказать по-английски?",
      note: "What I really wanted was… — взвешенно и убедительно выносит идею вперёд.",
      options: [
        { t: "What I really wanted was to make it free for everyone.", ok: true },
        { t: "I really wanted was to make it free for everyone." },
        { t: "What I really wanted to make it free for everyone." },
      ],
      why: "What I really wanted was… — стандартная эмфатическая рамка для главной мысли.",
    },
    {
      kind: "story",
      stage: 1,
      who: "Данияр",
      say: "You need a strong opening line. Something people will remember.",
      ru: "Тебе нужна сильная первая фраза. Что-то, что люди запомнят.",
    },
    {
      kind: "assemble",
      stage: 2,
      tag: "Инверсия",
      q: "Собери сильную первую фразу доклада: «Никогда я не думал, что мы дойдём до миллиона пользователей»:",
      note: "Never had I imagined — после Never вспомогательный глагол выходит перед подлежащим.",
      words: ["Never", "had", "I", "imagined", "we", "would", "reach", "a", "million", "users."],
      answer: "Never had I imagined we would reach a million users.",
      why: "Never had I imagined… — инверсия после отрицательного наречия звучит выразительнее обычного порядка слов.",
      phrase: { en: "Never had I imagined we would reach a million users.", ru: "Никогда я не думал, что мы дойдём до миллиона пользователей." },
    },
    {
      kind: "choice",
      stage: 2,
      tag: "Not only… also",
      q: "«Мы не только отказали инвестору, но и выросли быстрее без него». Выбери верный порядок слов:",
      note: "Not only в начале требует инверсии: did we say.",
      options: [
        { t: "Not only did we say no to the investor, we also grew faster without him.", ok: true },
        { t: "Not only we said no to the investor, we also grew faster without him." },
        { t: "We not only did say no to the investor, we also grew faster without him." },
      ],
      why: "Not only did we say no… — инверсия обязательна после Not only в начале предложения.",
    },
    {
      kind: "fill",
      stage: 2,
      tag: "Инверсия — практика",
      qBefore: "Rarely ",
      qAfter: " you see a team this committed.",
      hintRu: "Редко увидишь такую преданную команду. (do выходит вперёд после Rarely)",
      note: "Rarely — ограничительное наречие, требует инверсии: Rarely do you see…",
      answer: "do",
      why: "Rarely do you see — вспомогательный do выходит перед подлежащим you.",
    },
    {
      kind: "listen",
      stage: 3,
      tag: "Аудирование",
      q: "Данияр репетирует с тобой финал речи. Что он предлагает сказать?",
      audio: "It was free education that changed everything for me, and it can change everything for you too.",
      note: "It was X that… — выделяет free education как главный элемент фразы.",
      options: [
        { t: "Именно бесплатное образование всё изменило для тебя — и может изменить для слушателей", ok: true },
        { t: "Бесплатное образование когда-нибудь всё изменит" },
        { t: "Образование ничего не изменило" },
      ],
      why: "It was free education that changed everything — расщеплённая конструкция ставит акцент на free education.",
    },
    {
      kind: "choice",
      stage: 3,
      tag: "Черновик речи",
      q: "Выбери самую сильную версию открывающей фразы для доклада:",
      note: "Инверсия и расщеплённые предложения звучат весомее прямого порядка слов на большой сцене.",
      options: [
        { t: "Never had I imagined that a free app could reach a million people.", ok: true },
        { t: "I never imagined that a free app could reach a million people." },
        { t: "A free app reached a million people, I never imagined that." },
      ],
      why: "Инверсия (Never had I imagined…) — приём именно для сцены, где нужна максимальная выразительность.",
    },
    {
      kind: "assemble",
      stage: 4,
      tag: "Финал",
      q: "Собери финальную строку черновика: «Именно люди, а не код, сделали этот проект живым»:",
      note: "It was the people, not the code, that made this project alive.",
      words: ["It", "was", "the", "people,", "not", "the", "code,", "that", "made", "this", "project", "alive."],
      answer: "It was the people, not the code, that made this project alive.",
      why: "It was the people… that made… — расщеплённое предложение с явным противопоставлением (not the code).",
    },
    {
      kind: "story",
      stage: 4,
      en: "You close your laptop. The speech isn't perfect yet — but for the first time, it sounds like something worth saying out loud.",
      ru: "Ты закрываешь ноутбук. Речь ещё не идеальна — но впервые она звучит как то, что действительно стоит произнести вслух.",
    },
  ],
  words: [
    { en: "to be honoured", ru: "быть удостоенным чести" },
    { en: "keynote", ru: "ключевой доклад" },
    { en: "to sink in", ru: "дойти до сознания, осмыслиться" },
    { en: "committed", ru: "преданный (делу)" },
    { en: "worth saying", ru: "то, что стоит сказать" },
  ],
};

export default chapter2;
