import type { Chapter } from "@/lib/types";

const drills: Chapter = {
  slug: "drills-u3",
  title: "Тренажёр: официальный и академический язык",
  subtitle: "Отработка юнита «Официальный и академический язык»: номинализация, hedging, формальные связки.",
  section: "exercise",
  stages: [
    { icon: "🧮", name: "Номинализация" },
    { icon: "🎩", name: "Hedging" },
    { icon: "🔗", name: "Связки" },
    { icon: "✅", name: "Готово" },
  ],
  steps: [
    {
      kind: "fill",
      stage: 0,
      tag: "Номинализация",
      qBefore: "The company's ",
      qAfter: " has been remarkable this year.",
      hintRu: "Рост компании в этом году был впечатляющим. (grow → существительное)",
      answer: "growth",
      why: "growth — номинализация от grow, стандартная для отчётов.",
    },
    {
      kind: "choice",
      stage: 0,
      tag: "Номинализация",
      q: "«Разработка нового курса заняла шесть месяцев». Выбери формальный вариант:",
      note: "develop → development.",
      options: [
        { t: "The development of the new course took six months.", ok: true },
        { t: "We developed the new course took six months." },
        { t: "The developing of the new course took six months." },
      ],
      why: "The development of… — существительное development вместо глагола developed.",
    },
    {
      kind: "fill",
      stage: 0,
      tag: "Номинализация",
      qBefore: "Their ",
      qAfter: " in the international market was gradual but steady.",
      hintRu: "Их успех на международном рынке был постепенным, но устойчивым. (succeed → существительное)",
      answer: "success",
      why: "success — номинализация от succeed.",
    },
    {
      kind: "choice",
      stage: 1,
      tag: "Hedging",
      q: "Хочешь осторожно предположить причину роста, не заявляя это как факт. Какой вариант верный?",
      note: "It could be argued that… смягчает категоричность.",
      options: [
        { t: "It could be argued that trust played a key role.", ok: true },
        { t: "Trust definitely played the only role, 100%." },
        { t: "It is a fact that trust played a key role." },
      ],
      why: "It could be argued that… — стандартная hedging-формула для осторожных выводов.",
    },
    {
      kind: "fill",
      stage: 1,
      tag: "Hedging",
      qBefore: "This ",
      qAfter: " suggest that the demand is higher than expected.",
      hintRu: "Это может говорить о том, что спрос выше, чем ожидалось. (мягкое предположение)",
      answer: "may",
      why: "This may suggest that… — осторожное, а не категоричное заявление.",
    },
    {
      kind: "choice",
      stage: 2,
      tag: "Формальная связка",
      q: "«Рынок сложный. Тем не менее мы движемся вперёд». Выбери формальный вариант:",
      note: "Nevertheless — формальный аналог but.",
      options: [
        { t: "The market is difficult. Nevertheless, we are moving forward.", ok: true },
        { t: "The market is difficult, but yeah, we are moving forward." },
        { t: "The market is difficult. So we are moving forward." },
      ],
      why: "Nevertheless — уместная формальная связка вместо разговорного but.",
    },
    {
      kind: "fill",
      stage: 2,
      tag: "Формальная связка",
      qBefore: "",
      qAfter: " the challenges, the team delivered the project on time.",
      hintRu: "Несмотря на трудности, команда сдала проект вовремя. (книжная формальная связка)",
      answer: "Notwithstanding",
      why: "Notwithstanding the challenges — книжный, самый формальный эквивалент despite.",
    },
    {
      kind: "choice",
      stage: 2,
      tag: "Furthermore",
      q: "Ты добавляешь ещё один пункт к списку аргументов в отчёте. Какое слово формальнее?",
      note: "Furthermore/Moreover формальнее, чем also.",
      options: [
        { t: "Furthermore, the results were consistent across all regions.", ok: true },
        { t: "Also, the results were consistent across all regions." },
        { t: "Oh, and the results were consistent across all regions." },
      ],
      why: "Furthermore — формальная связка, уместная в отчёте или заявке.",
    },
    {
      kind: "assemble",
      stage: 3,
      tag: "Финал",
      q: "Собери формальное предложение: «Можно утверждать, что именно решение остаться бесплатными обеспечило рост»:",
      note: "It could be argued that the decision to remain free drove the growth — hedging + номинализация вместе.",
      words: ["It", "could", "be", "argued", "that", "the", "decision", "to", "remain", "free", "drove", "the", "growth."],
      answer: "It could be argued that the decision to remain free drove the growth.",
      why: "hedging (could be argued) + номинализация (decision, growth) — обе темы юнита в одной фразе. Тренажёр пройден!",
    },
  ],
  words: [],
};

export default drills;
