import type { Chapter } from "@/lib/types";

const drills: Chapter = {
  slug: "drills-u2",
  title: "Тренажёр: эмфаза и акцент",
  subtitle: "Отработка юнита «Эмфаза и акцент»: расщеплённые предложения и инверсия.",
  section: "exercise",
  stages: [
    { icon: "🎯", name: "Расщеплённые" },
    { icon: "⚡", name: "Инверсия" },
    { icon: "✅", name: "Готово" },
  ],
  steps: [
    {
      kind: "fill",
      stage: 0,
      tag: "It was… that",
      qBefore: "It was the free access ",
      qAfter: " made the biggest difference.",
      hintRu: "Именно бесплатный доступ сыграл главную роль. (связующее слово расщеплённой конструкции)",
      answer: "that",
      why: "It was the free access that made the biggest difference — that связывает выделенный элемент с остальной фразой.",
    },
    {
      kind: "choice",
      stage: 0,
      tag: "What… was",
      q: "«Чего команде действительно не хватало — времени». Выбери верный вариант:",
      note: "What + подлежащее + глагол + was… выносит идею вперёд.",
      options: [
        { t: "What the team really needed was time.", ok: true },
        { t: "The team really needed was time." },
        { t: "What was the team really needed time." },
      ],
      why: "What the team really needed was time — стандартная эмфатическая рамка.",
    },
    {
      kind: "fill",
      stage: 0,
      tag: "It was… that",
      qBefore: "It was Daniyar ",
      qAfter: " suggested the free model in the first place.",
      hintRu: "Именно Данияр первым предложил бесплатную модель. (связующее слово)",
      answer: "who",
      why: "It was Daniyar who suggested — who используется, когда выделяется человек.",
    },
    {
      kind: "choice",
      stage: 1,
      tag: "Инверсия — Never",
      q: "«Никогда я не видел такой преданной команды». Выбери верный порядок слов:",
      note: "Never в начале требует инверсии.",
      options: [
        { t: "Never have I seen such a dedicated team.", ok: true },
        { t: "Never I have seen such a dedicated team." },
        { t: "I have never seen such a dedicated team, never." },
      ],
      why: "Never have I seen — вспомогательный глагол have выходит перед I.",
    },
    {
      kind: "fill",
      stage: 1,
      tag: "Инверсия — Not only",
      qBefore: "Not only ",
      qAfter: " the app succeed, it also inspired dozens of similar projects.",
      hintRu: "Приложение не только преуспело, но и вдохновило десятки похожих проектов. (вспомогательный глагол выходит вперёд)",
      answer: "did",
      why: "Not only did the app succeed — did выходит перед the app в инверсии.",
    },
    {
      kind: "choice",
      stage: 1,
      tag: "Инверсия — Rarely",
      q: "«Редко встретишь инвестора, который принимает отказ так спокойно». Выбери верный вариант:",
      note: "Rarely в начале требует инверсии: Rarely do you meet…",
      options: [
        { t: "Rarely do you meet an investor who takes rejection so calmly.", ok: true },
        { t: "Rarely you meet an investor who takes rejection so calmly." },
        { t: "You rarely do meet an investor who takes rejection so calmly." },
      ],
      why: "Rarely do you meet — do выходит перед you после Rarely.",
    },
    {
      kind: "choice",
      stage: 1,
      tag: "No sooner",
      q: "«Едва я закончил речь, как зал взорвался аплодисментами». Выбери верный вариант:",
      note: "No sooner… than — устойчивая инверсионная конструкция.",
      options: [
        { t: "No sooner had I finished the speech than the room burst into applause.", ok: true },
        { t: "No sooner I had finished the speech than the room burst into applause." },
        { t: "No sooner had I finished the speech when the room burst into applause." },
      ],
      why: "No sooner had I finished… than… — инверсия и than (не when) — фиксированная пара.",
    },
    {
      kind: "assemble",
      stage: 2,
      tag: "Финал",
      q: "Собери фразу, соединяющую обе темы: «Именно провал научил нас большему, чем любой успех»:",
      note: "It was failure that taught us more than any success — расщеплённая конструкция для финала.",
      words: ["It", "was", "failure", "that", "taught", "us", "more", "than", "any", "success."],
      answer: "It was failure that taught us more than any success.",
      why: "It was failure that taught us… — эмфаза на слове failure. Тренажёр пройден!",
    },
  ],
  words: [],
};

export default drills;
