import type { Chapter } from "@/lib/types";

const drills: Chapter = {
  slug: "drills-u1",
  title: "Тренажёр: смысл между строк",
  subtitle: "Отработка юнита «Смысл между строк»: смешанные условные и модальные глаголы предположения.",
  section: "exercise",
  stages: [
    { icon: "🌀", name: "Смешанные условные" },
    { icon: "🔍", name: "Предположения" },
    { icon: "✅", name: "Готово" },
  ],
  steps: [
    {
      kind: "fill",
      stage: 0,
      tag: "Смешанное условное",
      qBefore: "If I ",
      qAfter: " harder at university, I would have a different career now.",
      hintRu: "Если бы я усерднее учился в университете, у меня сейчас была бы другая карьера. (причина в прошлом)",
      note: "Причина в прошлом → Past Perfect: had studied.",
      answer: "had studied",
      why: "If I had studied harder… — Past Perfect в причине, потому что решение было в прошлом.",
    },
    {
      kind: "choice",
      stage: 0,
      tag: "Смешанное условное",
      q: "«Если бы она не была такой осторожной, она бы не выжила в том шторме». Выбери верный вариант:",
      note: "Постоянное свойство (осторожность) → Past Simple. Результат в прошлом → would have + V3.",
      options: [
        { t: "If she weren't so careful, she wouldn't have survived the storm.", ok: true },
        { t: "If she wasn't so careful, she wouldn't survive the storm." },
        { t: "If she weren't so careful, she didn't survive the storm." },
      ],
      why: "If she weren't so careful… wouldn't have survived — второй тип смешанного условного.",
    },
    {
      kind: "fill",
      stage: 0,
      tag: "Смешанное условное",
      qBefore: "If we ",
      qAfter: " the deadline, we wouldn't be celebrating tonight.",
      hintRu: "Если бы мы не уложились в срок, мы бы сегодня не праздновали. (причина в прошлом)",
      answer: "hadn't met",
      why: "If we hadn't met the deadline — Past Perfect: причина случилась в прошлом.",
    },
    {
      kind: "choice",
      stage: 1,
      tag: "Уверенное предположение",
      q: "Ты видишь пустую кофейную чашку на столе коллеги. «Она, должно быть, уже ушла». Как сказать?",
      note: "must have + V3 — почти уверен, что так и было.",
      options: [
        { t: "She must have already left.", ok: true },
        { t: "She must has already left." },
        { t: "She must already left." },
      ],
      why: "must have left — после модального глагола всегда have, а не has.",
    },
    {
      kind: "fill",
      stage: 1,
      tag: "Отрицательная уверенность",
      qBefore: "They ",
      qAfter: " have forgotten — they just called me an hour ago.",
      hintRu: "Они не могли забыть — они звонили мне час назад. (уверенность, что этого не было)",
      answer: "can't",
      why: "can't have forgotten — почти уверен, что событие НЕ произошло.",
    },
    {
      kind: "choice",
      stage: 1,
      tag: "Простая возможность",
      q: "«Возможно, он не увидел моё сообщение». Какая степень уверенности здесь нужна?",
      note: "might/could have — просто возможность, без уверенности в любую сторону.",
      options: [
        { t: "He might not have seen my message.", ok: true },
        { t: "He can't have seen my message." },
        { t: "He must not have seen my message." },
      ],
      why: "might not have seen — мягкое предположение, а не уверенность (can't) или почти-уверенность (must).",
    },
    {
      kind: "choice",
      stage: 1,
      tag: "Разница модальных",
      q: "В чём разница между «He must have left» и «He might have left»?",
      note: "must — почти уверен, might — просто одна из возможностей.",
      options: [
        { t: "must — говорящий почти уверен; might — просто предполагает", ok: true },
        { t: "Никакой разницы, это синонимы" },
        { t: "must — о будущем, might — о прошлом" },
      ],
      why: "must have — сильная уверенность, might have — мягкая возможность. Это ключевое различие уровня C1.",
    },
    {
      kind: "assemble",
      stage: 2,
      tag: "Финал",
      q: "Собери фразу, смешивающую обе темы юнита: «Если бы мы не поверили в идею, кто-то другой, должно быть, уже сделал бы это первым»:",
      note: "If we hadn't believed in the idea, someone else must have done it first — смешанное условное + предположение о прошлом.",
      words: ["If", "we", "hadn't", "believed", "in", "the", "idea,", "someone", "else", "must", "have", "done", "it", "first."],
      answer: "If we hadn't believed in the idea, someone else must have done it first.",
      why: "Смешанное условное (hadn't believed) и предположение (must have done) в одной фразе — ровно то, что нужно на уровне C1. Тренажёр пройден!",
    },
  ],
  words: [],
};

export default drills;
