import type { Chapter } from "@/lib/types";

const drills: Chapter = {
  slug: "drills-u5",
  title: "Тренажёр: сложные конструкции",
  subtitle: "Отработка юнита «Сложные конструкции»: причастные обороты и редуцированные придаточные.",
  section: "exercise",
  stages: [
    { icon: "✂️", name: "Причастные обороты" },
    { icon: "🔧", name: "Редуцированные" },
    { icon: "✅", name: "Готово" },
  ],
  steps: [
    {
      kind: "choice",
      stage: 0,
      tag: "Having + V3",
      q: "«Проработав пять лет в стартапах, она точно знала, какие риски того стоят». Выбери верный вариант:",
      note: "Having + V3 показывает завершённое до этого действие.",
      options: [
        { t: "Having worked in startups for five years, she knew exactly which risks were worth it.", ok: true },
        { t: "Working in startups for five years, she knew exactly which risks were worth it, five years ago." },
        { t: "Have worked in startups for five years, she knew exactly which risks were worth it." },
      ],
      why: "Having worked — причастный оборот с законченным до этого действием.",
    },
    {
      kind: "fill",
      stage: 0,
      tag: "V-ing причастие",
      qBefore: "",
      qAfter: " the risks clearly, they still decided to invest.",
      hintRu: "Ясно понимая риски, они всё равно решили инвестировать. (know → причастие)",
      answer: "Knowing",
      why: "Knowing the risks clearly — V-ing показывает одновременность причины и результата.",
    },
    {
      kind: "choice",
      stage: 0,
      tag: "Причастный оборот",
      q: "«Основанная в маленькой квартире, компания теперь работает в десяти странах». Выбери верный вариант:",
      note: "Founded — причастие от found, страдательный смысл (была основана).",
      options: [
        { t: "Founded in a small apartment, the company now operates in ten countries.", ok: true },
        { t: "Founding in a small apartment, the company now operates in ten countries." },
        { t: "Found in a small apartment, the company now operates in ten countries." },
      ],
      why: "Founded — причастие прошедшего времени (V3) показывает, что действие было совершено НАД компанией.",
    },
    {
      kind: "fill",
      stage: 1,
      tag: "Редуцированное придаточное",
      qBefore: "The report ",
      qAfter: " by the whole team took three weeks to finish.",
      hintRu: "Отчёт, написанный всей командой, занял три недели. (written → редуцированное придаточное вместо «that was written»)",
      answer: "written",
      why: "The report written by the whole team — сокращение от «that was written by the whole team».",
    },
    {
      kind: "choice",
      stage: 1,
      tag: "Редуцированное придаточное",
      q: "«Все, кто интересуется стажировкой, могут написать нам». Выбери сокращённый вариант:",
      note: "who are убирается перед interested.",
      options: [
        { t: "Anyone interested in the internship can write to us.", ok: true },
        { t: "Anyone who interested in the internship can write to us." },
        { t: "Anyone interesting in the internship can write to us." },
      ],
      why: "Anyone interested — who are убрано, interested остаётся само по себе.",
    },
    {
      kind: "fill",
      stage: 1,
      tag: "Редуцированное придаточное",
      qBefore: "The people ",
      qAfter: " this project have never met in person.",
      hintRu: "Люди, стоящие за этим проектом, никогда не встречались лично. (build → причастие)",
      answer: "building",
      why: "The people building this project — сокращение от «who build this project».",
    },
    {
      kind: "choice",
      stage: 1,
      tag: "Сравнение",
      q: "Какая версия звучит более естественно и компактно для делового текста?",
      note: "Причастные обороты и редуцированные придаточные делают текст короче и профессиональнее.",
      options: [
        { t: "Having tested the model for a year, the team felt confident about scaling it.", ok: true },
        { t: "The team tested the model for a year. After that, the team felt confident. They wanted to scale it." },
        { t: "The team, which tested the model, which took a year, felt confident about scaling it, which they wanted to do." },
      ],
      why: "Having tested the model for a year… — компактный, естественный вариант без лишних which/that.",
    },
    {
      kind: "assemble",
      stage: 2,
      tag: "Финал",
      q: "Собери фразу: «Проверенный сотнями пользователей, продукт был готов к запуску»:",
      note: "Tested by hundreds of users, the product was ready for launch.",
      words: ["Tested", "by", "hundreds", "of", "users,", "the", "product", "was", "ready", "for", "launch."],
      answer: "Tested by hundreds of users, the product was ready for launch.",
      why: "Tested by hundreds of users — причастный оборот в начале предложения. Тренажёр пройден!",
    },
  ],
  words: [],
};

export default drills;
