import type { Chapter } from "@/lib/types";

const drills: Chapter = {
  slug: "drills-u4",
  title: "Тренажёр: живой английский",
  subtitle: "Отработка юнита «Живой английский на высоком уровне»: фразовые глаголы, эллипсис, замещение.",
  section: "exercise",
  stages: [
    { icon: "🧩", name: "Фразовые глаголы" },
    { icon: "💬", name: "Эллипсис" },
    { icon: "✅", name: "Готово" },
  ],
  steps: [
    {
      kind: "fill",
      stage: 0,
      tag: "Фразовый глагол",
      qBefore: "We ",
      qAfter: " an idea for the new feature during lunch.",
      hintRu: "Мы придумали идею для новой функции во время обеда. (come up with)",
      answer: "came up with",
      why: "came up with — прошедшее время фразового глагола «придумать».",
    },
    {
      kind: "choice",
      stage: 0,
      tag: "Фразовый глагол",
      q: "«Давай свяжемся на следующей неделе». Какой глагол уместен?",
      note: "touch base — коротко связаться по делу.",
      options: [
        { t: "Let's touch base next week.", ok: true },
        { t: "Let's touch down next week." },
        { t: "Let's touch up next week." },
      ],
      why: "touch base — коротко связаться; touch down означает «приземлиться», touch up — «подретушировать».",
    },
    {
      kind: "fill",
      stage: 0,
      tag: "Фразовый глагол",
      qBefore: "We still have a few details to ",
      qAfter: " before signing.",
      hintRu: "Нам нужно уладить несколько деталей перед подписанием. (iron out)",
      answer: "iron out",
      why: "iron out — «уладить» разногласия или детали.",
    },
    {
      kind: "choice",
      stage: 0,
      tag: "Фразовый глагол",
      q: "«Можно я покажу тебе эту идею перед встречей?» Какой фразовый глагол верный?",
      note: "run something by someone.",
      options: [
        { t: "Can I run this idea by you before the meeting?", ok: true },
        { t: "Can I run this idea over you before the meeting?" },
        { t: "Can I run this idea for you before the meeting?" },
      ],
      why: "run something by someone — посоветоваться, показать на проверку.",
    },
    {
      kind: "choice",
      stage: 1,
      tag: "Эллипсис",
      q: "— «Are you free tonight?» — «I think so.» Что означает короткий ответ?",
      note: "I think so заменяет целую фразу.",
      options: [
        { t: "«Думаю, да» — заменяет «I think I am free tonight»", ok: true },
        { t: "«Я так не думаю» — отрицательный ответ" },
        { t: "«Я думаю об этом» — размышление вслух" },
      ],
      why: "I think so — короткая замена длинной положительной фразы.",
    },
    {
      kind: "fill",
      stage: 1,
      tag: "Замещение",
      qBefore: "— I loved the talk. — I did ",
      qAfter: ".",
      hintRu: "— Мне понравилось выступление. — Мне тоже. (замещение вместо повтора глагола)",
      answer: "too",
      why: "I did too — замещает «I loved the talk too», избегая повтора.",
    },
    {
      kind: "choice",
      stage: 1,
      tag: "Эллипсис в вопросе",
      q: "За ужином кто-то предлагает десерт коротким вопросом. Какой вариант естественнее для непринуждённой беседы?",
      note: "Want some? — сокращение от Do you want some?",
      options: [
        { t: "Want some?", ok: true },
        { t: "Do you desire to have some of it?" },
        { t: "Would you be interested in consuming some?" },
      ],
      why: "Want some? — естественное разговорное сокращение, уместное за столом с друзьями.",
    },
    {
      kind: "assemble",
      stage: 2,
      tag: "Финал",
      q: "Собери фразу с фразовым глаголом и замещением: «Если мы сможем масштабировать это, они тоже смогут»:",
      note: "If we can scale this up, they can too — scale up + замещение can too.",
      words: ["If", "we", "can", "scale", "this", "up,", "they", "can", "too."],
      answer: "If we can scale this up, they can too.",
      why: "scale this up + can too — фразовый глагол и естественное замещение в одной фразе. Тренажёр пройден!",
    },
  ],
  words: [],
};

export default drills;
