import type { Chapter } from "@/lib/types";

const exam: Chapter = {
  slug: "exam",
  title: "Экзамен уровня C1",
  subtitle:
    "Финальное испытание сезона: смешанные условные, эмфаза и инверсия, формальный язык, живая речь, причастные обороты и риторика — без упрощений.",
  exam: true,
  stages: [
    { icon: "🌀", name: "Условные и модальные" },
    { icon: "⚡", name: "Эмфаза" },
    { icon: "🎩", name: "Формальный язык" },
    { icon: "🧩", name: "Живая речь" },
    { icon: "🎓", name: "Результат" },
  ],
  steps: [
    {
      kind: "choice",
      stage: 0,
      tag: "Смешанное условное",
      q: "«Если бы я не рискнул тогда, у меня не было бы этой карьеры сейчас». Какой вариант верный?",
      rule: "mixed-conditionals",
      options: [
        { t: "If I hadn't taken the risk then, I wouldn't have this career now.", ok: true },
        { t: "If I didn't take the risk then, I wouldn't have this career now." },
        { t: "If I hadn't taken the risk then, I won't have this career now." },
      ],
      why: "Причина в прошлом (hadn't taken) → результат в настоящем (wouldn't have) — классическое смешанное условное.",
    },
    {
      kind: "fill",
      stage: 0,
      tag: "Предположение о прошлом",
      qBefore: "She ",
      qAfter: " have known about the deadline — she asked about it yesterday.",
      hintRu: "Она, должно быть, знала о сроке — она спрашивала о нём вчера. (уверенное предположение)",
      answer: "must",
      why: "must have known — уверенное предположение о прошлом.",
    },
    {
      kind: "choice",
      stage: 0,
      tag: "Отрицательная уверенность",
      q: "«Не может быть, чтобы они уже приняли решение — совещание ещё идёт». Какой вариант верный?",
      options: [
        { t: "They can't have made the decision already — the meeting is still going on.", ok: true },
        { t: "They mustn't have made the decision already — the meeting is still going on." },
        { t: "They don't have made the decision already — the meeting is still going on." },
      ],
      why: "can't have made — уверенность, что событие НЕ произошло.",
    },
    {
      kind: "choice",
      stage: 1,
      tag: "Расщеплённое предложение",
      q: "Ты хочешь выделить именно бесплатный доступ как главную причину успеха. Какой вариант верный?",
      rule: "cleft-sentences",
      options: [
        { t: "It was free access that made the biggest difference.", ok: true },
        { t: "Free access was that made the biggest difference." },
        { t: "It was that free access made the biggest difference." },
      ],
      why: "It was free access that… — расщеплённая конструкция для выделения конкретного элемента.",
    },
    {
      kind: "fill",
      stage: 1,
      tag: "Инверсия",
      qBefore: "Not only ",
      qAfter: " we launch on time, we also stayed under budget.",
      hintRu: "Мы не только запустились вовремя, но и уложились в бюджет. (вспомогательный глагол выходит вперёд)",
      rule: "inversion",
      answer: "did",
      why: "Not only did we launch — did выходит перед we после Not only.",
    },
    {
      kind: "choice",
      stage: 1,
      tag: "Инверсия",
      q: "«Редко встретишь такую преданную команду». Какой вариант верный?",
      options: [
        { t: "Rarely do you meet such a dedicated team.", ok: true },
        { t: "Rarely you meet such a dedicated team." },
        { t: "You rarely do meet such a dedicated team." },
      ],
      why: "Rarely do you meet — инверсия обязательна после ограничительного наречия Rarely.",
    },
    {
      kind: "choice",
      stage: 2,
      tag: "Номинализация",
      q: "«Улучшение вовлечённости было значительным» — выбери формальный вариант с существительным:",
      rule: "nominalization",
      options: [
        { t: "The improvement in engagement was significant.", ok: true },
        { t: "We improved engagement significantly, which was good." },
        { t: "The improving of engagement was significant." },
      ],
      why: "improvement — номинализация от improve.",
    },
    {
      kind: "fill",
      stage: 2,
      tag: "Hedging",
      qBefore: "It ",
      qAfter: " be argued that trust was the key factor.",
      hintRu: "Можно утверждать, что доверие было ключевым фактором. (смягчённая формулировка)",
      rule: "hedging",
      answer: "could",
      why: "It could be argued that… — типичная hedging-конструкция.",
    },
    {
      kind: "choice",
      stage: 2,
      tag: "Формальная связка",
      q: "«Несмотря на трудности, проект был завершён вовремя». Выбери самый формальный вариант:",
      rule: "formal-connectors",
      options: [
        { t: "Notwithstanding the challenges, the project was completed on time.", ok: true },
        { t: "Despite the challenges, no big deal, the project was done on time." },
        { t: "There were challenges, but the project was done on time anyway." },
      ],
      why: "Notwithstanding — самый формальный вариант из трёх.",
    },
    {
      kind: "choice",
      stage: 3,
      tag: "Фразовый глагол",
      q: "«Нам нужно уладить последние детали контракта». Выбери верный фразовый глагол:",
      rule: "phrasal-verbs-advanced",
      options: [
        { t: "We need to iron out the last details of the contract.", ok: true },
        { t: "We need to iron up the last details of the contract." },
        { t: "We need to iron the last details of the contract out over." },
      ],
      why: "iron out — «уладить» разногласия или детали.",
    },
    {
      kind: "choice",
      stage: 3,
      tag: "Причастный оборот",
      q: "«Проработав годы в этой сфере, она точно знала, что делать». Выбери верный вариант:",
      rule: "participle-clauses",
      options: [
        { t: "Having worked in the field for years, she knew exactly what to do.", ok: true },
        { t: "Working in the field for years ago, she knew exactly what to do." },
        { t: "Have worked in the field for years, she knew exactly what to do." },
      ],
      why: "Having worked — причастный оборот с действием, завершённым до основного.",
    },
    {
      kind: "choice",
      stage: 3,
      tag: "Редуцированное придаточное",
      q: "«Статья, опубликованная на прошлой неделе, привлекла много внимания». Выбери сокращённый вариант:",
      rule: "reduced-relatives",
      options: [
        { t: "The article published last week got a lot of attention.", ok: true },
        { t: "The article which published last week got a lot of attention." },
        { t: "The article publishing last week got a lot of attention." },
      ],
      why: "The article published last week — which was убрано, published осталось как причастие.",
    },
    {
      kind: "reading",
      stage: 4,
      tag: "Чтение",
      title: "Экзаменационный отрывок",
      note: "Прочитай короткий отрывок и ответь на вопросы — без адаптации, как в настоящем тексте уровня C1.",
      text: [
        "Having spent a decade building something meant to be free, Alim had grown used to a particular kind of question: not «how much does it cost?» but «why isn't everyone doing this?» It was a question he still couldn't fully answer — and, in a strange way, he had stopped trying to.",
        "What mattered, he had come to believe, was not the answer but the asking. Every learner who opened the app for the first time was, in effect, asking the same question in a different form: can this be for me too? Notwithstanding every doubt he'd ever had about the project, the answer to that one had always, stubbornly, been yes.",
      ],
      questions: [
        {
          q: "Какой вопрос люди чаще всего задавали Алиму о проекте?",
          options: [
            { t: "«Почему этим не занимаются все?», а не «сколько это стоит?»", ok: true },
            { t: "«Когда вы продадите компанию?»" },
            { t: "«Почему это платно?»" },
          ],
          why: "not «how much does it cost?» but «why isn't everyone doing this?» — расщеплённое противопоставление двух вопросов.",
        },
        {
          q: "Что, по мнению Алима, было важнее самого ответа?",
          options: [
            { t: "Сам факт того, что вопрос задают", ok: true },
            { t: "Скорость, с которой он отвечал" },
            { t: "Количество вопросов в день" },
          ],
          why: "What mattered… was not the answer but the asking — ещё одна расщеплённая конструкция, теперь без it was.",
        },
        {
          q: "Каким, несмотря на все сомнения, всегда оставался ответ Алима?",
          options: [
            { t: "«Да» — этот проект может быть и для тебя", ok: true },
            { t: "«Пока рано об этом говорить»" },
            { t: "«Нет, это не для всех»" },
          ],
          why: "Notwithstanding every doubt… the answer to that one had always, stubbornly, been yes — формальная связка Notwithstanding вводит финальную мысль.",
        },
      ],
    },
    {
      kind: "listening",
      stage: 4,
      tag: "Аудирование",
      intro: "Финальная строка курса",
      note: "Экзамен на слух — без текста на экране, только звук.",
      audio: [
        "It was people like you who made me want to build it in the first place.",
      ],
      questions: [
        {
          q: "На кого делается акцент в этой фразе?",
          options: [
            { t: "На собеседнике («people like you»), а не на самом говорящем", ok: true },
            { t: "На самом говорящем" },
            { t: "На технологии, которая была построена" },
          ],
          why: "It was people like you who… — расщеплённая конструкция ставит акцент на people like you, не на I.",
        },
      ],
    },
  ],
  words: [],
};

export default exam;
